### ISSUE TITLE
Interactive strategic plan URL is broken

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1028]
- Visit `/budget/strategic-plan/`
- Click Interactive URL for `/budget/strategic-plan/interactive/`
- Get Django default 404.

cc @kave @kurtw

**Comment by kurtw** [comment]
So when DEBUG = True, it won't render out 404 view. If you turn debug off then you'll see the correct page displayed, however you also won't get the static assets because when DEBUG is off django won't do the configuration to render those things. (on the servers that's handled by apache)

**Comment by anselmbradford** [comment]
So is `DEBUG = True` set on flapjack.demo then? Because it's the proper 404 on [flapjack.demo]/budget/strategic-plan/interactive/, but it should be the interactive strategic plan page not a 404.

Should look like [refresh.demo]/budget/strategic-plan/interactive/

**Comment by KimberlyMunoz** [comment]
Related bug: #867

**Comment by KimberlyMunoz** [comment]
This particular issue was fixed when we moved to wagtail.
