### ISSUE TITLE
IE8 - mega menu is blank

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1029]
![screen shot 2015-09-25 at 5 24 33 pm](https://cloud.githubusercontent.com/assets/704760/10112812/42f00a76-63ac-11e5-9785-045ea2053338.png)

**Comment by anselmbradford** [comment]
Maybe fix https://github.com/cfpb/cfgov-refresh/issues/963 at the same time.

**Comment by jimmynotjim** [comment]
Well then...
