### ISSUE TITLE
Make setup.sh default to development environment?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1079]
Would it make more sense to have `./setup.sh` run the local setup by default and have something like `./setup.sh production` that would be run in the production scripts. It seems like humans need to type `./setup.sh local`, while if the command-line flag was set instead on production it would be hardcoded, right? (At least in Travis.) What do you think? cc @kave @kurtw @rosskarchner

**Comment by kave** [comment]
doesn't sound unreasonable, would help relieve issues of people forgetting to include `local` as a param

**Comment by Scotchester** [comment]
:+1:

**Comment by kurtw** [comment]
That sounds good to me, though I do like knowing exactly which environment is being loaded just by looking at the command.

**Comment by kurtw** [comment]
Especially when looking in Jenkins.

**Comment by jimmynotjim** [comment]
:+1: @kurtw how do you know which is being run in Jenkins now?

**Comment by anselmbradford** [comment]
> That sounds good to me, though I do like knowing exactly which environment is being loaded just by looking at the command.

This would still be possible, right? It'd just be the reverse of what is currently happening. Like now `base` is implied, and `local` builds on that, but instead the dev settings are implied.

`./setup.sh` = local deploy
`./setup.sh production` = production deploy (or whatever you want to call it.
