### ISSUE TITLE
`settings.` and `options.` doc format?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1083]
We have two formats for documenting when a `settings` or [`options`](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/jinja2/v1/_includes/macros/video-player.html#L11-L22) object is passed to a macro:

(A)
```
settings:

      heading:   Heading text.
      intro:     Body introduction text.
      body:      Body text.

      link_url:  Link URL.
      link_text: Link text.
```

AND

(B)
```
   settings:           An object with the following options for settings.

   settings.heading:   Heading text.
   settings.intro:     Body introduction text.
   settings.body:      Body text.

   settings.link_url:  Link URL.
   settings.link_text: Link text.
```

Preference for one or the other?

**Comment by sebworks** [comment]
I would prefer not to use the YAML style format (A). I think (B) is closer to JSON which we are using in our Javascript.

**Comment by jimmynotjim** [comment]
Ditto @sebworks, it's certainly easier to scan if there's multiple parent args.

**Comment by anselmbradford** [comment]
Updated to (B) in https://github.com/cfpb/cfgov-refresh/pull/1062
