### ISSUE TITLE
links.sh still needed?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1097]
https://github.com/cfpb/cfgov-refresh/blob/flapjack/links.sh

Is this still needed with the new backend updates? 

cc @kave @rosskarchner @kurtw

**Comment by rosskarchner** [comment]
I have never seen or run this script before, and it's not referenced elsewhere in the repo. I think it can die.

**Comment by Scotchester** [comment]
Hang on. Isn't this needed for the ability to show the interstitial page when linking to an external site? It may be that it's no longer needed with the new back end, but I just wanted to make sure we all know what it is we're talking about.

**Comment by kurtw** [comment]
There's a JS module that is executed for each link visited which checks the URL against a regex to determine if it's an external link. That was the purpose of links.sh so it seems that it's useless after all.

**Comment by Scotchester** [comment]
Uhhhhhhhhhh. I seriously dislike the idea of checking every clicked link with JS. Won't that be a serious drag on performance? Am I missing something?

**Comment by kurtw** [comment]
@sebworks?

**Comment by sebworks** [comment]
It is needed because we don't want the users to be able to redirect to any random external page by passing in a query-string parameter. We still need to implement the functionality on the server. There might be a better way to do it without using links.sh.

**Comment by sebworks** [comment]
@Scotchester, there certainly is a performance cost associated with intercepting every link click and running the regex.  I'm open to ideals on how this can be done in a more efficient manner.

**Comment by rosskarchner** [comment]
at long last, links.sh is gone.

**Comment by kurtrwall** [comment]
Praise @dpford
