### ISSUE TITLE
Move prototype pages to /proto/ URL

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1135]
Instead of creating new entries in `cfgov/cfgov/urls.py` for each prototype page, how about we move them all to a `localhost:8000/proto/*` parent directory and just ignore that path? Would this work @kurtw ? This would also separate our prototype paths from production paths in the file structure.

**Comment by KimberlyMunoz** [comment]
If it works, I think this is a better solution. :+1:

**Comment by kurtw** [comment]
Hmm. So are you just looking to support another set of url patterns? This broader conversation is starting to sound like we want a `proto` app where we can experiment without screwing around in our official v1 app.

**Comment by anselmbradford** [comment]
I'd be on board with a proto app if that makes the most sense. I'm not too keen on the mix of prototype and production code we currently have going on. This also would be a preview of what things like OAH would look like integrated into the project, right?

**Comment by kurtw** [comment]
>This also would be a preview of what things like OAH would look like integrated into the project, right?
As in, OAH could look at the app and see how things would look?

**Comment by anselmbradford** [comment]
> As in, OAH could look at the app and see how things would look?

As when OAH is added to our architecture it'll be an app, right? So we can see how that looks and OAH can as well.

**Comment by kurtw** [comment]
Oh I see. Kind of. See that comment on what I think we should consider about the site.

https://github.com/cfpb/cfgov-refresh/issues/1137#issuecomment-154086963

**Comment by KimberlyMunoz** [comment]
We're at the stage where prototype pages are both prototypes and templates and it seems to be working pretty well. I'm going to close, but I think we could re-open and revisit in v2!
