### ISSUE TITLE
Check how phone numbers are formatted/entered

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1146]
**50-50 Image Text Molecule**
- [x] Change "Is widescreen" to "Use 16:9 image"
- [x] Change "is button" to "Show link as button"
- [x] Enable the ability for multiple links with the 50-50 image. (Also an issue for 75-25 text-image)
- [x] Eliminate the "image path" field and replace with the wagtail image selector

**Contact molecule**
- [x] Examine the character limit for contact titles from 22 to something that can fit the full name of OMWI and Servicemembers office. `office of minority and women inclusion` or `office of servicemembers and veterans affairs`
- [ ] Is there a way to signal to content how the phone numbers should be inputted?
- [ ] The macro for formatting number works with 10 character phone numbers, but the character limit is 15. What happens with those extra characters?

**Comment by kave** [comment]
@KimberlyMunoz have the contact molecule issues been resolved?

**Comment by KimberlyMunoz** [comment]
I think so. I'll check today.
