### ISSUE TITLE
Press Resources design tweaks for the "Press Contacts" section

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cfgov-refresh#115]
- [x] I noticed that the headers on that page have 30px margins under them which is larger than the normal heading margin when they are headers for just text. Maybe we can call them `.content_block-header` or something and give them the 30px margins?
- [x] The intro text "We are committed to engaging..." is in Georgia but it should be Avenir Regular. You can use the new `.short-desc` class to fix that.
![image](https://cloud.githubusercontent.com/assets/1093373/3797872/8c1b6ee6-1bde-11e4-9ae8-474808e783ec.png)
- [ ] This looks like the first time we're actually collapsing some content.
![image](https://cloud.githubusercontent.com/assets/1093373/3797968/784d348e-1bdf-11e4-86a3-f25a4c9698e6.png)

**Comment by anselmbradford** [comment]
Can this be closed? Doesn't appear the expandables are used in the Press Contacts anymore.

**Comment by Scotchester** [comment]
I think the original idea was to collapse them on mobile viewports, but I don't know how important that is. Check with Design/UX before closing.

**Comment by duelj** [comment]
Yup! Sounds like we are all set on this the contacts are not being hidden. Thanks all!
