### ISSUE TITLE
Update ESLint settings for consistent bracket handling

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1150]
See https://github.com/cfpb/cfgov-refresh/pull/1134/files#r44039211

Any preference for a space in the brackets vs no space?

**Comment by Scotchester** [comment]
I'm against spaces in square brackets, because they rarely are passed in stuff complex enough to warrant them, except in the case of a literal array definition, as noted in your comment.

**Comment by anselmbradford** [comment]
`.eslintrc` file in the cfgov-refresh repo needs to be updated, as does the one in https://github.com/cfpb/capital-framework/blob/canary/.eslintrc and https://github.com/cfpb/development/blob/master/.eslintrc

**Comment by anselmbradford** [comment]
I think we can close this, if we update the linter, it'll autofix the spacing with `--fix` and the only preference noted above is to keep it the way it is.
