### ISSUE TITLE
Add path resolver npm module

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1201]
See https://github.com/cfpb/cfgov-refresh/pull/1189#issuecomment-161723605

Ideally we'd have a module to resolve relative paths where require statements have deep relative paths, especially in the cases of JS found in the acceptance and unit tests.

**Comment by sebworks** [comment]
This issue is no longer relevant. There are plenty of NPM modules which could remedy this issue.
