### ISSUE TITLE
Text styling in hero, 25/75, disclaimer.

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1206]
Text in Hero, 25/75 organsim and disclaimer text in the email organsim isn't styled. Data & Research page preview is a good example.  @KimberlyMunoz @jimmynotjim @anselmbradford @sebworks

**Comment by kave** [comment]
@tnferrell resolved it'll be fixed in the next refresh push

**Comment by tnferrell** [comment]
The hero looks fixed, but the 25/75 and disclaimer text still look off.

**Comment by tnferrell** [comment]
The spacing between link and text in the 25/75 also looks like it varies depending on how many 25/75 are stacked. You can compare /consumer-help and /data-research.

**Comment by kave** [comment]
@jimmynotjim hey when you create a PR for the disclaimer text on Email Sign up could you link it here?

**Comment by jimmynotjim** [comment]
Thanks for the reminder, this fell off my radar. PR opened here https://github.com/cfpb/cfgov-refresh/pull/1231. It's more than just the small change, I updated everything to use our latest and greatest data prototyping and included it all in the landing page so we can actually see what's going on.

**Comment by tnferrell** [comment]
Hey guys, I'm still noticing something wonky on the 25/75 one of my pages - /consumer-help/managing-credit/

**Comment by jimmynotjim** [comment]
It looks like Wagtail is doing something funky with the markup output. @kave or @kurtw, any ideas?

This is the rendered markup:

![screen shot 2016-01-05 at 12 24 15 pm](https://cloud.githubusercontent.com/assets/1280430/12122152/4f5c8f14-b3a7-11e5-8761-f3f2b0843549.png)

And this is [the source](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/jinja2/v1/_includes/molecules/image-text-25-75.html#L84):

```
<p class="short-desc">{{ value.body.source | safe }}</p>
```

Not really sure why it's stripping the `p` tags in the markup and inserting it's own.

**Comment by anselmbradford** [comment]
Looks like `value.body.source` is wrapped in a `<p>` tag. Can't put `<p>` inside of `<p>` so the browser kicks them to the outside and leaves an empty paragraph with a new one below.

**Comment by kave** [comment]
@jimmynotjim @anselmbradford yup thats exactly it. the fix would be:
```
<div class="short-desc">
{{value.body.source}}
</div>
```

**Comment by jimmynotjim** [comment]
There's no `short-desc` on this one, it should be the serif font, so we just need `{{ value.body.source }}`?

**Comment by KimberlyMunoz** [comment]
Yep. That should be it. File a quick fix PR to flapjack?

**Comment by jimmynotjim** [comment]
Crud, I commented on the wrong one. Too many nested `p` tags. This one does need the short-desc class name. I can update this if no one else already has.

**Comment by jimmynotjim** [comment]
These are fixed in code and will be updated after the next refresh push
