### ISSUE TITLE
Page Specific JS 

### ISSUE THREAD

**Issue by kave** [cfpb/cfgov-refresh#1211]
With our transistion to wagtail, URL's can now be dynamically created/edited/deleted in real-time. With that brings a new problem of loading page-specific JS since the previous method was statically creating these routes on the backend because URLs were unchanged and decided upon before.

A tentative solution is upon page creation/edits/deletion, a JSON file is created that houses the page details such as `slug` and `atomic-elements`.
This then triggers a gulp task on the backend to use the existing page-specific loading method and creates these directories with their JS related to the atomic elements on the fly.
https://github.com/cfpb/cfgov-refresh/pull/1200

**Comment by KimberlyMunoz** [comment]
Did you all fix this @anselmbradford and @kave?

**Comment by kave** [comment]
@KimberlyMunoz yup thanks for the reminder. it was fixed here https://github.com/cfpb/cfgov-refresh/pull/1253
