### ISSUE TITLE
Gray well organism needs option for 2 columns

### ISSUE THREAD

**Issue by schaferjh** [cfpb/cfgov-refresh#1218]
Per team discussion during working session 12/11/15:

We want gray wells to be somewhat short so that they don't occupy a lot of height on the page. Allowing two columns within the well would support this design and content goal. We'll want to be able to choose this option within the CMS.

During the working session we discussed modifying the **half width link blob** so that just the text portion could be used, then two could be placed next to each other within the **gray well** organism to accommodate this functionality change. @jimmynotjim may be able to explain the proposed solution better.

Also tagging @tnferrell as an FYI since I can't find Laura S.'s handle.

**Comment by jimmynotjim** [comment]
Essentially. We'd split the __half width link blob__ into a parent __half width__ organism, and child __link blob__ molecule. We could then use the __half width__ organism elsewhere and for other molecules, like within the __gray well__.

**Comment by KimberlyMunoz** [comment]
Would the Half-Width organism be used in the 50-50-text-image organism?

**Comment by jimmynotjim** [comment]
I think it could.

**Comment by kurtw** [comment]
This sounds good. We'll need a list of molecules to include as "children" of the half width organism.

**Comment by schaferjh** [comment]
Low priority as we no longer need this for V1 migration.

**Comment by anselmbradford** [comment]
Closing, it'll be recreated if a request for this comes up again.
