### ISSUE TITLE
Need the filterable list of post-preview organisms for sub-landing pages

### ISSUE THREAD

**Issue by sarahsimpson09** [cfpb/cfgov-refresh#1244]
Was slated to be used only for browse filterable pages, but we'll need it to display the most recent reports on Data & Research > Research Reports sublanding page.

**Comment by jimmynotjim** [comment]
Will it include the filters or just the previews?

**Comment by sarahsimpson09** [comment]
Just the previews!

**Comment by jimmynotjim** [comment]
Ok, thanks

**Comment by schaferjh** [comment]
Fairly positive this need for showing Post preview items on a sub-landing page has been addressed -- @kurtw or @kave can you confirm? If yes, let's close this issue.

**Comment by kurtw** [comment]
I can confirm that it's available for _sub-landing_ pages, however Data & Research is a Landing page. Do we need to add that to Landing pages now?

**Comment by sarahsimpson09** [comment]
No landing pages, just sub-landing. Thanks everyone!
