### ISSUE TITLE
Need single form field w/ button for Wagtail sublanding pages

### ISSUE THREAD

**Issue by sarahsimpson09** [cfpb/cfgov-refresh#1246]
I need to be able to add the single form field w/ button molecule to the sublanding page template

**Comment by kave** [comment]
@sarahsimpson09 do you mean in the main content area or the side bar?

**Comment by kave** [comment]
@sarahsimpson09 could you close this if its no longer an issue

**Comment by KimberlyMunoz** [comment]
I don't see where this form field is required in GHE/flapjack/Modules-V1/wiki/Sub-landing-page-template

@schaferjh or @sarahsimpson09 can you weigh in?

**Comment by schaferjh** [comment]
I think this comes from @sarahsimpson09 wanting to create the email sign up before that organism was done -- but now it is, so I don't think this is an issue anymore, right?

**Comment by KimberlyMunoz** [comment]
In that case, the email sign-up is in and this issue is ready to close. Reopen this if I'm completely wrong.

**Comment by sarahsimpson09** [comment]
Sorry--this was for one of the credit card agreement database pages when I thought we'd be moving them into a template instead of forklifitng, trying to anticipate what we'd need. I think I wasn't looking at the site map when I created this issue. Sorry! Thought I closed it a while ago!
