### ISSUE TITLE
content portion not showing up on wagtail sublanding drafts

### ISSUE THREAD

**Issue by michaelrivera03** [cfpb/cfgov-refresh#1262]
I'm running into issues viewing pre-drafted content on wagtail. Thinking it might be linked to the related content sidebar issue, but I get errored out before I can remove.

![image](https://cloud.githubusercontent.com/assets/14353344/11981246/dee2abca-a96e-11e5-856e-503805e10843.png)

![image](https://cloud.githubusercontent.com/assets/14353344/11981253/f51d2ac8-a96e-11e5-9135-1b5613a2dc64.png)

**Comment by kave** [comment]
@michaelrivera03 of your created pages, which one are you seeing this problem?

**Comment by michaelrivera03** [comment]
@kave - Still can't add content. I was able to get related content removed, the preview still links to a 500 error
http://refresh.demo.cfpb.gov/admin/pages/29/edit/ - Managing Your Credit
http://refresh.demo.cfpb.gov/admin/pages/28/edit/ - Your Money, Your Goals
http://refresh.demo.cfpb.gov/admin/pages/27/edit/ - Managing someone else's money

**Comment by kave** [comment]
page had been corrupted. re-creating pages resolved issues
