### ISSUE TITLE
Discuss required elements on Landing & Sublanding pages

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1269]
For Text Introduction molecule, it seems that Wagtail is treating Links as required. They shouldn't be required, per wiki.

For 25/75 and 50/50 molecules, it seems that there's a group heading that's required. Per wiki, there is a required heading but that should be for individual 25/75 entries and not for the whole group.

In the E-Mail Signup organism, something called an ID is required. Not sure what this is and per wiki, there should be no required elements.

**Comment by kave** [comment]
@Schlachtmeyer Hi this should be resolved now, please verify this is the case

**Comment by Schlachtmeyer** [comment]
@kave - I'll get in this afternoon and work it through & let you know. Thx!

**Comment by kave** [comment]
@Schlachtmeyer hi could you close this if its no longer an issue?

**Comment by Schlachtmeyer** [comment]
I think this is resolved - thanks!
