### ISSUE TITLE
Wagtail & other issues: Credit Discrimination Sublanding page

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1278]
![creditdiscrimination_sublanding](https://cloud.githubusercontent.com/assets/14129916/12039846/f34558fc-ae31-11e5-95ae-6b45dc75987a.png)

Featured Content is showing markup tags -- I have tried to fix this in Wagtail and I can't seem to

@sarahsimpson09 @tnferrell @schaferjh -- This page needs to be broken up differently (I think) or else made into a Browse page? Any thoughts on how to configure this differently?

**Comment by kave** [comment]
@Schlachtmeyer hmm i'll look into this mark up issue

**Comment by schaferjh** [comment]
According to the most recent sitemap, this page is a browse page, underneath the "Managing your credit" sublanding page. Let's touch base when everyone is back next week to make sure we're in agreement on that.

**Comment by Schlachtmeyer** [comment]
Update: The sidebar looks better now I think.

This will be moved to a browse page eventually, just putting this here to illustrate that the stray coding tags are cleaned up now.

![creditdiscrimination_featured_0106](https://cloud.githubusercontent.com/assets/14129916/12122234/c3cfdae0-b3a7-11e5-9888-e0bad3772e05.png)

**Comment by kave** [comment]
great thanks :+1:
