### ISSUE TITLE
Wagtail & other issues: Retirement Sublanding page

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1279]
![retirement_sublanding](https://cloud.githubusercontent.com/assets/14129916/12039888/55036b60-ae32-11e5-8f26-9c98e2b512d7.png)

Some of the same issues as #1277 
- Spacing generally okay?
- Spacing in E-Mail Signup okay?
- Heading in E-Mail Signup needs attention from Content

**Comment by kave** [comment]
@KimberlyMunoz @sebworks

**Comment by KimberlyMunoz** [comment]
Hey @Schlachtmeyer or @schaferjh, is there a breakout sidebar for this page? If there isn't it might make more sense to move the text introduction under the bar by deleting the text introduction in the "header" section and moving it to the top "content" section.

**Comment by Schlachtmeyer** [comment]
Oh I see what you're saying. I'll try it. Thanks.

**Comment by Schlachtmeyer** [comment]
@KimberlyMunoz is this what you meant? Seems like it has shifted the spacing issue but not exactly fixed it. Or were you suggesting something different?

![retirement_sublanding_altheader](https://cloud.githubusercontent.com/assets/14129916/12055733/dbf7ce24-aefd-11e5-9312-4f42a1a95c0b.png)

**Comment by KimberlyMunoz** [comment]
Yep. That top spacing issue should be fixed in #1283.

**Comment by Schlachtmeyer** [comment]
I see. We'll wait for the next push on Tuesday then?

**Comment by KimberlyMunoz** [comment]
Yep. And I have some fixes for the Email Signup.

The Slug should be `Stay Informed`
The text in the slug `Subscribe to get information...` should be in text
The phrase `Email Address` should be under label, that's important for accessibility and should be marked as required.

There's still a slight spacing issue that I'm looking into fixing.

**Comment by Schlachtmeyer** [comment]
Great - got it. I'll implement this in all my pages with e-mail signups.

@sarahsimpson09 @tnferrell - How important is it to carry back this text to the content drafts? As we make changes inside the CMS, do we need to keep the content drafts updated for stakeholders?

**Comment by Schlachtmeyer** [comment]
@KimberlyMunoz - The spacing looks much better when I select the "Type" as "Email"

![email_rev](https://cloud.githubusercontent.com/assets/14129916/12056780/72d1a266-af08-11e5-92be-5fbd1efedd15.png)

**Comment by Schlachtmeyer** [comment]
Cannot see this page in the V1 Wagtail space right now...will keep looking.

**Comment by KimberlyMunoz** [comment]
I found it under Consumer Help/Planning for Retirement

**Comment by KimberlyMunoz** [comment]
It looks good to me. Re-open if you see another issue.
