### ISSUE TITLE
Wagtail & other issues: Research Reports Sublanding page

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1280]
![researchreports_sublanding](https://cloud.githubusercontent.com/assets/14129916/12040079/c13b8d98-ae33-11e5-9b9c-240822034464.png)

- No sidebar is appearing, I think because the Related Content isn't working?
- Is there a way to add the latest or featured Reports to the content of this page, using the Post Preview molecule? (Will the Events landing page also need this?)

**Comment by kave** [comment]
@Schlachtmeyer So the only element you have on this page is the related posts element. Which is doing expected behavior. 
Currently the only pages you can relate are `Event` pages using wagtail `tags` found in the `Configuration` tab

**Comment by kave** [comment]
@Schlachtmeyer you could use the FeaturedContent molecule to feature a page?

**Comment by Schlachtmeyer** [comment]
Thanks @kave - I'll circle back with content folks to figure this out. We have to display as much detail on the reports as we have on the current page, http://www.consumerfinance.gov/reports/ -- and those are essentially fully-loaded Post Preview molecules.

**Comment by KimberlyMunoz** [comment]
Related posts is fixed. The Post preview molecule will be tracked in #1244
