### ISSUE TITLE
Wagtail & other issues: Trouble with icons and fields inside Wagtail

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1282]
![linkblobs](https://cloud.githubusercontent.com/assets/14129916/12040209/f5b5112e-ae34-11e5-8562-1bace5846a4f.png)

I end up with a bunch of typos and missing letters because the icons are overprinting the fields inside Wagtail. What can I do to avoid this? Is it a browser issue or something?

**Comment by kave** [comment]
@Schlachtmeyer hmm maybe a browser issue, can you try using chrome

**Comment by KimberlyMunoz** [comment]
Did using Chrome fix this issue, @Schlachtmeyer?

**Comment by Schlachtmeyer** [comment]
Haven't tried it yet but I will!
