### ISSUE TITLE
Full width button modifier

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#1307]
There's a few uses of full-width buttons. We should consider adding a `btn_full-on-bp-xs` modifier and updating them where applicable.

**Comment by KimberlyMunoz** [comment]
There's one in the footer that's only visible on mobile. Add more to this thread if you see others.

**Comment by KimberlyMunoz** [comment]
> It's also used in the hero if the link is a button
It's used in the form submit button

**Comment by jimmynotjim** [comment]
This is now in Capital Framework => https://github.com/cfpb/capital-framework/pull/483
