### ISSUE TITLE
Rows built below first set of rows on table molecules not showing on preview pages

### ISSUE THREAD

**Issue by michaelrivera03** [cfpb/cfgov-refresh#1318]
![image](https://cloud.githubusercontent.com/assets/14353344/12182189/b17722c8-b554-11e5-87d5-cc97219ff0be.png)

![image](https://cloud.githubusercontent.com/assets/14353344/12182248/ff59d51c-b554-11e5-836c-fb9a1ae446ea.png)

**Comment by kurtw** [comment]
@michaelrivera03 unfortunately the way that table is implemented is pretty confusing. 

When you go to create a Row you should click the `Add Another` button. To add columns, you should use the "Streamfield menu" that has things like RichText Blob, Textarea Blob, etc.

Additionally, in order for each of the columns to show, they need a corresponding Header. In your screenshot, you only have one header. If you added 2 more, you'd see the content you've added show up on the same Row that you created.

If you need more clarification, just reach out.
