### ISSUE TITLE
sizing of 50/50 images

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1319]
Using a 16x9 image that AJ provided in the 50/50 on /education-outreach-resources/ and the re-sizing looks off.

**Comment by jimmynotjim** [comment]
This is a front-end issue, opened in Jira under DFJR-676.

**Comment by tnferrell** [comment]
This may have been human error. I didn't see the 16:9 checkboxes in wagtail when I reported this. That fixed the issue.

**Comment by KimberlyMunoz** [comment]
Closed the issue in JIRA before we forget.
