### ISSUE TITLE
line break missing between stacked urls in sidefoot

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1328]
looks like there may be spacing/formatting issues too

example:  /consumer-help/financial-resources-servicemembers/

**Comment by sebworks** [comment]
@kurtw, should the sidefoot have the `Related-Links` molecule. It looks like that's why they are recreating.

**Comment by kurtw** [comment]
I think that makes the most sense. I'll send up a change briefly.

**Comment by kurtw** [comment]
@tnferrell The Related Links molecule is now in refresh. The links you've had problems with will have to be re-entered in that molecule to attained the desired result.
