### ISSUE TITLE
fcm categories need to be updated

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1337]
The categories available in the CMS aren't the categories outlined in the spec. They should be in line with the design manual and should display in sentence case. 

![c5c20af0-b9ea-11e5-9e87-7e0c4ef80d9b](https://cloud.githubusercontent.com/assets/13967788/12302994/b614b802-b9ed-11e5-9951-a82692ea6f5e.png)

**Comment by KimberlyMunoz** [comment]
To verify:

The Featured Content module should **NOT** have these categories, but rather the ones above.

![image](https://cloud.githubusercontent.com/assets/1860176/12623953/8486c0c4-c4fa-11e5-9344-2766cd6f0794.png)

**Comment by KimberlyMunoz** [comment]
#1314 updates the issues here:
https://github.com/cfpb/cfgov-refresh/pull/1314/files#diff-942617fe5c58b4c677a6d7cb593ec94aR15

**Comment by KimberlyMunoz** [comment]
Just checked and things are updated in wagtail!
