### ISSUE TITLE
Wagtail: Arabic formatting

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1345]
We have Arabic content on two pages: /sending-money/ar (browse page) and /cfpb-your-language (sublanding page). It needs to be not just right-justified, but also reading right-to-left (for example, bullet points align on the right margin). Example page from current site is here: http://www.consumerfinance.gov/sending-money/ar/

**Comment by KimberlyMunoz** [comment]
This is a larger accessibility issue. We need to have the language set correctly either in the top or a block of content that has the language

`<html dir="rtl" lang="ar">` or at least `<div dir="rtl" lang="ar">` should be set on this page. I looked into the HTML5 element `dir="auto"` to have the browser know what needs to be set in what direction, but the IE support looks terrible.

**Comment by KimberlyMunoz** [comment]
We'll also need to set a language for our Spanish content and content in other languages.

**Comment by Schlachtmeyer** [comment]
Keep in mind also the use case in the /cfpb-your-language/ sublanding page that contains all 7 languages (not counting English & Spanish).

**Comment by KimberlyMunoz** [comment]
That one might need to be hard coded to be implemented correctly. The whole page reads in English right now.

**Comment by KimberlyMunoz** [comment]
Actually, are all the foreign language things in "full-width text" molecules?

**Comment by KimberlyMunoz** [comment]
Going to write this down here before I lose it over the weekend. If all the foreign language blocks are full-width text or even a limited number of molecules, we could add a dropdown to each one to choose the language and set the language for the block. Pros: Multiple languages could be handled on one page. Cons: We're creeping in options madness and we'd have to do this for every molecule we want to use in alternate languages.

Alternatively, people can set the language on page settings which would toggle the language and set it on the main div that holds everything. Pros: One dropdown vs. multiple per pages. Cons: If there's a mix of English generated content and non-English content, the English stuff will be read incorrectly.

**Comment by Schlachtmeyer** [comment]
Most of the foreign-language content does appear in full-width content molecules...BUT foreign languages currently also used in:
Heading, intro, body (Text Introduction)
Well
Heading, image text, body (25/75)
Slug (sidefoot)
Hyperlink text

Currently ALL foreign language pages (on the English site, at least) have multiple languages, because along with each language we offer links over to the other languages, using those languages (for example, on the Russian page we offer links to Korean, Chinese, Vietnamese, Tagalog, Arabic, and the rest).

**Comment by KimberlyMunoz** [comment]
>Currently ALL foreign language pages (on the English site, at least) have multiple languages, because along with each language we offer links over to the other languages, using those languages (for example, on the Russian page we offer links to Korean, Chinese, Vietnamese, Tagalog, Arabic, and the rest).

I can fix this and we'll hard code that bit, so no worries there. ;)

Other than the  /cfpb-your-language/ language page, are there any other pages with a mix of languages?

**Comment by Schlachtmeyer** [comment]
Take a look at the /sending-money/vi page or another one...they all follow the same format. In the sidefoot you'll see the hyperlinks -- some are to the languages pages and some are to publications. But if you can hard-code that somehow, that's the only other place where we currently need additional languages within a foreign-language page.

**Comment by KimberlyMunoz** [comment]
Hopped on the phone with @Schlachtmeyer clarified a few things and came up with an initial proposal to share at team working session.

It looks like all the content in the main content section is mostly always the same language with the exception of  `/cfpb-your-language/`. So the whole page (which contains the header/footer/sidebar/etc) will be in English, with the main content section being selected by content users in a page settings option. 

If the page is Arabic, we'll include logic to also make it right-to-left reading.

There is a sidefoot section which has the pages in other languages. We'll need to visit how to programmatically make sure that reads correctly with proper href and hreflang tags in the future, but users should still be able to access content by selecting their language in the global eyebrow and navigating.
![image](https://cloud.githubusercontent.com/assets/1860176/12365656/2026d894-bba4-11e5-9249-8fb64a93f1ef.png)

`/cfpb-your-language/` should be broken up into individual pages for each language or alternatively hardcoded.

**Comment by schaferjh** [comment]
I think this sounds like a great proposal @KimberlyMunoz but I'm not sure I understand it fully -- tell me more about this "page settings option" -- is this basically a drop-down select near the main content on `/cfpb-your-language/`? And then for the individual `/sending-money-abroad/` pages, we would still have a page per language? or do you see a way to use a page setting options there as well?

Looking forward to discussing at team working session!

**Comment by KimberlyMunoz** [comment]
On the configuration tab of each page, we ~should~ be able to add an option to select the language for the page. 

![image](https://cloud.githubusercontent.com/assets/1860176/12367240/8d9eab04-bbae-11e5-8689-d94d8ece0d48.png)

**Comment by Schlachtmeyer** [comment]
Hey @KimberlyMunoz - All the languages pages are now broken out into their own Browse pages, so if you want to try out your language selection, you've got some examples to work with. Let me know if & when you want me to do anything!

**Comment by KimberlyMunoz** [comment]
Working with BEWDs to get the option turned on in the new config menu. Moved to JIRA issue DFJR-738.

**Comment by KimberlyMunoz** [comment]
Related PRs: #1361 and #1372.

**Comment by KimberlyMunoz** [comment]
This should be ready for content to use! Check for language options in the configuration page.

**Comment by Schlachtmeyer** [comment]
Cool!!

Question about Arabic. It looks good but I think it's treating the phone number strangely. On our current site the phone number reads left to right, just as it does in English: http://www.consumerfinance.gov/lang/#ar

On the new page once I click the "Arabic" drop-down, the alignment looks great. But somehow the phone number might not be working: الحماية المالية للمستهلكين (855) 411-2372 واضغط 8

Each bit of the phone number reads left to right but the overall number is right to left? Seems odd and not what we have today. Should I do something in the content to keep those phone number elements together?

**Comment by KimberlyMunoz** [comment]
We have something hardcoded to make the phone number go the right direction there on our current page. I added some non-breaking spaces to fix the numbers for now.

![image](https://cloud.githubusercontent.com/assets/1860176/12799563/6db4ff7a-ca9d-11e5-9c94-b69152703a66.png)

**Comment by Schlachtmeyer** [comment]
Cool. What happens if something is not tagged in its language - especially something that doesn't have a different character set, like Spanish or Tagalog?

**Comment by KimberlyMunoz** [comment]
It just reads in the language that it's being tagged with.

**Comment by KimberlyMunoz** [comment]
I think this is done, but flag this issue if I'm wrong and there's more work to be done.
