### ISSUE TITLE
Wagtail lacks the ability to add sub-bullet points

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1346]
In the sending-money pages, there are sub-bullets in the full-width text molecules. Right now the formatting is borrowed from the underlying Word doc but where that gets lost, I'm unable to format correctly (please see /sending-money/es/ for an example of where it's not possible to make sub-bullets).

We will probably need this option in all the areas where the bulleted list molecule exists.

**Comment by KimberlyMunoz** [comment]
I don't see sending-money at the top level.

**Comment by Schlachtmeyer** [comment]
oh sorry -- it's under Consumer Help

**Comment by KimberlyMunoz** [comment]
I just checked with @kave and there isn't a way to have sub-bullets in wagtail. Is there a way to change the content to not require subbullets?

cc @schaferjh so she's aware.

**Comment by schaferjh** [comment]
Hmmm. For reference this is the content on the current site -- http://www.consumerfinance.gov/sending-money/, so you can see where the sub-bullets are coming into play. When we talk to the stakeholders about moving this page into the new template, we can feel out the likelihood of being able to modify the content slightly to get rid of the sub-bullets, though it seems possible that this is going to come up elsewhere in the future.

**Comment by Schlachtmeyer** [comment]
Totally agree. Even if we could write around it in future, on these particular pages we don't have the in-house (or in-team!) language ability to rewrite sub-bullets in all the languages.

**Comment by sebworks** [comment]
Closing, the /sending-money/ pages have been converted and have sub-bullets. You can create sub-bullets by copy / pasting from an editor such as TinyMCE. Wagtail 2.0 with Draft.js should allow us to do this without a hack.
