### ISSUE TITLE
Required body text in link blob

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1348]
Right now the half-width link blob requires content between the heading and list of links. That's not working for /college-credit-card-agreements-browse/ - do we need to create lead-in text or can this be changed to not required (in Wagtail and on wiki)?

**Comment by KimberlyMunoz** [comment]
Where is that page. I don't see it on the top level.

**Comment by KimberlyMunoz** [comment]
Found it and the issue.

![image](https://cloud.githubusercontent.com/assets/1860176/12621580/3053b256-c4ef-11e5-9668-c171c98496d0.png)

**Comment by KimberlyMunoz** [comment]
BEWDs will have to make that field unrequired.

**Comment by KimberlyMunoz** [comment]
Fixed in refresh!
