### ISSUE TITLE
Higher table title character count?

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1354]
There appears to be a 20-character limit on table titles, which I don't think is enough. Maybe 100? 

Please see the Your Money, Your Goals page in Wagtail.

**Comment by tnferrell** [comment]
To Laura's point, I'm kind of for removing character limits altogether for tables. Here's a table I'm trying to input into wagtail. http://www.consumerfinance.gov/guidance/petitions-to-modify-or-set-aside/. The first cell character limits are too low for text and for hyperlinks.

**Comment by KimberlyMunoz** [comment]
I'm trying to see the bug in wagtail itself, but I can't find the table in Your Money, Your Goals. I think the BEWDs can easily increase the character limit on table titles for now though!

**Comment by schaferjh** [comment]
There are no longer tables on Your Money, Your Goals because we made a content/ux decision to convert the information to browse pages instead of putting it all into tables on this sublanding page. 

As for the character limits in tables, is this linked to #1355?

**Comment by KimberlyMunoz** [comment]
No, that's a different front-end issue.

**Comment by schaferjh** [comment]
ok cool, thanks for the carification @KimberlyMunoz. 

@kave this is a higher priority issue now as content has been running into it in a couple of places. One example of a more recent page where they've run into the problem at the bottom of /policy-compliance/small-business-review-panels/, but you can also look at the content board on Jira, where they've flagged all the pages where they've run into problems.

**Comment by kave** [comment]
@schaferjh created a fix for this to be reviewed on the next push to refresh this afternoon

https://github.com/cfpb/cfgov-refresh/pull/1418
