### ISSUE TITLE
Table line length varies?

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1355]
On the Your Money, Your Goals page, there are 4 table headings. They seem to alternate between long and short line lengths. Is this intentional? Screen grab shows sections 2, 3, 4.

![image](https://cloud.githubusercontent.com/assets/14129916/12430502/f36b007e-bebd-11e5-9d93-5d449332ee43.png)

**Comment by KimberlyMunoz** [comment]
Setting the tables to be width: 100% by default will probably fix this. I didn't because I was mostly porting cf-tables, but it probably makes sense here.

**Comment by KimberlyMunoz** [comment]
I can't find the page with this issue. Please let me know the URL and I can work on it.

**Comment by Schlachtmeyer** [comment]
Well, this page now has a totally different layout, so I guess until we hit this use case again it will be hard to troubleshoot! Let's close for now and we can reopen if it shows up elsewhere.

**Comment by KimberlyMunoz** [comment]
Sounds good to me.
