### ISSUE TITLE
Spacing across different pages / elements

### ISSUE THREAD

**Issue by ajbush** [cfpb/cfgov-refresh#1366]
There are several pages that seem to have display bugs with spacing. I think the best way to capture the issues I've seen thus far regarding spacing is to use this issue to document appearances of spacing issues and to keep track of where they were found. At this time I'm not sure if these are global issues or just isolated occurrences but the goal is to be as succinct as possible by using mockups.

**Click links below to view marked up screenshots.**

[Consumer Help](https://cloud.githubusercontent.com/assets/6931351/12563112/99b6d162-c376-11e5-8663-ab4e094b7e92.png)
[Credit Card Data](https://cloud.githubusercontent.com/assets/6931351/12563125/ab709b22-c376-11e5-8b3e-546bafaa9538.png)
[Data and research](https://cloud.githubusercontent.com/assets/6931351/12563134/b7f167e6-c376-11e5-9ace-ec8d7a26a17d.png)
[For communities and educators](https://cloud.githubusercontent.com/assets/6931351/12563145/c14b5216-c376-11e5-80f1-ff24f465a276.png)
[Managing Credit](https://cloud.githubusercontent.com/assets/6931351/12563161/d4473d62-c376-11e5-9290-ce73393b6723.png)
[Planning for retirement](https://cloud.githubusercontent.com/assets/6931351/12563173/e064baac-c376-11e5-9a17-b7bee86373fe.png)
[Protecting Against Credit Discrimination](https://cloud.githubusercontent.com/assets/6873734/12590760/89353e84-c432-11e5-8bdf-625f1d8c98a3.png)
[Protecting Against Fraud](https://cloud.githubusercontent.com/assets/6873734/12597202/ec23091c-c451-11e5-808e-7da64b87e1d1.png)
[Sending Money Abroad](https://cloud.githubusercontent.com/assets/6873734/12597329/9ddc1f68-c452-11e5-94eb-adcb9952fff8.png)
[Information for Servicemembers](https://cloud.githubusercontent.com/assets/6873734/12592131/1b0c36c2-c439-11e5-8d02-5f419d9cfeb8.png)
[Money Tips for Servicemembers](https://cloud.githubusercontent.com/assets/6873734/12592462/78e7276a-c43a-11e5-90e8-a2c86c71307b.png)
[Other languages - Sending Money Abroad](https://cloud.githubusercontent.com/assets/6873734/12594391/e78d9434-c443-11e5-9464-d7aa3b5c4a4b.png) All language pages have the same spacing issues.

**Comment by duelj** [comment]
#### Policy & Compliance page - 
The space after the page content and the footer is too much, however the spacing on the rest of the page looks as expected. *There is no link to the page because it is still a draft*

<img width="1324" alt="screen shot 2016-01-26 at 3 30 50 pm" src="https://cloud.githubusercontent.com/assets/6873734/12594032/0ce614b0-c442-11e5-9de6-a8aea45d20ba.png">

**Comment by KimberlyMunoz** [comment]
For this issue, could you update the screenshots with what the intended spacing should be. Some are obvious, but there's a few on there that aren't.

**Comment by duelj** [comment]
Since the spacing patterns should be pretty consistent across the site between different molecules and organisms can we just have a discussion soon and outline our spacing standards instead? 

It seems like showing the updated spacing for each page would lend itself to the idea that the spaces will be coded bespoke for each page which is not what we want. I mostly want to understand if there is a more efficient way for us to do this? Maybe we can have a pow-wow Monday?

**Comment by KimberlyMunoz** [comment]
I'll try to remember to bring this up on Monday, but I'm tagging @leejenni to add it to the agenda.

Spacing standards are fine/awesome. Since we're making changes at the template level, we definitely don't want bespoke spacing either.

**Comment by schaferjh** [comment]
We don't have scrum this Monday, but Jen and I are happy to arrange a meeting --- or we could discuss after scrum on Tuesday. Let me know which you prefer.

**Comment by duelj** [comment]
I collected some general spacing thoughts for spacing between molecules and organisms that are consistent across page types. I thought I would see if this helped and make sure we were all on the same page with these before we have more discussion

#### Standard spacing (no rule line)
![screen shot 2016-02-01 at 1 00 32 pm](https://cloud.githubusercontent.com/assets/6873734/12726174/2f636e42-c8e4-11e5-8921-f049d119e96f.png)
* 30px above 
 * This is true of mols/orgs under heroes as well
 * unless it is a text introduction under a breadcrumb which would be [handled like this](https://github.cfpb.gov/flapjack/Modules-V1/wiki/Breadcrumbs)
* 60px after
 * This is true when the mol/org is the last piece to a section. The next element should be a rule line or mol/org of a new section.
* **These spacings are not additive! There should not be more than 60px between mol/orgs unless there is a rule line (see below)**

#### Spacing with rule line divider between sections
![screen shot 2016-02-01 at 1 00 47 pm](https://cloud.githubusercontent.com/assets/6873734/12726300/dd30b89a-c8e4-11e5-8e17-cc1bc52af0b1.png)
* The rule line acts a mol/org without spacing of it's own 
* mol/org before rule line has standard 60px after, the rule line, and the mol/org that follows the rule has the standard 30px above. 

#### Spacing between multiple 25/75 molecules
![screen shot 2016-02-01 at 1 00 53 pm](https://cloud.githubusercontent.com/assets/6873734/12726446/9d1f353c-c8e5-11e5-934a-cb9ced247b4f.png)
* The [specs for the 25/75](https://github.cfpb.gov/flapjack/Modules-V1/wiki/25-75-Image-&-Text) do not reflect this but we use this molecule commonly without rule lines on top and bottom. The spacing in the spec is still generally correct without the rules.
* An update that was made in build was allowing for 30px of space between 25/75 molecules where there were multiples of these in the same section stacked on top of each other. 
 * The last 25/75 molecule should still have 60px of space after. 
 * This spacing should not be used if the multiple 25/75 molecules are not part of the same section or are not intended to be grouped. 
 * I do not think any other molecules abide by this spacing structure. 

#### Other instances
* Sidebar mol/orgs abide by the same spacing structure and the slug headings are considered part of a given sidebar mol/org. 
* Full width text molecules follow this structure when the mol/org  above or below is not another full width text molecule. 
 * When multiple full width text molecules are next to each other the spacing should reflect the [web type hierarchy spacing standards](https://github.com/cfpb/design-manual/issues/269#issuecomment-157544901)

@ajbush and @schaferjh - do these guidelines follow your thinking for our general approach to spacing elements on all page types? Are there things  that are missing or need to be added? Do any of these sound incorrect?

**Comment by KimberlyMunoz** [comment]
A lot of the spacing issues have been merged in. With the exception of anything on the browse-filterable page that is being addressed this sprint, any new spacing issues should get tagged with a new spacing issue!
