### ISSUE TITLE
Body copy Avenir by default

### ISSUE THREAD

**Issue by duelj** [cfpb/cfgov-refresh#1373]
There have been a few discussions around when we use Avenir vs. Georgia in body copy but the DM has not been resolved on this. Latest thinking is to use Avenir Next regular as default body copy across V1 and specify instances where Georgia will be used for longer passages of body text. This particularly seems to be an issue in the text introduction molecule.

[Protection against credit discrimination](https://cloud.githubusercontent.com/assets/6873734/12596942/a1559cfc-c450-11e5-86f4-a9d280ed53dc.png)
[Protecting against fraud](https://cloud.githubusercontent.com/assets/6873734/12597031/158d4f0c-c451-11e5-8445-680a965e47ce.png)
[Sending money abroad](https://cloud.githubusercontent.com/assets/6873734/12597455/39ecb4d0-c453-11e5-8dfa-3ac1317209e4.png)

**Comment by KimberlyMunoz** [comment]
@jimmynotjim is already on it! See #1360

**Comment by duelj** [comment]
That is good news! Sorry I missed that. If #1360 will update everything we need, should I close this issue?

**Comment by KimberlyMunoz** [comment]
I put a "Review on next refresh push" tag on this issue. For the last couple weeks, we've been closing them when the reporter confirms the changes on refresh, but it's up to youl

**Comment by KimberlyMunoz** [comment]
Fixed on refresh. Since this is all over, do you mind confirming that there aren't any stray Georgia paragraphs @duelj?

**Comment by duelj** [comment]
There are a few pages where I still found some random Georgia. I pretty much just went through all the pages on the content migration tracker spreadsheet.

[Suggest a case](http://content.refresh.demo.cfpb.gov/policy-compliance/amicus/suggest/)
[Sending money abroad Spanish](http://content.refresh.demo.cfpb.gov/consumer-help/sending-money-abroad/es/) *I didn't try all the other languages*
[Community banks and credit unions](http://content.refresh.demo.cfpb.gov/policy-compliance/community-banks-credit-unions/)

**Comment by duelj** [comment]
Just checked again as requested with a shift+refresh and the example above were viewing correctly. Looking great!

**Comment by KimberlyMunoz** [comment]
![kermit_the_frog_yay_arm_flail_original](https://cloud.githubusercontent.com/assets/1860176/12984952/429395dc-d0be-11e5-9d23-8022cb61dff8.gif)
