### ISSUE TITLE
Sending money (languages) - 25/75  molecuels changed to 50/50 in well

### ISSUE THREAD

**Issue by duelj** [cfpb/cfgov-refresh#1378]
On the sending money abroad pages for different languages the V1 versions are showing 25/75 image & text molecules for the "before you pay" and "after you pay" sections. In discussion we realized that this was because we needed to try and recreate the look of what was currently on cf.gov. The images are much taller than the aspect ratios that we use on V1 so the thought was to use larger images in the 25/75 molecule. 

|[Currently on cf.gov](http://www.consumerfinance.gov/sending-money/)|[Content currently on V1](http://content.refresh.demo.cfpb.gov/consumer-help/sending-money-abroad/es/)|
---|---
| <img width="1089" alt="screen shot 2016-01-27 at 2 17 49 pm" src="https://cloud.githubusercontent.com/assets/6873734/12625488/1649169a-c502-11e5-87c7-9a795c5f08df.png">|<img width="769" alt="screen shot 2016-01-27 at 2 11 23 pm" src="https://cloud.githubusercontent.com/assets/6873734/12625491/1b439940-c502-11e5-93eb-02bfb0aba8df.png">|

@KimberlyMunoz suggested that using the 50/50 well might function better. we agreed changing the current 25/75 molecules to 50/50 well would allow the images to be larger and still grouped together with a before and after payment.  

@schaferjh @KimberlyMunoz - does this all sound right?

**Comment by Schlachtmeyer** [comment]
We can do whatever looks better. The issue I was thinking of in choosing 25/75 is that the two images are not the same height. So I don't think the 50-50 content will align nicely either. I'm happy to try it either way -- could we bring over the actual images so that we can decide?

**Comment by KimberlyMunoz** [comment]
There's going to be a new 50-50 layout molecule inside the well organism that we're thinking of using in this use case.

**Comment by KimberlyMunoz** [comment]
Blocked by #1218

**Comment by schaferjh** [comment]
Closing out this issue since we are no longer handling this content for the V1 migration.
