### ISSUE TITLE
Information for servicemembers - Featured Content Molecule - multi link issues

### ISSUE THREAD

**Issue by duelj** [cfpb/cfgov-refresh#1379]
The two links in the FCM on this page should visually look the same. The first link seems to be lighter weight and also does not get the full mobile link style on smaller screens. Both links should look the same at all screen sizes. 

|Large screen|Small screen|
---|---
|<img width="832" alt="screen shot 2016-01-27 at 2 35 19 pm" src="https://cloud.githubusercontent.com/assets/6873734/12625909/e21aa148-c503-11e5-88c2-dc1cb64386fd.png">|<img width="385" alt="screen shot 2016-01-27 at 2 35 41 pm" src="https://cloud.githubusercontent.com/assets/6873734/12625912/e42889c8-c503-11e5-8b6d-23c378ec74ef.png">|

**Comment by KimberlyMunoz** [comment]
Fixed!
