### ISSUE TITLE
Remove extra form fields from slug sections on browse pages

### ISSUE THREAD

**Issue by duelj** [cfpb/cfgov-refresh#1381]
Pages with slug sections have extra form fields after the real content. 

**Seems to be on all browse pages with slug elements.**

#### Pages affected
[Sending money abroad Spanish](http://content.refresh.demo.cfpb.gov/consumer-help/sending-money-abroad/es/) - all language pages
[Money tips and basics for servicemembers](http://content.refresh.demo.cfpb.gov/consumer-help/financial-resources-servicemembers/money-tips/)
[Warning Letters](http://content.refresh.demo.cfpb.gov//policy-compliance/enforcement/warning-letters/)
[Appeals Policy](http://content.refresh.demo.cfpb.gov//policy-compliance/supervision-examinations/appeals-policy/)
[List of depository institutions/Institutions subject to CFPB supervisory authority](http://content.refresh.demo.cfpb.gov//policy-compliance/supervision-examinations/institutions/)
[Supervision and examinations](http://content.refresh.demo.cfpb.gov//policy-compliance/supervision-examinations/)

#### Example from money tips page
<img width="774" alt="screen shot 2016-01-27 at 3 05 46 pm" src="https://cloud.githubusercontent.com/assets/6873734/12626606/7d126926-c507-11e5-8422-20a40d21f050.png">

**Comment by KimberlyMunoz** [comment]
Weeeeeeeeeeeeiiird... Looking into it.

**Comment by KimberlyMunoz** [comment]
Fixed on refresh!
