### ISSUE TITLE
Slug sections should have well background on browse pages 

### ISSUE THREAD

**Issue by duelj** [cfpb/cfgov-refresh#1383]
Pages that use atomic elements with slug headings such as any of the "Related X" molecules should have a well background so that they look like a pre-footer. 

**Looks like this is happening across multiple browse pages.**

#### Examples
[Protecting against credit discrimination](http://content.refresh.demo.cfpb.gov/consumer-help/managing-credit/protecting-against-credit-discrimination/)
[Protecting against fraud](http://content.refresh.demo.cfpb.gov/consumer-help/planning-retirement/protecting-against-fraud/)
[Sending money abroad Spanish](http://content.refresh.demo.cfpb.gov/consumer-help/sending-money-abroad/es/)
[Money tips and basics for servicemembers](http://content.refresh.demo.cfpb.gov/consumer-help/financial-resources-servicemembers/money-tips/)

**Comment by KimberlyMunoz** [comment]
This issue is affecting browse-basic and browse-filterable pages.
