### ISSUE TITLE
Add header font-size mixins to cf-enhancements

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1387]
In #1369, [I used the .heading-2() mixins for the sole purpose of exposing the @font-size variable within](https://github.com/cfpb/cfgov-refresh/pull/1369#discussion_r51180539). If we create a number of font-size mixins for this reason, we should be to avoid situations like this while also avoiding the need to hard code those numbers.

**Comment by jimmynotjim** [comment]
Did you mean we should add size variables?

**Comment by KimberlyMunoz** [comment]
yep!

**Comment by KimberlyMunoz** [comment]
@jimmynotjim, should I close now that it's in CF?

**Comment by jimmynotjim** [comment]
Yep, no use in having them set twice.
