### ISSUE TITLE
General atomic element spacing guidlines

### ISSUE THREAD

**Issue by duelj** [cfpb/cfgov-refresh#1396]
I collected some general spacing thoughts for spacing between molecules and organisms that are consistent across page types. I thought I would see if this helped and make sure we were all on the same page with these before we have more discussion

#### Standard spacing (no rule line)
![screen shot 2016-02-01 at 1 00 32 pm](https://cloud.githubusercontent.com/assets/6873734/12726174/2f636e42-c8e4-11e5-8921-f049d119e96f.png)
* 30px above 
 * This is true of mols/orgs under heroes as well
 * unless it is a text introduction under a breadcrumb which would be [handled like this](https://github.cfpb.gov/flapjack/Modules-V1/wiki/Breadcrumbs)
* 60px after
 * This is true when the mol/org is the last piece to a section. The next element should be a rule line or mol/org of a new section.
* This is true for the last mol/org on a page before the footer. *(there should always be 60px between the last thing on the page and the footer)*
* **These spacings are not additive! There should not be more than 60px between mol/orgs unless there is a rule line (see below)**

#### Spacing with rule line divider between sections
![screen shot 2016-02-01 at 1 00 47 pm](https://cloud.githubusercontent.com/assets/6873734/12726300/dd30b89a-c8e4-11e5-8e17-cc1bc52af0b1.png)
* The rule line acts a mol/org without spacing of it's own 
* mol/org before rule line has standard 60px after, the rule line, and the mol/org that follows the rule has the standard 30px above. 

#### Spacing between multiple 25/75 molecules
![screen shot 2016-02-01 at 1 00 53 pm](https://cloud.githubusercontent.com/assets/6873734/12726446/9d1f353c-c8e5-11e5-934a-cb9ced247b4f.png)
* The [specs for the 25/75](https://github.cfpb.gov/flapjack/Modules-V1/wiki/25-75-Image-&-Text) do not reflect this but we use this molecule commonly without rule lines on top and bottom. The spacing in the spec is still generally correct without the rules.
* An update that was made in build was allowing for 30px of space between 25/75 molecules where there were multiples of these in the same section stacked on top of each other. 
 * The last 25/75 molecule should still have 60px of space after. 
 * This spacing should not be used if the multiple 25/75 molecules are not part of the same section or are not intended to be grouped. 
 * I do not think any other molecules abide by this spacing structure. 

#### Other instances
* Sidebar mol/orgs abide by the same spacing structure and the slug headings are considered part of a given sidebar mol/org. 
* Full width text molecules follow this structure when the mol/org  above or below is not another full width text molecule. 
 * When multiple full width text molecules are next to each other the spacing should reflect the [web type hierarchy spacing standards](https://github.com/cfpb/design-manual/issues/269#issuecomment-157544901)

@ajbush and @schaferjh - do these guidelines follow your thinking for our general approach to spacing elements on all page types? Are there things  that are missing or need to be added? Do any of these sound incorrect?

**Comment by KimberlyMunoz** [comment]
How much spacing should there be for the last molecule on a page? 60px?

**Comment by duelj** [comment]
Great call, yes 60px after the last molecule on the page. I have updated the original post and added this into the "standard spacing" section.

**Comment by schaferjh** [comment]
@duelj yep, this all looks correct to me -- thank you for putting it together!

**Comment by jimmynotjim** [comment]
This is how I've understood it so far but had trouble describing. That's for making it visual.
