### ISSUE TITLE
Avoiding widows

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1398]
Is there a way to squeeze content or expand line length to avoid bad widows? 

Couple examples on the Sending Money Abroad page (in English) -- in the paragraph content and in the breakout sidebar:
![image](https://cloud.githubusercontent.com/assets/14129916/12728300/25920fda-c8ef-11e5-8632-c24e400a03a6.png)

**Comment by KimberlyMunoz** [comment]
I did some research with @jimmynotjim on this one and unless we go down a hacky JavaScript solution that iterates on every single paragraph on the website*, there really isn't anything we can do for this one. In responsive design, there's going to be so many different widths and breakpoints that stray words will occur. 

Tagging in @schaferjh, so she's aware and can weigh in on whether to close or discuss more.

* Please don't do this. It'll be a huge performance hit for very little gain.

**Comment by Schlachtmeyer** [comment]
No worries - it was something that came up in our meeting with design and thought it was worth looking into.

**Comment by schaferjh** [comment]
Thanks for looking into it @KimberlyMunoz and @jimmynotjim. Let's avoid the huge performance hit and let the words fall where they may. Responsive rulz win.
