### ISSUE TITLE
Filterable List Spacing Issue

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1408]
The results for the filterable list has off spacing. Reported by @kurtw in chat.

## Steps to Replicate

1. Visit [content refresh]/policy-compliance/amicus/briefs/
2. Apply Supreme Court Filter

## Expected Behavior

There should be spacing between the notification and the list of results

## Screenshot

![image](https://cloud.githubusercontent.com/assets/1860176/12833280/98155b2c-cb6d-11e5-918e-9e5b8dcad083.png)

**Comment by kurtw** [comment]
It seems like this is done? @KimberlyMunoz could you confirm and close if so?
![screen shot 2016-03-02 at 10 17 02 am](https://cloud.githubusercontent.com/assets/1412978/13464612/f712d986-e05f-11e5-957d-d9fdb25f6eec.png)
