### ISSUE TITLE
Every phone number in contact info appears to be a fax

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1412]
In the Contact Info molecule, all the molecules with phone numbers appear to be faxes even when they aren't.

## Steps to replicate

1. Create a sublanding page
2. Create a Contact Info Molecule in the sidebar
3. Select a contact with phone numbers, such as "Submit a complaint" or "Reasonable Accommodation Requests"

Everything will appear under fax. If you move the loop outside of the label, every label will be "Fax", even when no fax numbers are included in the contact.

## Preview

** Result **
![image](https://cloud.githubusercontent.com/assets/1860176/12855299/9ae40c28-cc0c-11e5-8811-5084795ef8ae.png)

![image](https://cloud.githubusercontent.com/assets/1860176/12855371/fee99b84-cc0c-11e5-9fd2-328c28b501a8.png)

**Expected fields**

![image](https://cloud.githubusercontent.com/assets/1860176/12855314/b19ff706-cc0c-11e5-96e2-d424eef1c371.png)

![image](https://cloud.githubusercontent.com/assets/1860176/12855384/0fb34b36-cc0d-11e5-9718-cfcc5ff5d53d.png)

**Comment by kave** [comment]
@KimberlyMunoz so theres a boolean check box that renders if a number is a fax or not. Could you verify content just isn't saved incorrectly?

**Comment by KimberlyMunoz** [comment]
Is the information that feeds the contact-information molecule the same as the information that feeds the contact us page? Because it appears correctly in the contact us page screenshots above.

**Comment by kave** [comment]
@KimberlyMunoz nah its not, the contact-us page is using `macros/util/format/contact.html` but the molecule is using `/_includes/organisms/main-contact-info.html`

**Comment by kave** [comment]
discussed, possible bug with import-data script. i'll be looking into it

**Comment by schaferjh** [comment]
High priority because we are going to get a lot of pushback if we allow it to look like folks can only reach us via fax or email! :neutral_face:

**Comment by kave** [comment]
@kurtw @richaagarwal this has been pushed to refresh. If one of you wants to log into the server and re-run the contact import-data script with the override flag that would be great. don't forget to source python!

**Comment by Schlachtmeyer** [comment]
I am unable to preview pages that have the "sidebar contact" molecule. Is this a known issue?

**Comment by kave** [comment]
@Schlachtmeyer ah now it is, i'll take care of it https://github.com/cfpb/cfgov-refresh/pull/1489

**Comment by kave** [comment]
@Schlachtmeyer could you try again?

**Comment by Schlachtmeyer** [comment]
@kave Yes! Working now. Thanks!
