### ISSUE TITLE
Moving Tables to inside Full-Width Text Organism

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1419]
While going over spacing issues with @ajbush and @duelj, they pointed out that tables inside a bunch of text should only have 30px of spacing instead of the full-organism spacing. I think the easiest way to do this and take into account the edge cases where a table would need the full organism spacing when it's the only thing on the page, would be to move the table molecule inside the full-width text organism.

**Comment by kave** [comment]
@KimberlyMunoz sure i'll create a PR and include table as an option in the full width text.
