### ISSUE TITLE
Post preview should have title link 

### ISSUE THREAD

**Issue by duelj** [cfpb/cfgov-refresh#1434]
During working session team noticed a bug in the [post previews](https://github.cfpb.gov/flapjack/Modules-V1/wiki/Post-Preview) where the title text was not a link to the detail page. The link only was separate and posted after the description. The intent for these molecules was that the title would be the primary link and if needed there would be an additional link allowed after the description text. I don't think this interaction was clear in the documentation, so I am not sure if it is built into the molecule currently. 

---

#### Example from [Filed briefs page](http://content.refresh.demo.cfpb.gov/policy-compliance/amicus/briefs/)
![screen shot 2016-02-10 at 12 05 47 pm](https://cloud.githubusercontent.com/assets/6873734/12955084/6868a9e8-cfef-11e5-8a5c-31d0050fc66f.png)

---

**Comment by kave** [comment]
Would the title link be the same url as the `preview_link` below?

**Comment by duelj** [comment]
I think in the filed briefs example yes, but originally wanted the preview link to be able to be able to function as a separate link. I think the only use case for this was on the notice and comment page where the title link was an external link and the preview link would have linked to something else. [This comment](https://github.cfpb.gov/flapjack/Modules-V1/issues/16#issuecomment-56074) shows the various use cases we were trying to address with this molecule.

@schaferjh - does separate links for title and the bottom preview link sound right to you?

**Comment by schaferjh** [comment]
Yes, that sounds right to me. The main (required) link is the title, just as you see on [the blog on beta] (http://beta.consumerfinance.gov/blog/). 

What is being called a `preview_link` is optional and the only use case we currently have for it is on the Closed Notices page (GHE/flapjack/policy-compliance/issues/9 to see the original wireframes).

**Comment by schaferjh** [comment]
For consistency labelling this high, but @KimberlyMunoz is already all over it.
