### ISSUE TITLE
Table row borders

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1440]
The table row borders don't extend in instances where we have an empty cell. This is the most recent example /policy-compliance/enforcement/petitions/. This page is probably going to disappear soon though and I can't think of the previous pages where we've seen this occur. It is occurring on other pages though, so still think it's worth resolving. 

![tables](https://cloud.githubusercontent.com/assets/13967788/12982373/15e3c5fc-d0aa-11e5-9435-a907540e754b.png)

**Comment by KimberlyMunoz** [comment]
Ugh, there isn't a way to do it with css alone. We'll have to create the empty `td` cells somehow to get the borders to show.

**Comment by schaferjh** [comment]
Low priority because yes it's annoying but it's not impeding usage of the page.

**Comment by anselmbradford** [comment]
What's an example page showing this? I don't see it on /policy-compliance/enforcement/petitions/

**Comment by Scotchester** [comment]
No longer true.
