### ISSUE TITLE
Expandable labels not showing correct font

### ISSUE THREAD

**Issue by ajbush** [cfpb/cfgov-refresh#1442]
The expandable label is rendering as "san-serif" instead of Avenir Medium. Caught this on the /policy-compliance/amicus/suggest/ page.

<img width="810" alt="screen shot 2016-02-11 at 1 29 38 pm" src="https://cloud.githubusercontent.com/assets/6931351/12986092/8c245786-d0c3-11e5-81d1-c8361d587288.png">

**Comment by KimberlyMunoz** [comment]
This is happening because `normalize.css` turns all buttons into `sans-serif`, so it should be easy to overwrite.
