### ISSUE TITLE
GET forms should not include csrf_token

### ISSUE THREAD

**Issue by rosskarchner** [cfpb/cfgov-refresh#1450]
csrf protection doesn't really do anything for GET queries, and makes the resulting URL pretty ugly (and the token will also be cached by Akamai, so is almost never actually valid when the user submits something)

This is from the blog filter:

```
<form class="" method="get" lpformnum="1">
    <input type="hidden" name="csrfmiddlewaretoken" value="eOuytBpg0IZ9n95TiFjwkyJFyrA2Hq4e">
    <div class="form-l form-l__float form-l__flush">

[snip]
    
</form>
```

**Comment by kave** [comment]
@rosskarchner which elements are you seeing this behavior?

**Comment by kurtw** [comment]
[This](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/jinja2/v1/_includes/macros/filters.html#L191) does the checking for the csrf token now.
