### ISSUE TITLE
Related links / generic content organsim should include paragraph text

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1454]
We need the ability to add paragraph text to the related links organism in wagtail to make it structured like a generic sidebar content organism, like the spec here: 
https://github.cfpb.gov/flapjack/Modules-V1/wiki/Generic-Sidebar-Content

It's labeled as "related links" in wagtail in the sidefoot.

**Comment by kurtw** [comment]
The fix is on refresh.
