### ISSUE TITLE
preview posts links are linking to refresh

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1455]
For some reason, the preview posts links on content.refresh are linking to refresh instead of content.refresh. View an example here: /policy-compliance/amicus/briefs/

**Comment by schaferjh** [comment]
High priority because this is related to the linking issues we need to get sorted out ASAP so we can effectively test our pages.

**Comment by kurtw** [comment]
I'll handle the fix on this. [Here](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/jinja2/v1/_includes/organisms/post-preview.html#L111) is where the bug is. It's passing `page` to get the URL instead of `post`. Trivial.

**Comment by kurtw** [comment]
This is fixed
