### ISSUE TITLE
post v1: related posts pulling in other types of content

### ISSUE THREAD

**Issue by tnferrell** [cfpb/cfgov-refresh#1470]
CEE has expressed strong interest in the related posts organism pulling in other types of content (i.e. reports, tools, products, etc). Just logging this as a requested enhancement post v1.

**Comment by schaferjh** [comment]
Actually, I think it would be helpful to log this in Jira instead of here so I can work through the backlog in one location. 

@tnferrell Would you create an improvement task over there and tag it with the Post V1 epic? thanks!

**Comment by schaferjh** [comment]
Since Tanya's been out, I moved this into the Jira backlog and am closing this issue for now.
