### ISSUE TITLE
Javascript Error on Expandables

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1487]
Expandables won't load

## Current behavior

- Expandables do not expand, hiding all the content inside them
- There's a JS error `Uncaught Error: o-secondary-navigation not found on or in passed DOM node.`

## Expected behavior

- Expandables should expand.

## Steps to replicate behavior

1. Visit [GHE]/policy-compliance/amicus/suggest/

or create a page with an expandable that is closed by default

## Screenshots

![image](https://cloud.githubusercontent.com/assets/1860176/13262314/3027ab40-da32-11e5-8ec2-fbd3ca8c0d30.png)

**Comment by KimberlyMunoz** [comment]
@jimmynotjim  This got fixed right?

**Comment by jimmynotjim** [comment]
Yep, sorry, didn't know there was a GH issue as well.
