### ISSUE TITLE
Expandables should work when JavaScript is broken

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1488]
We can improve the progressive enhancement on the expandables by changing things so they work when expandables are broken like in issue #1487. This might be difficult to solve without a flash of opening expandables, but we should revisit later.
## Current behavior
- When JS is broken, expandables hide all the content inside them
## Expected behavior
- Expandables should be resilient enough to show content when JavaScript is broken/doesn't load correctly/etc
## Steps to replicate behavior
1. Introduce an error in JS, since Javascript is enabled the no-js will be removed
2. Sadly note you can't read any expandable goodness

**Comment by anselmbradford** [comment]
Not able to repeat this. If I turn JS off, expandables show their content on https://cfpb.github.io/capital-framework/components/cf-expandables/
