### ISSUE TITLE
Breakpoint labels?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cfgov-refresh#149]
We've tried and failed before, but now that we are starting to see clearer layout patterns it might be beneficial to create breakpoint labels based specifically on content-specific layout patterns; like the breakpoints used in `.content_main, .content_sidebar, .content-l`. We might have other breakpoints but they don't all need to be accounted for in this "content-layout breakpoint scale". I think limiting the scope like this might prove more successful.

So far I think we have:

| Label | Range | Site layout |
| --- | --- | --- |
| Mobile | 0 – 599 | Single column |
| Tablet | 600 – 800 | Single column with extra wrapper gutters |
| Desktop | 801 – 1170 | Two columns (1170px is the `max-width` on `.wrapper`) |

Thoughts?

**Comment by anselmbradford** [comment]
This is good reading to frame this issue around http://bradfrost.com/blog/post/7-habits-of-highly-effective-media-queries/ ... in particular having major and minor breakpoints that are dictated by the content (not devices). Seems like the direction the thoughts in this issue are going anyway.

**Comment by KimberlyMunoz** [comment]
Closing this as done for now.
