### ISSUE TITLE
/sub-pages/

### ISSUE THREAD

**Issue by rosskarchner** [cfpb/cfgov-refresh#1527]
Now that we aren't constrained by Sheer's limitation, we should be able to eliminate the 'sub-pages/' URL space, which is kind of sloppy

## Current behavior

- browse to advisory groups
- click consumer advisory board
- observe that that the URL is /sub-pages/consumer-advisory-board/

## Expected behavior

- browse to advisory groups
- click consumer advisory board
- observe that that the URL is /offices/advisory-groups//consumer-advisory-board/

## Steps to replicate behavior

See current behavior.

## Screenshots

__Current__
<img width="1149" alt="screen shot 2016-03-02 at 11 54 13 am" src="https://cloud.githubusercontent.com/assets/235397/13467735/86ee23a0-e06d-11e5-8a81-bae58d9df83b.png">

**Comment by schaferjh** [comment]
Hold on this for the moment -- We are going to try forklifting these pages into Wagtail this sprint, which will have the side effect of working out this URL issue.

**Comment by anselmbradford** [comment]
/sub-pages/ are gone as of https://github.com/cfpb/cfgov-refresh/pull/1594, right? Can this be closed?

**Comment by KimberlyMunoz** [comment]
Yep. Let's close it!
