### ISSUE TITLE
Extra spacing on sublanding page

### ISSUE THREAD

**Issue by Schlachtmeyer** [cfpb/cfgov-refresh#1556]
Not sure why this sublanding page is displaying so much space below the hero.

## Current behavior
![image](https://cloud.githubusercontent.com/assets/14129916/13644148/4ebadaac-e5f2-11e5-8656-254f8f6a3a3a.png)

## Expected behavior
Even adding a header above the half-width link blob doesn't fill in the spacing or make it even with the sidebar content. And the gap between the hero and the sidebar seems extra wide to me?

## Steps to replicate behavior

http://content.refresh.demo.cfpb.gov/data-research/credit-card-data/

**Comment by KimberlyMunoz** [comment]
The hero needs a `block_flush` added to it. That seems to be a FEWD issue, so I'll look into it. 

Here's what it looks like when it's added.

![image](https://cloud.githubusercontent.com/assets/1860176/13650336/2bc0a220-e610-11e5-8051-f2055ff2529c.png)

**Comment by Schlachtmeyer** [comment]
Looks better! I may still try adding a header for the link blob group, but this helps.

**Comment by KimberlyMunoz** [comment]
LGTM!
