### ISSUE TITLE
More robust link patterns

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cfgov-refresh#156]
I was in need in a simple standalone Avenir link and realized we didn't have a pattern for it so I added `.styled-link`. We also have `.jump-link` which is kind of similar but does way more. We also have link styles for links. I'm wondering if we can consolidate and create a `.link` base class and build off of that instead.

|||
| --- | --- |
| `.link` | simple webfont link |
| `.link__large` | bumps up to 18px |
| `.link__rwd` | regular link on large screens and a block link on small screens |
| `.link__jump` | auto adds the right caret icon |
| `.link__jump-download`|  auto adds download icon |

`.link` could possibly replace the need for `.list_link`.
It could also be used as a base for the `__jump` modifiers.
For `.list__links` we could specify that all `.link`s here will get the `.link__rwd` behavior.
For `.__jump`'s we could specify that these automatically get the `.link__rwd` behavior too.

Still need to account for links with icons in front of them but maybe it could be done similarly to how `__jump`.

Am I missing any other link styles?

**Comment by juidai** [comment]
- links should be blue to look like link
- onHover, underline link
- links should be bumped down. it is not proportional to the rest of the page

![link-list](https://cloud.githubusercontent.com/assets/6623411/5630513/8f917d90-958c-11e4-8d9b-85cabc9d1c38.png)
