### ISSUE TITLE
Label on Filters does not match Placeholder

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1620]
The label on the date picker on the filters does not match the guidance given by the placeholder 

## Current behavior

- The placeholder advises people to enter a date as DD-MM-YYYY whereas the label says YYYY-MM. If JS isn't working, we advise people to enter the date as YYYY-MM and have that as the default. When JS is working both should match.

## Expected behavior

- The two pieces of guidance should match.

## Steps to replicate behavior

1. Visit `/blog/` or any other sheer filter page

## Screenshots

![image](https://cloud.githubusercontent.com/assets/1860176/13885145/76a3882c-ed07-11e5-9fb3-e288f821af8b.png)

**Comment by schaferjh** [comment]
Low priority, but given that we have a could of filter issues coming in through QA, I may group this update with another task.

**Comment by sebworks** [comment]
I'm currently working on this in conjunction with changing the way the filters handle the dates.

**Comment by schaferjh** [comment]
Ok. For the record, noting this is being addressed in DFJR-1054.

**Comment by sebworks** [comment]
This was fixed when the referenced pages were converted to Wagtail.
