### ISSUE TITLE
Mega Menu: Long link names need padding again 

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1644]
## Current behavior
- Long names in mega menu links overlap with the green arrow. 
## Expected behavior
- Long names should wrap or be truncated.
## Steps to replicate behavior
1. Open iOS simulate and visit site on iPhone 5.
2. Click through menu and note that long link names overlap with the green side arrow.
## Screenshots

**Current**

![screen shot 2016-03-20 at 7 33 23 pm](https://cloud.githubusercontent.com/assets/704760/13908129/f37c0230-eed2-11e5-9f85-419d03ed09e0.png)

**Expected**

Wrap or truncate long text.

**Comment by jimmynotjim** [comment]
To clarify, you mean iPhone 5, not iOS5 right?

**Comment by anselmbradford** [comment]
> To clarify, you mean iPhone 5, not iOS5 right?

Yup! Updated, thanks!

**Comment by anselmbradford** [comment]
No longer able to reproduce this issue in iOS 11.
