### ISSUE TITLE
Header: menu flyouts zoom off-screen on transition

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1667]
## Current behavior
- When navigating between menu items or the search, the view zooms offscreen and follows the menu transition into view.
## Expected behavior
- Offscreen content should not get focus till it's in view.
## Steps to replicate behavior
1. Open iOS simulator.
2. Open the megamenu
3. Click a second-level menu.
## Screenshots

**Current**

![ioszoom](https://cloud.githubusercontent.com/assets/704760/13935501/0253d3e4-ef8e-11e5-8906-ca4b74587ad3.gif)

**Expected**

![ioszoom2](https://cloud.githubusercontent.com/assets/704760/13935547/3f6fdbec-ef8e-11e5-9162-8768645775fb.gif)

**Comment by jimmynotjim** [comment]
Can we delay the focus change until the animationEnd is triggered?

**Comment by anselmbradford** [comment]
I'd turned off setting the focus explicitly, so I think this just the default focus behavior. We may have to set the focus off of the menu in `expandBegin` and then re-set it on the menu in `expandEnd`.

**Comment by jimmynotjim** [comment]
I'm starting to favor the idea of setting `overflow-x: hidden` on body for screens w/ anything that flies out. This is entirely too complex to handle in individual modules.

**Comment by schaferjh** [comment]
Side note: I'm thinking about priority level of things and am marking this one low, even though I consider it very high among the lower priority things. Is it annoying and not the way things should work? Yes. Does it prevent someone from actually interacting with the site? No. 

That said, if there's a quick fix we might be able to do now and note the need for further exploration, I'd be happy to re-prioritize. Let me know.

**Comment by anselmbradford** [comment]
This may be fixed

**Comment by anselmbradford** [comment]
No longer able to reproduce in iOS 11.
