### ISSUE TITLE
MegaMenu on Android 4.0: Mega Menu does not close

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1669]
## Current behavior

- When navigating on the mega menu on Android 4.0, the "back" button and ability to close the menu doesn't work, leaving users stuck.

View behavior here: https://saucelabs.com/beta/tests/e60667c032b94634be8a09ede39381a7/watch

This was found on Amazon Fire Kindle running Android 4.0. I'll update the post with other browsers affected.

## Expected behavior

- Back button should work and send users back.
- When you click on the menu and then the search, the menu should close and search should appear

## Steps to replicate behavior

1. Click on the menu button
2. Click on Consumer Education
3. Click on the "Back" button and nothing happens
4. Click on the "Search" button and nothing happens

* If you click "Search" before the menu button, the menu button will not appear.

## Screenshots

![image](https://cloud.githubusercontent.com/assets/1860176/13958077/1eee9aa6-f025-11e5-9991-143f65ba4fcc.png)

View behavior here: https://saucelabs.com/beta/tests/e60667c032b94634be8a09ede39381a7/watch

## Affected OS

- Android 4.0
- Android 4.1
- Android 4.2
- Android 4.3

**Comment by KimberlyMunoz** [comment]
[Amazon Fire Tablet/Android 4.0](https://saucelabs.com/beta/tests/e60667c032b94634be8a09ede39381a7/watch)
[HTC One X/Android 4.0](https://saucelabs.com/beta/tests/d8a20884d319465fbbbd01a2c2910328/watch) 

[HTC One X/Android 4.1](https://saucelabs.com/beta/tests/0e3f8d72452348f39e7454d70ff2566a/watch)
Search is not working on this one either.
[Samsung Galaxy Nexus/Android 4.1](https://saucelabs.com/beta/tests/ae0ca8db43d543498b20c16458d39f0d/watch)

**Comment by KimberlyMunoz** [comment]
Issue on Android 4.2 - Search does not work either
[Samsung Galaxy Nexus/Android 4.2](https://saucelabs.com/beta/tests/af2bc5cb67834c7197aa7198f8a31b51/watch)

Issue on Android 4.3 - Search does not work. Clicking Search and then clicking menu causes the menu to break.
[Samsung Galaxy Nexus/Android 4.3](https://saucelabs.com/beta/tests/cd32664f07c544e19caae8b03d5c1901/watch)

**Comment by KimberlyMunoz** [comment]
Works as intended in Android 4.4!
[Samsung Galaxy Nexus/Android 4.4](https://saucelabs.com/beta/tests/725e269c82e745bca8c817b0d06ab0a2/watch)

**Comment by schaferjh** [comment]
@anselmbradford any thoughts on these issues?

**Comment by anselmbradford** [comment]
I have a hunch that at least part of this is lack of support for `aria-expanded` http://caniuse.com/#feat=wai-aria, which would account for the mega menu hamburger menu icon not changing, but I don't think it would disable the menu or the search in the way described. I'll keep digging.

**Comment by sebworks** [comment]
The MegaMenu should now be closing/showing. There is an issue where search is being not being displayed on Android. For some strange reason, commenting out ( or using Mordnzr to conditionally ommit) the line allows it to work on Android. https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/unprocessed/js/molecules/GlobalSearch.js#L174

**Comment by sebworks** [comment]
Discovered that the issue can be resolved by forcing a page reflow; this isn't the most elegant solution but the one we will go with if a better solution isn't found quickly.

**Comment by anselmbradford** [comment]
Fixed in https://github.com/cfpb/cfgov-refresh/pull/1964
