### ISSUE TITLE
Most of the JS is broken on Blackberry

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1672]
The Mega menus, all expandables (Including the in this section) nav do not function.

## Current behavior

When you visit beta.consumerfinance.gov, most functions that require javascript do not work, but js styles are applying, it seems there's a JS error very early in the page.

## Expected behavior

Mega menu, expandables and other JS features should either work or fall back to no-js styles

## Steps to replicate behavior

1. Visit beta.consumerfinance.gov on your Blackberry
2. Menus and Expandables do not open

## Affected Browsers
- Blackberry

**Comment by schaferjh** [comment]
oh Blackberry. :sob:

**Comment by anselmbradford** [comment]
Have any JS been found that works? Beta banner is broken too. Here is the load order of the first scripts in the footer (modernizr, IE scripts, and GTM are loading in the header):

```
require( 'jquery' );
require( 'jquery-easing' );
require( 'cf-expandables' );

// Global modules.
require( '../modules/beta-banner-state' ).init();
```
