### ISSUE TITLE
"In this section" expandable does not open on wagtail pages

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#1673]
Expandables are not opening on several different browsers. I've seen it on Android 5.0 and Blackberry, but I'll add to the issue as I see it other places and see if sauce can give feedback on errors. Seems to be on wagtail pages.

## Current behavior

The "In this section" links do not expand or show the expanded state.

## Expected behavior

- The "In this section" should either expand or be expanded so people can navigate.

## Steps to replicate behavior

1. Visit http://beta.consumerfinance.gov/about-us/budget-strategy/ and shrink to mobile
2. "In This Section" does not open or expand

## Screenshots

![image](https://cloud.githubusercontent.com/assets/1860176/13963658/9982c500-f03c-11e5-8b53-6d3e4bab10b1.png)

**Comment by schaferjh** [comment]
@kurtw @kave Could whatever we did to address #1487 (DFJR-934) help here?

**Comment by kurtw** [comment]
This is being fixed with #1692

**Comment by anselmbradford** [comment]
Is this fixed?

**Comment by schaferjh** [comment]
Yes, appears to be fixed on Refresh.
