### ISSUE TITLE
Multi-select: long names wrap oddly in some cases

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1685]
## Current behavior
- When an item in the multi-select is perfectly the width of the available area the (x) gets indented alone on the next line.
## Expected behavior
- Don't place (x) at the end of the line, but instead place it to the right side of the button. 
## Steps to replicate behavior
1. Check the multiselect on /blog/
## Screenshots

**Current**

![screen shot 2016-03-23 at 2 51 07 pm](https://cloud.githubusercontent.com/assets/704760/14001170/0c949e9a-f11b-11e5-80d2-3421a856f070.png)

**Expected**

Something like:
![screen shot 2016-03-23 at 5 21 28 pm](https://cloud.githubusercontent.com/assets/704760/14001348/bdb30996-f11b-11e5-998b-6ab8170ec04a.png)

**Comment by anselmbradford** [comment]
Still an issue as of 2/13/18

![screen shot 2018-02-13 at 10 46 48 am](https://user-images.githubusercontent.com/704760/36158817-41defada-10ab-11e8-8df7-9e0f0b6cc51d.png)

**Comment by sebworks** [comment]
@mistergone is working on this, so it should be resolved shortly.

**Comment by anselmbradford** [comment]
Reported resolved by @mistergone !
