### ISSUE TITLE
Multi-select: wrapping names in selection list should be indented from checkboxes

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1686]
## Current behavior
- Long names in the checkbox list wrap under their associated checkboxes.
## Expected behavior
- Long names wrap, but don't go under the checkboxes.
## Steps to replicate behavior
1. Check the multi-select on /blog/ and scroll down till you find a long name.
## Screenshots

**Current**

![screen shot 2016-03-23 at 2 51 14 pm](https://cloud.githubusercontent.com/assets/704760/14001403/0d8c3564-f11c-11e5-9f43-0a00e2133ada.png)

**Expected**

![screen shot 2016-03-23 at 5 24 46 pm](https://cloud.githubusercontent.com/assets/704760/14001426/2d71e89c-f11c-11e5-9627-228672a91873.png)

**Comment by sebworks** [comment]
This was fixed in #3801
