### ISSUE TITLE
Inline WP post styles are breaking some pages

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#1690]
Inline WP post styles are breaking some pages.

## Current behavior

- `aside` elements are being styled by inline styles in WP Posts

## Expected behavior

- WP shouldn't be setting any styles

## Steps to replicate behavior

1. Navigate to `/blog/take-a-tour-of-money-as-you-grow-our-new-resource-to-help-parents-and-caregivers-give-children-a-strong-financial-start/`

2. Open the `About Us` menu item on a desktop-ish size

## Screenshots

![screen shot 2016-03-24 at 10 11 20 am](https://cloud.githubusercontent.com/assets/1280430/14023152/0a4bb81c-f1b1-11e5-8edd-744d305601fc.png)

![screen shot 2016-03-24 at 10 42 42 am](https://cloud.githubusercontent.com/assets/1280430/14023156/0f463568-f1b1-11e5-906e-fa2d3bcd8ea4.png)

## Notes 

There may be other instances like this but this is the one I happened upon. Not sure what we're going to have to do to clean them all and prevent any new inline styles from being added.

**Comment by sebworks** [comment]
we can query the pages, using ES, to find out which pages have styles.

**Comment by KimberlyMunoz** [comment]
I thought I removed a lot of this when I started this gig. This is a brand new page. :weary:

**Comment by jimmynotjim** [comment]
I think converting the blog to Wagtail will be the highest priority after launch to avoid stuff like this from happening in the future. We have very little control what happens in WP.

**Comment by schaferjh** [comment]
Besides knocking the featured menu content out of whack and making the text in the inset render at a silly size, is this a more insidious issue in any way?

**Comment by KimberlyMunoz** [comment]
In this one page, I think the FMC is pretty bad, but what you see is what you get.

In general, with the way the classes are being targeted if someone targeted a `section` or worse `.block`, content editors could do some serious damage to the layout.

**Comment by schaferjh** [comment]
:weary: is right

**Comment by schaferjh** [comment]
So this blog post from WP also looks bonkers, but doesn't seem to have the same impact on the mega menu -- http://beta.consumerfinance.gov/blog/mortgage-moves-how-much-can-you-afford/

**Comment by kave** [comment]
Can we use Javascript on blog pages to remove styles in the interim?

**Comment by schaferjh** [comment]
Interesting to note these posts look horrible on the live site as well http://www.consumerfinance.gov/blog/mortgage-moves-how-much-can-you-afford/

**Comment by jimmynotjim** [comment]
This is fixed yeah? cc @schaferjh

**Comment by schaferjh** [comment]
For now anyway!
