### ISSUE TITLE
Header items are misaligned to the rest of the page

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#1693]
## Current behavior

- Header is wider than it should be, misaligning it to the rest of the page. 

## Expected behavior

- Header left/right should align with the contents below

## Steps to replicate behavior

1. Navigate to any page, most noticeable on the homepage

## Screenshots

![screen shot 2016-03-24 at 12 40 34 pm](https://cloud.githubusercontent.com/assets/1280430/14025759/9f6c4950-f1bd-11e5-953d-01b8f8a3307f.png)

![screen shot 2016-03-24 at 12 38 49 pm](https://cloud.githubusercontent.com/assets/1280430/14025753/98dca08a-f1bd-11e5-84a0-ad2f02c48d7c.png)

**Comment by anselmbradford** [comment]
Is this an issue with the header, or with the body content adding additional padding on the left/right?

![screen shot 2016-03-30 at 5 07 16 pm](https://cloud.githubusercontent.com/assets/704760/14157636/e230118c-f699-11e5-8491-9f4ea10e59bf.png)

**Comment by jimmynotjim** [comment]
The body content is supposed to have that space, it's the border of the grid. The header should either use it as well, or limit itself in width.

**Comment by Scotchester** [comment]
We have the `wrapper__match-content` modifier for this purpose.

**Comment by anselmbradford** [comment]
Hm, the banner has `wrapper__match-content` already and is the same width as the other header items. This is going to be a fun one to figure out.

**Comment by jimmynotjim** [comment]
`.grid_column( 1, 1 );` done :D

**Comment by jimmynotjim** [comment]
This got fixed prior to launch, closing out.
