### ISSUE TITLE
/external-site/ stripping URL parameters

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1786]
## Current behavior

- If a link is like `http://refresh.demo.cfpb.gov/external-site/?ext_url=http://twitter.com/intent/tweet?url=http%3A//refresh.demo.cfpb.gov/about-us/the-bureau/leadership-calendar/&via=CFPB&text=%20--`, /external-site/ will strip off the `&via=CFPB` and `&text` bits. 

## Expected behavior

- URL is preserved in its full state through /external-site/ URL.

## Steps to replicate behavior

1. Visit http://refresh.demo.cfpb.gov/about-us/the-bureau/about-director/
2. Click Twitter share button.
3. End up at twitter tweet page without related `@CFPB` in the tweet.

**Comment by anselmbradford** [comment]
cc @kave @kurtw @richaagarwal

**Comment by richaagarwal** [comment]
Thanks Ans! I have a fix up for a similar issue, but didn't think through a more generic solution since I didn't realize this was impacting other types of links.  I'll think of a solution that takes care of all params.

**Comment by kurtw** [comment]
https://github.com/cfpb/cfgov-refresh/pull/1791 Should fix this issue.

**Comment by jimmynotjim** [comment]
Can this be closed then?

**Comment by kurtw** [comment]
Actually, I found a bug I'm about to push up a fix for. Hold off for a bit.

**Comment by kurtw** [comment]
https://github.com/cfpb/cfgov-refresh/pull/1811

**Comment by sebworks** [comment]
@anselmbradford , is this still an issue?

**Comment by kurtw** [comment]
Closing this now that the fix has been in.

**Comment by sebworks** [comment]
thanks @kurt
