### ISSUE TITLE
Sharing: Truncate long pre-made tweet to fit 140 characters

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1787]
Twitter share should truncate long page titles to keep tweet length to 140 characters

## Current behavior

- Currently possible to have a share via twitter pre-made tweet that is over 140 characters in length

## Expected behavior

- Truncate long titles to fit pre-made tweet within Twitter's character limit.

## Steps to replicate behavior

1. Go to /careers/, find a long job title, and click share via Twitter.
2. Note that pre-made tweet URL is too long to tweet without editing the tweet.

## Screenshots

__Current__

![screen shot 2016-04-01 at 12 51 15 pm](https://cloud.githubusercontent.com/assets/704760/14213950/80acb0bc-f808-11e5-94f8-fba9c9c9f8ca.png)

__Expected__

![screen shot 2016-04-01 at 12 51 32 pm](https://cloud.githubusercontent.com/assets/704760/14213955/85fe6c40-f808-11e5-8b14-5ac86d933b2f.png)

**Comment by KimberlyMunoz** [comment]
I'm going to say that it's probably worse to truncate and lose the context than have it automatically truncated and easier to tweet in a single click, but it's probably a UX decision on the trade-off.

**Comment by schaferjh** [comment]
Huh, you know on beta it's only generating tweets with the link, nothing else.

![screen shot 2016-04-01 at 6 15 29 pm](https://cloud.githubusercontent.com/assets/10562545/14221571/c1c0eb5e-f835-11e5-8cde-cc0d306f157f.png)

**Comment by anselmbradford** [comment]
@schaferjh The nothing else is https://github.com/cfpb/cfgov-refresh/issues/1786.
Also, pretty sure the title not coming through is this issue https://github.com/cfpb/cfgov-refresh/pull/1785#discussion_r58230545 I think @kurtw has a fix.

**Comment by schaferjh** [comment]
ah, ok

**Comment by anselmbradford** [comment]
On further thought, I agree with @KimberlyMunoz. For long URLs the title could get unrecognizably mangled. It may be worth exploring excluding the title completely if the URL is too long, but yeah that's a UX decision. Feel free to close this issue @schaferjh

**Comment by schaferjh** [comment]
I am going to close this with a note to my backlog list that it deserves further thought. Erring on the side of too much context for the moment feels safest. Thanks for bringing it up.
