### ISSUE TITLE
design tweaks

### ISSUE THREAD

**Issue by ell0ell0** [cfpb/cfgov-refresh#182]
#### Simply documenting things I see so they aren't forgotten. Backlog and prioritize accordingly.

Sidebar on contact us has some odd spacing happening.

![screen shot 2014-10-29 at 1 45 38 pm](https://cloud.githubusercontent.com/assets/3589375/4831368/eb6b6b00-5f93-11e4-86b6-f7ae0996ad34.png)

need tighter spacing here at the start of a new section

![screen shot 2014-10-29 at 1 51 33 pm](https://cloud.githubusercontent.com/assets/3589375/4831433/7899cdf0-5f94-11e4-8fcc-3ef696fa2217.png)

**Comment by jimmynotjim** [comment]
The design on `/blog/` changed but this still exists on `/newsroom/`

**Comment by KimberlyMunoz** [comment]
Closing in favor of an updated issue in JIRA on spacing.
