### ISSUE TITLE
Full-width content footers?

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cfgov-refresh#183]
@ell0ell0, the issue you noted here appears on all pages with content footers: https://github.com/cfpb/cfgov-refresh/issues/182#issuecomment-60980705

What can we do about it @Scotchester, @virginiacc?

**Comment by jimmynotjim** [comment]
The design on /blog/ changed but this still exists on /newsroom/

**Comment by schaferjh** [comment]
These will definitely continue to exist on pages like newsroom. (I have a couple of them in Policy & Compliance wireframes)

@duelj Do we want the content footer to expand fully out to the right? I thought we had a conversation about that not happening, but I could be mis-remembering.

**Comment by duelj** [comment]
@schaferjh I agree we did talk about them not bleeding to the edge of the viewport. This would be the same for sidebars as well. 

I think we decided against the bleed when the FEWD's had highlighted there may be some difficulties making this happen in code. I am still game to not have the full bleed, I do feel that a stroke makes the edges feel more "finished" though if we go this route. how would you all feel about adding the stroke in? 

|No stroke|Stroke|
---|---
|![screen shot 2015-05-18 at 10 44 26 am](https://cloud.githubusercontent.com/assets/6873734/7683250/ba39d002-fd4b-11e4-98eb-ac3d1d48a65c.png)|![screen shot 2015-05-18 at 10 49 28 am](https://cloud.githubusercontent.com/assets/6873734/7683257/bf4d58ca-fd4b-11e4-8f8f-0753182a57d4.png)|

**Comment by schaferjh** [comment]
Je suis pro-stroke.

**Comment by jimmynotjim** [comment]
Agree, feels more complete vs possibly broken (though that could be the upcoming events placeholder influencing me). Should I add this to the Jira backlog?

**Comment by duelj** [comment]
Yea, sounds like everyone is on board. Sorry for adding another task in with the answer.

**Comment by jimmynotjim** [comment]
Added to Jira and linked back.
