### ISSUE TITLE
/external-site/ is receiving common.js, but is not a full page.

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#1838]
## Current behavior
- /external-site/ is receiving common.js, but is not like the other pages since it doesn't have a header and footer.
## Expected behavior
- /external-site/ should not receive common.js or should have a global header and footer like the rest of the site.
## Steps to replicate behavior
1. visit /external-site/ and check the JS console. Find an error.
## Screenshots

**Current**

![screen shot 2016-04-06 at 1 18 03 pm](https://cloud.githubusercontent.com/assets/704760/14326173/cc25d0aa-fbfa-11e5-8499-d76e0aa28c39.png)

**Expected**

Should not have JS errors.

**Comment by sebworks** [comment]
This has been fixed.
