### ISSUE TITLE
Wagtail Admin: Padded zeros on event zipcodes

### ISSUE THREAD

**Issue by kave** [cfpb/cfgov-refresh#1842]
Event Pages zipcodes do not display padded zeros. Can be confusing to content.
## Current behavior
- Save `00140` as a zip but it displays as `140`
## 
## Steps to replicate behavior
1. Create an Event page with a venue zipcode `00140`
## Fix
- Override wagtail template to account for padded zeros

**Comment by anselmbradford** [comment]
@cfpb/cfgov-backends is this still an issue?

**Comment by chosak** [comment]
@anselmbradford yes, if you save a zipcode with leading zeros, the block removes them:

![image](https://user-images.githubusercontent.com/654645/38995995-3278426e-43b8-11e8-8439-f0e6b5305923.png)

and then the zipcode gets rendered without those zeros:

![image](https://user-images.githubusercontent.com/654645/38996025-41f900d4-43b8-11e8-8699-65bc7cee2bba.png)

**Comment by epicfaace** [comment]
Moreover, it looks like this will require some data migration to actually cast ints to strings: https://stackoverflow.com/a/33404876/1950269

**Comment by anselmbradford** [comment]
Maybe that's the issue at https://github.com/USAJOBS/design-system/issues/159 too!

**Comment by jedisnowrob** [comment]
RealZipCode = 
SWITCH(
    TRUE(),
    LEN('Table'[ZipCode]) = 5, 'Table'[ZipCode],
    LEN('Table'[ZipCode]) = 4, "0" & 'Table'[ZipCode],
    LEN('Table'[ZipCode]) = 3, "00" & 'Table'[ZipCode]
)

**Comment by jedisnowrob** [comment]
ZIP = RIGHT("00000" & 'myaddresses'[myzip], 5)


Zipcode(zipcode=u'10001', zipcode_type=u'Standard', major_city=u'New York', post_office_city=u'New York, NY', common_city_list=[u'New York'], county=u'New York County', state=u'NY', lat=40.75, lng=-73.99, timezone=u'Eastern', radius_in_miles=0.9090909090909091, area_code_list=[u'718', u'917', u'347', u'646'], population=21102, population_density=33959.0, land_area_in_sqmi=0.62, water_area_in_sqmi=0.0, housing_units=12476, occupied_housing_units=11031, median_home_value=650200, median_household_income=81671, bounds_west=-74.008621, bounds_east=-73.984076, bounds_north=40.759731, bounds_south=40.743451)

>>> zipcode.values() # to list
[u'10001', u'Standard', u'New York', u'New York, NY', [u'New York'], u'New York County', u'NY', 40.75, -73.99, u'Eastern', 0.9090909090909091, [u'718', u'917', u'347', u'646'], 21102, 33959.0, 0.62, 0.0, 12476, 11031, 650200, 81671, -74.008621, -73.984076, 40.759731, 40.743451]

>>> zipcode.to_dict() # to dict
{'housing_units': 12476, 'post_office_city': u'New York, NY', 'bounds_east': -73.984076, 'county': u'New York County', 'population_density': 33959.0, 'radius_in_miles': 0.9090909090909091, 'timezone': u'Eastern', 'lng': -73.99, 'common_city_list': [u'New York'], 'zipcode_type': u'Standard', 'zipcode': u'10001', 'state': u'NY', 'major_city': u'New York', 'population': 21102, 'bounds_west': -74.008621, 'land_area_in_sqmi': 0.62, 'lat': 40.75, 'median_household_income': 81671, 'occupied_housing_units': 11031, 'bounds_north': 40.759731, 'bounds_south': 40.743451, 'area_code_list': [u'718', u'917', u'347', u'646'], 'median_home_value': 650200, 'water_area_in_sqmi': 0.0}

>>> zipcode.to_json() # to json
{
    "zipcode": "10001",
    "zipcode_type": "Standard",
    "major_city": "New York",
    "post_office_city": "New York, NY",
    "common_city_list": [
        "New York"
    ],
    "county": "New York County",
    "state": "NY",
    "lat": 40.75,
    "lng": -73.99,
    "timezone": "Eastern",
    "radius_in_miles": 0.9090909090909091,
    "area_code_list": [
        "718",
        "917",
        "347",
        "646"
    ],
    "population": 21102,
    "population_density": 33959.0,
    "land_area_in_sqmi": 0.62,
    "water_area_in_sqmi": 0.0,
    "housing_units": 12476,
    "occupied_housing_units": 11031,
    "median_home_value": 650200,
    "median_household_income": 81671,
    "bounds_west": -74.008621,
    "bounds_east": -73.984076,
    "bounds_north": 40.759731,
    "bounds_south": 40.743451
}

**Comment by higs4281** [comment]
Sorry, @jedisnowrob 
I addressed this on the back end in [PR 5130](https://github.com/cfpb/cfgov-refresh/pull/5130) and neglected to close the issue.
