### ISSUE TITLE
consumerfinance.gov should use HTTPS and HSTS

### ISSUE THREAD

**Issue by konklone** [cfpb/cfgov-refresh#1993]
The CFPB's newly redesigned [consumerfinance.gov](http://www.consumerfinance.gov) should default to HTTPS, so that its users are given a safe experience.
## Current behavior
- consumerfinance.gov can not be reached securely or privately by its users. Its users are subject to potential [non-consented tracking](http://www.forbes.com/sites/kashmirhill/2014/10/28/find-out-whether-this-privacy-killing-super-cookie-is-on-your-phone/), [content injection](http://arxiv.org/abs/1602.07128), and other [malware attacks](https://citizenlab.org/2015/04/chinas-great-cannon/).
## Expected behavior
- consumerfinance.gov should employ [HTTPS](https://https.cio.gov/) and [HSTS](https://https.cio.gov/hsts/) to ensure its users have a [safe and private experience](https://https.cio.gov/everything/).
## Steps to replicate behavior
1. Type "consumerfinance.gov" into browser.
2. Get redirected to `http://www.consumerfinance.gov`.
3. Frown, manually click on location bar, prepend URL with `https://`, hit Enter.
4. Get brought to full-screen certificate warning, as Akamai has not been configured to return a certificate valid for `www.consumerfinance.gov`.
5. The corners of the user's frown begin to tug and twitch, until a single tear begins rolling down the user's cheek.
## Screenshots

**Current**

![image](https://cloud.githubusercontent.com/assets/4592/14754561/1e18f296-08aa-11e6-8ee4-2b05aa4a721c.png)

**Expected**

Imagine the below image but with the grey lock icon with an X through it replaced with a beautiful green lock icon:

![image](https://cloud.githubusercontent.com/assets/4592/14754575/39f1266e-08aa-11e6-8053-a0e70bdaccab.png)

**Comment by Scotchester** [comment]
Thanks for continuing to gently prod us, @konklone :) This is definitely on our list of things to do "soon".

**Comment by rosskarchner** [comment]
it will be done, even if I this is the hill I die on.

**Comment by rosskarchner** [comment]
I wouldn't be foolish enough to offer an estimate, *but* I'm comfortable saying that the wheels are turning on this, faster than they have at any point in the past year.

**Comment by rosskarchner** [comment]
Making progress, @konklone https://pulse.cio.gov/https/domains/#q=www.consumerfinance.gov  ;)

**Comment by anselmbradford** [comment]
@rosskarchner can this be closed?

**Comment by rosskarchner** [comment]
YES!

**Comment by konklone** [comment]
:tada:
