### ISSUE TITLE
Future of this code

### ISSUE THREAD

**Issue by rosskarchner** [cfpb/cfgov-refresh#2070]
I've been in and heard some conversations about what happens with the code currently in cfgov-refresh, and where new code targeting cf.gov should go. I thought it was worth capturing my thoughts, and giving the discussion a URL.

First: I don't mean to imply that this code _must_ be broken up. Maybe the thing to do is just give it a more permanent name, and continue improving the code structure within this repo.

Second: This reflects a BEWD/Django view of the universe. There may be be front-end nuances that make this particular structure infeasible or inadequate.

So, here's how _I_ imagine this codebase evolving, mostly into three new repo's:
- **cfgov-common**: the base templates, images,  and front-end code needed to make a Django app that looks like it belongs on consumerfinance.gov. 
- **cfgov-django**: the "project" code (settings, urls, etc),  legacy Django apps  and assets that never quite made it to open source that we're still using (like jobmanager, the leadership calendar), utilities like sheerlike and our customization to the login system and password policy enforcement. Maybe Vagrant configs can live here too.
- **cfgov-cms**:  Wagtail-specific code, like Page subclasses, our sharing customizations, and templates, images, and front-end code that exist for supporting the CMS.

One question I have: do atomic elements have a life outside of the CMS (ie, do they belong in common or in CMS)?
## Where should new code go?

That's a big question. Looking into the immediate future, it seems natural that the team working on Policy & Compliance will continue to work in the same code base (in the proposal above, cfgov-cms), instead of spinning out a separate app. I wonder how that changes for things with larger scope, like something the size of Owning a Home or Ask CFPB.

**Comment by jimmynotjim** [comment]
From a front-end perspective, atomic elements will have a life outside the CMS, it's just unclear when exactly that'll happen.

**Comment by kurtw** [comment]
@rosskarchner I like this setup. @jimmynotjim I tend to agree, but I think it would be a mistake to do it too soon. A couple of things:

1. Front-end and back-end aren't entirely separate.
2. Templates should probably live in cfgov-cms and if there needs to be a markup change in the separated atomic elements codebase then that requires another PR for cfgov-cms.

But...

Separating out the codebases could help scale development, as long as there's a clear and defined contract between backends and frontends about versions, keeping up with tests, documentation, etc. It _could_ help with deployments, ease of separate workstreams, possibly release planning. I'm starting to climb out on a limb here but these are just some suggestions. Also, if we decide to do this that would mean we'd have 4 repositories to maintain (+__atomic-elements__).

**Comment by rosskarchner** [comment]
I guess, by "life outside of the CMS", I was musing on whether they naturally live next to cfgpv-cms or cfgov-common

**Comment by kave** [comment]
i would imagine the frontend assets would live in `cfgov-cms` because the templates are directly tied to the models, you can't have 1 without the other.

**Comment by kurtw** [comment]
@kave I think there's talk of separating the frontend and backend builds so `pip` wouldn't be dependent on npm or grunt or anything. @vickumar1981 and @vccabral should probably chime in on this and on this issue in general.
