### ISSUE TITLE
Homepage: Automate percentage of timely responses to match the Consumer Complaint Database landing

### ISSUE THREAD

**Issue by cfarm** [cfpb/cfgov-refresh#2079]
## Current behavior

Currently, the [homepage of consumerfinance.gov](http://www.consumerfinance.gov/) uses a static number for the "% of consumers
get timely replies when we send their complaints to companies" copy:

![screen shot 2016-05-12 at 12 44 59 pm](https://cloud.githubusercontent.com/assets/702526/15222803/5dd33726-183f-11e6-9ef7-538a7d69497b.png)

This same statistic appears on the [Consumer Complaint Database landing page](http://www.consumerfinance.gov/data-research/consumer-complaints/), where it is automated and updated daily based on the database values:

![screen shot 2016-05-12 at 12 47 01 pm](https://cloud.githubusercontent.com/assets/702526/15222884/a7917012-183f-11e6-9cec-d2300abcf2f0.png)

Notice the problem: the static number becomes outdated and doesn't always match the automated number from the database.
## Expected behavior
- The homepage + CCDB landing page should reflect the same number at all times. 

To automate this permanently, we can reuse the code from the CCDB landing page. There is a short term fix that updates the static number here: #2078

**Comment by cfarm** [comment]
@schaferjh Any updates on when this might happen?

**Comment by schaferjh** [comment]
We’ve run into some delays in getting stakeholder agreement on our next batch of home page updates, but I am working diligently on this and will let you know as soon as we’re approved to move forward.

**Comment by rosskarchner** [comment]
I just wanted to capture some thoughts on the approach. We could...

1. import [get_narratives_json](https://github.cfpb.gov/CCDB4/CCDB-content/blob/master/complaintdatabase/views.py#L45) and insert the percentage into the [homepage context](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/v1/models/home_page.py) (and edit the template to use it) this is the simplest, and creates the least duplication-- but it does create a dependency between cfgov-refresh and the (non open source) CCDB-content repo, which is something we've been avoiding (mostly via the [OPTIONAL_APPS](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/cfgov/settings/base.py#L64) mechanism). In other words, it becomes no longer optional.
2. We can do the above, but add some sort of failover behavior, so if a developer is running cfgov-refresh without the CCDB app installed, things don't break. The app remains optional.
3. We could just copy the get_narratives_json logic into cfgov-refresh somewhere. This creates some duplication, but 14 lines isn't *too* terrible.
4. combine 2 and 3: (try to use CCDB's version of get_narratives_json, failover to our own). This feels like the most robust, but also kind of a silly dance to do.

Of those, I think I'd favor number 2. Thoughts @kave @richaagarwal @kurtw?

It's probably overkill for right now, but I think the future direction for stuff like this would be: apps that want to provide content for use elsewhere on the site (the homepage or anywhere else) should expose [snippets](http://docs.wagtail.io/en/v1.3.1/topics/snippets.html) and/or [streamfield blocks](http://docs.wagtail.io/en/v1.3.1/topics/streamfield.html).

**Comment by kurtw** [comment]
I think number 2 is the best option as well. 

> apps that want to provide content for use elsewhere on the site (the homepage or anywhere else) should expose snippets and/or streamfield blocks.

👍

**Comment by richaagarwal** [comment]
Hmm, but the data lives in a public API (the json file) and it's pretty standard for multiple apps to be making similar calls to the same API - I don't see that as duplication. I think we should just have our own code that grabs the json and fetches `percent_timely`. So I guess none of the above options 😈

**Comment by rosskarchner** [comment]
@richaagarwal fair point

**Comment by anselmbradford** [comment]
@cfpb/cfgov-backends is this still an issue?

**Comment by chosak** [comment]
@anselmbradford yes, this [is still hardcoded](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/index.html#L169) on the homepage and it would be nice if it were consistent with the CCDB landing page.

**Comment by anselmbradford** [comment]
Homepage content was removed in the homepage redesign so there is no longer content to keep in sync.
