### ISSUE TITLE
Specificity & list-links

### ISSUE THREAD

**Issue by virginiacc** [cfpb/cfgov-refresh#218]
I noticed that the state border color changes on a `.list_link` within a `.list__links` list are being overridden, so a visited `.list_link` will have `@pacific` borders on mobile sizes. This seems to be due to specificity, since a dotted `@pacific` border is applied to `.list__links .list_link`. I can substitute `.jump-link` in my offices page instance, but I don't know if that will always be the case.

**Comment by juidai** [comment]
Notes from usability feedback and how we agreed to handle link-list styles.

- links should be blue to look like link style
- onHover, underline link
- links should be bumped down. it is not proportional to the rest of the page

![link-list](https://cloud.githubusercontent.com/assets/6623411/5630664/c458c7b2-958d-11e4-9a1a-58e0d3729718.png)

**Comment by jimmynotjim** [comment]
@Scotchester hows that underline thing going, still in process?

**Comment by virginiacc** [comment]
I think this is an example of what I was referring to above:

<img width="403" alt="screen shot 2015-07-20 at 6 56 37 pm" src="https://cloud.githubusercontent.com/assets/778171/8789522/203821fa-2f11-11e5-82a6-d147a4cf79c9.png">

The text of the visited 'director' link on '/the-bureau' page is `@teal`, but the borders are still `@pacific`.

**Comment by KimberlyMunoz** [comment]
Thanks Virginia!

@Scotchester -- Is this something you're working on or is this up-for-grabs?

**Comment by KimberlyMunoz** [comment]
Here's the line issue that Scott's working on.

https://github.com/cfpb/design-manual/issues/244

**Comment by KimberlyMunoz** [comment]
I did a little digging on this and it looks like it's by design. If the border-color changes, it'll only change the border above the visited link. I'm going to close since we'd have to go back to design to fix and I don't think it'll get tackled any time soon.
