### ISSUE TITLE
Form number identifier vulnerable to changing based on user input

### ISSUE THREAD

**Issue by kurtrwall** [cfpb/cfgov-refresh#2200]
The number appended to the form input fields in a filterable list is the loop index of the blocks in the StreamField that the filterable list exists in. If a user adds another block of content before the filterable list in the StreamField then that number will change. Luckily, links across the site will change along with it. However, any link that's saved before this change occurs will be broken. We want to make this number permanent in case of this.
## Current behavior
- The form number that is appended to all form fields is subject to change based on user input.
## Expected behavior
- The form number should be static regardless of position in Streamfield.
## Steps to replicate behavior
1. Note the number in the blog fields in their ID attribute, or even just filter on some parameter and note it in the url.
2. edit the blog index page and add a block before the filterable list controls block. Publish the page.
3. Go back to the blog and note the number has changed.

**Comment by anselmbradford** [comment]
@cfpb/cfgov-backends Is this still an issue?

**Comment by schbetsy** [comment]
This is no longer an issue. Input fields don't have an integer identifier in the ID. Closing.
