### ISSUE TITLE
Custom request error handlers always return 200

### ISSUE THREAD

**Issue by kurtw** [cfpb/cfgov-refresh#2215]
200 OK responses are not OK when there's a server error (500) or a file not found (404). 

## Current behavior

- When the server wants to respond with a 404 or 500, [we're catching it](https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/cfgov/urls.py#L304) and always returning a 200 even though it serves back the appropriate 404.html or 500.html page.

## Expected behavior

- The when there's an error during a request, the appropriate page 404.html/500.html is served back, and the response has the appropriate status.

## Steps to replicate behavior

1. go to bad url http://www.consumerfinance.gov/not-found/
2. see 404 page
3. run `curl -I http://www.consumerfinance.gov/not-found/`
4. see 200 status

**Comment by rosskarchner** [comment]
This was fixed in today's hotfix (107dcfc2a0fa821b33042bc401aacc1748599441) , now merged in to flapjack

**Comment by kurtw** [comment]
@rosskarchner is the Platform team closing issues on merge or release?
