### ISSUE TITLE
Log server errors to a file

### ISSUE THREAD

**Issue by kurtrwall** [cfpb/cfgov-refresh#2216]
The server errors only log the error to an email sent to the site admins. Maybe we should log them to a local file on the server as well.

**Comment by anselmbradford** [comment]
@cfpb/cfgov-backends Is this still an issue?

**Comment by chosak** [comment]
@anselmbradford I don't believe so. In production [we log errors to syslog](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/cfgov/settings/production.py#L19) which goes to the local system and to other downstream listeners.
