### ISSUE TITLE
Jenkins job to load Credit Card Agreements data failures

### ISSUE THREAD

**Issue by kurtrwall** [cfpb/cfgov-refresh#2223]
When @kave was showing me the in's and out's of the ccdb data loading job, the `/tmp/credit-agreements` folder was missing, causing the job to fail. It's possible that it has something to do with RHEL6's [`/etc/cron.daily/tmpwatch`](http://linux.die.net/man/8/tmpwatch) which clears out the tmp directory by age. Combine that with the fact that data only gets loaded once a quarter and we have a possible reason for the missing directory.

That, or someone just deleted it without knowing what it was for but I don't think that's likely.
## Current behavior
- When running the Jenkin's job to load data into the CCDB, the tmp directory to copy to is missing causing build failures.
## Expected behavior
- The tmp directory should be present.
## Steps to replicate behavior
1. Run Jenkins job
2. See failure

**Comment by kurtw** [comment]
Two caveats:
1. You probably won't see the failure since we've created the directory recently.
2. This might just be alarmist.

Still, I figure this should be documented somewhere.

**Comment by anselmbradford** [comment]
@cfpb/cfgov-backends Is this still an issue?
