### ISSUE TITLE
[BUG] scary search result "Your connection is not private" page

### ISSUE THREAD

**Issue by amycesal** [cfpb/cfgov-refresh#2231]
## Current behavior
- Search results page linked to HTTPS versions of pages. Results in warning page. SCARY! 
## Expected behavior
- no warning page. linked to HTTP version
## Screenshots

**Current**

http://search.consumerfinance.gov/search?utf8=%E2%9C%93&affiliate=cfpb&query=fall+consumer+advisory+board

https://www.consumerfinance.gov/about-us/advisory-groups/consumer-advisory-board/

![screen shot 2016-07-20 at 10 30 39 am](https://cloud.githubusercontent.com/assets/1656046/16991457/a35e95f0-4e69-11e6-94f3-f930caf92121.png)
![screen shot 2016-07-20 at 10 30 52 am](https://cloud.githubusercontent.com/assets/1656046/16991456/a35af12a-4e69-11e6-8dbc-553baca988aa.png)

**Comment by rosskarchner** [comment]
I'll reach out to @ErikSArnold at GSA.

**Comment by anselmbradford** [comment]
@rosskarchner This can be closed, right?

**Comment by rosskarchner** [comment]
Yes!
