### ISSUE TITLE
[BUG] search bar text overlaps

### ISSUE THREAD

**Issue by amycesal** [cfpb/cfgov-refresh#2232]
Short description explaining the high-level reason for the new issue.
## Current behavior
- The words in the search bar overlap the magnifying glass icon and the clear button. 
## Expected behavior
- There's more padding so things don't overlap
## Steps to replicate behavior
1. type lots of words into the search bar on the homepage in chrome. 
## Screenshots

**Current**

![screen shot 2016-07-20 at 10 29 39 am](https://cloud.githubusercontent.com/assets/1656046/16992004/a1fd0852-4e6b-11e6-9e1c-bbdfed937325.png)

**Comment by anselmbradford** [comment]
Yeah, something crept into the search CSS in the spring to throw it off, see [original PR](https://github.com/cfpb/cfgov-refresh/pull/1342).

**Comment by sebworks** [comment]
@anselmbradford, looks fine on http://www.consumerfinance.gov/your-story/.

**Comment by anselmbradford** [comment]
@sebworks oh weird! Looks like the text input is still a little off in tell your story, but the button isn't. Hmmm

**Comment by schaferjh** [comment]
I believe /your-story/ might have a different header than the home page/other Wagtail-backed pages -- isn't it a sheer page?

**Comment by Scotchester** [comment]
It's a WordPress page.

**Comment by sebworks** [comment]
@Scotchester @anselmbradford , the css should be the same for both pages, right? Sounds like CSS scoping issue.

**Comment by anselmbradford** [comment]
This is sort of fixed, though it's really tight still:
![screen shot 2017-08-10 at 12 58 31 pm](https://user-images.githubusercontent.com/704760/29182122-abc1417e-7dcb-11e7-93d9-1ab838601150.png)

**Comment by anselmbradford** [comment]
Still an issue as of 2/13/2018

**Comment by jimmynotjim** [comment]
The clear text will be going away with the CF icons svg update. I've already fixed it on our in-progress cfgov branch but adding a comment here so I hopefully remember to check on non-wagtail pages as well.

**Comment by anselmbradford** [comment]
This was fixed, possibly in https://github.com/cfpb/cfgov-refresh/pull/4125
