### ISSUE TITLE
About > Doing business with us > Small, women-owned, and minority-owned businesses LINK NEEDED

### ISSUE THREAD

**Issue by juidai** [cfpb/cfgov-refresh#224]
PDF link - 
http://files.consumerfinance.gov/f/201310_cfpb_omwi_opportunities_trifold_final.pdf

![link-needed-1](https://cloud.githubusercontent.com/assets/6623411/5630934/500c999e-9590-11e4-970a-9e32fc6112aa.png)

**Comment by himedlooff** [comment]
I'll tackle this quickly
