### ISSUE TITLE
[BUG] Filter Button disappears when multiple Topics selected

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#2248]
Filter Button disappears when multiple Topics selected

## Current behavior

- Filter Button disappears when multiple Topics selected

## Expected behavior

- Filter will adjust to be the correct height. `Apply Filters` button will be visible.

## Steps to replicate behavior

1. Visit `http://www.consumerfinance.gov/about-us/blog/?form-id=1&filter1_title=&filter1_topics=Mortgages&filter1_topics=Financial+education&filter1_topics=Students&filter1_topics=Student+loans&filter1_from_date=&filter1_to_date=` on any browser and observe the filter button isn't visible.

## Screenshots

Current:

<img width="793" alt="screen shot 2016-07-27 at 8 13 08 am" src="https://cloud.githubusercontent.com/assets/1696212/17174799/09700104-53d2-11e6-82be-d18b828ee403.png">

Expected:

<img width="774" alt="screen shot 2016-07-27 at 8 14 28 am" src="https://cloud.githubusercontent.com/assets/1696212/17174827/2e0f75bc-53d2-11e6-8c25-0de96f0054c8.png">

**Comment by schaferjh** [comment]
I've moved this to the platform team board to be addressed: GHE/CFGOV/platform/issues/145.

Will close this issue once a fix is in review.

**Comment by sebworks** [comment]
Fixed in https://github.com/cfpb/cfgov-refresh/pull/2257
