### ISSUE TITLE
multi-select: inconsistent categorization

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2249]
Multi-select related files appear under both atom and molecule.
## Screenshots

![screen shot 2016-07-27 at 12 35 58 pm](https://cloud.githubusercontent.com/assets/704760/17183788/1c4ea6f2-53f7-11e6-85dd-ee0276b6443f.png)

**Comment by KimberlyMunoz** [comment]
The issue of solving it here will probably be resolved when it's added to capital framework. 

https://github.com/cfpb/capital-framework/issues/344

**Comment by sebworks** [comment]
Issue was closed in #2270
