### ISSUE TITLE
About > Doing business with us > Small, women-owned, and minority-owned businesses content suggestions

### ISSUE THREAD

**Issue by juidai** [cfpb/cfgov-refresh#225]
Merge the title of "Current awards to small businesses" with "FY13" into "FY13 awards to small businesses"

![fy13-title](https://cloud.githubusercontent.com/assets/6623411/5631007/f4fe7c74-9590-11e4-98b6-bdb3e49b91ed.png)

**Comment by himedlooff** [comment]
This is a WP content change. We can update it in build but it will also need to be updated in content. I wonder how we should handle changes like this?

**Comment by juidai** [comment]
I'll log this in Jira and assign it to Jame.

**Comment by juidai** [comment]
I'll log this in Jira and assign it to Jame.
