### ISSUE TITLE
About > Doing business with us -- contact info

### ISSUE THREAD

**Issue by juidai** [cfpb/cfgov-refresh#226]
we have a rule to remove personal contact information and to use contact CMS. we should enforce that rule here in case david.gragan@cfpb.gov leaves CFPB.

![contact-procurement](https://cloud.githubusercontent.com/assets/6623411/5631088/ba6a3138-9591-11e4-998a-1a1fef9118e8.png)

**Comment by himedlooff** [comment]
To clarify, we should 1) create a new "doing business with us" contact and then 2) use the primary email for that contact instead of david.gragan@cfpb.gov, right?

Do you have an email to use as the primary email for "doing business with us"?

**Comment by juidai** [comment]
Yes, you are correct. I do not have another primary email address. This is also something we need to review with James.

**Comment by juidai** [comment]
move it to jira
