### ISSUE TITLE
[BUG] Some headers not receiving correct CSS/JS

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2264]
## Current behavior

- On-demand header fails in IE8 because `Node` is not defined in https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/js/modules/util/behavior.js#L74

## Expected behavior

- Check existence of `Node` support before calling it or check `nodeType` instead (see http://stackoverflow.com/questions/13377887/javascript-node-undefined-in-ie8-and-under)

## Steps to replicate behavior

1. Run `gulp scripts:ondemand`
2. Open `/test-fixture/` in sauce labs (won't work in local VM unless localhost routing is set up).
3. See error in JS console that a function is expected for Node.

## Screenshots

__Current__

![screen shot 2016-07-29 at 7 42 49 pm](https://cloud.githubusercontent.com/assets/704760/17266307/aaffdfe6-55c4-11e6-8304-5081b5810e3a.png)

**Comment by anselmbradford** [comment]
In on-demand header `behaviorElement` where this error is thrown is actually the string `a[href^="#"]``, but it hits the second `else if` that checks `Node` before getting to the third `String` check.

**Comment by sebworks** [comment]
I thought IE8 was getting the no JS experience.

**Comment by anselmbradford** [comment]
@sebworks ah right, good point! The on-demand header must not be falling back properly.

**Comment by sebworks** [comment]
@anselmbradford, can i close this issue?

**Comment by anselmbradford** [comment]
I believe this is still a cfgov-refresh issue in that https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/legacy/templates/front/base_update.html looks like it needs [this code](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/legacy/templates/front/base_nonresponsive.html#L128-L136). @rosskarchner do you know what pages are using `base_update.html` linked above?
