### ISSUE TITLE
Run `npm test` from `gulp test`

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2303]
## Current behavior
- `npm test` runs snyk npm package vulnerability scan.
## Expected behavior
- Tie snyk vulnerability scan into gulp test workflow, e.g. if `gulp audit:security` is run, the snyk vulnerability scan is run.

**Comment by KimberlyMunoz** [comment]
It should be the opposite way around. `npm test` should be the default command that runs the default gulp task.

**Comment by anselmbradford** [comment]
That too

**Comment by anselmbradford** [comment]
Running `snyk test` from node's spawn runs into permission issues.

**Comment by wpears** [comment]
Closing in favor of https://github.com/cfpb/cfgov-refresh/issues/3576
