### ISSUE TITLE
our tests no longer require mysql, but tox does

### ISSUE THREAD

**Issue by rosskarchner** [cfpb/cfgov-refresh#2306]
We recently refactored our Python tests to no longer require MySQL (yay!) BUT....
- `tox` processes all of requirements/base.txt
- base/requirements.txt requests `mysql-python==1.2.5`
- which fails if  you don't actually have mysql installed
## Current behavior

```
Collecting MySQL-python==1.2.5 (from -r /home/theross/Projects/cfgov-refresh/requirements/base.txt (line 16))
  Downloading MySQL-python-1.2.5.zip (108kB)
    Complete output from command python setup.py egg_info:
    sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-XC8JhU/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
```
## Expected behavior

tox runs without incident.
## Steps to replicate behavior

1.`tox`

**Comment by chosak** [comment]
@rosskarchner actually this is no longer true:

> no longer require MySQL

 I did temporarily remove the Python test dependence on MySQL in [cfgov-refresh#2227](https://github.com/cfpb/cfgov-refresh/pull/2227) but it was restored (albeit in a faster way) in [cfgov-refresh#2242](https://github.com/cfpb/cfgov-refresh/pull/2242).

**Comment by rosskarchner** [comment]
I think this is no longer the case?

**Comment by rosskarchner** [comment]
Thanks @chosak for pointing out that it is almost certainly *still* the case

**Comment by rosskarchner** [comment]
This is either no longer a problem, or isn't causing us any actual problems.
