### ISSUE TITLE
Compare JS bundling solutions

### ISSUE THREAD

**Issue by contolini** [cfpb/cfgov-refresh#2313]
Set up https://www.npmjs.com/package/webpack-closure-compiler and run some size and performance benchmarks comparing it to our current webpack config.

See https://github.com/nolanlawson/cost-of-small-modules.

cc @KimberlyMunoz @sebworks @virginiacc

**Comment by ascott1** [comment]
:+1:

**Comment by sebworks** [comment]
yeah, lets do it. I think we can reduce our JavaScript footprint by 50%.
