### ISSUE TITLE
--sauce CLI flag is broken

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2324]
At some point the Sauce Connect `--sauce` flag broke and doesn't work anymore. Fixing this issue should really address https://github.com/cfpb/cfgov-refresh/issues/885 as well.

Also, https://github.com/cfpb/cfgov-refresh/issues/887 and https://github.com/cfpb/cfgov-refresh/issues/886 are Sauce issues.
## Current behavior
- Tests run with and without the `--sauce` flag do not run on Sauce, even with the `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` credentials set in `.env`.
## Expected behavior
- Tests run with the `--sauce=true` flag set should attempt to run tests through a local running Sauce Connect tunnel. (In the past the behavior was also make this the default, so no `--sauce` flag at all would be equivalent to its value being true.)
## Steps to replicate behavior
1. Set `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` credentials in `.env` and uncomment `SAUCE_SELENIUM_URL`.
2. Run `gulp test:acceptance --sauce=true` and note that there are no errors around Sauce connect not running and the tests run locally as if `gulp test:acceptance --sauce=false` were set.

**Comment by sebworks** [comment]
Fixed in #3040

**Comment by sebworks** [comment]
> (In the past the behavior was also make this the default, so no --sauce flag at all would be equivalent to its value being true.)

I've modified the code to not default to  Sauce because it does require setting `.env` variables and runs externally.
