### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by rosskarchner** [cfpb/cfgov-refresh#239]
There should be a screenshot in the README, like this:

![screen shot 2015-01-28 at 10 47 12 am](https://cloud.githubusercontent.com/assets/235397/5940816/3529246a-a6db-11e4-9bfc-76d5b5220a36.png)

(dummy issue to upload the image)

**Comment by anselmbradford** [comment]
Fixed in https://github.com/cfpb/cfgov-refresh/pull/243
