### ISSUE TITLE
Add JS module loader?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#244]
Had a discussion with @jimmynotjim @himedlooff @sebworks ... it sounds like it would be helpful to modularize the JS in this repo and use a module loader. Using browserify and following the architecture of owning-a-home probably makes the most sense.

**Comment by ascott1** [comment]
BIG :+1: I'm a fan of this approach.

**Comment by himedlooff** [comment]
Been working in OAH for a bit and I am digging this approach so far. The only thing is that I wish adding new JS files was easier. Maybe documentation would help?
