### ISSUE TITLE
_vars-budget has trailing comma in array

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#245]
https://github.com/cfpb/cfgov-refresh/blob/gh-pages/budget/_vars-budget.html#L8
has a trailing comma for the last item in the array. This looks like it shouldn't be there.

**Comment by jimmynotjim** [comment]
The `&` should prob be an `&amp;` as well.

**Comment by Scotchester** [comment]
We decided to allow unencoded **unambiguous** ampersands, based on the excellent research in [this article](https://mathiasbynens.be/notes/ambiguous-ampersands) by Mathias Bynens.

**Comment by Scotchester** [comment]
I also prefer leaving trailing commas in arrays/objects, where allowable, because it makes it less likely you'll make a mistake when manipulating the array later.

**Comment by jimmynotjim** [comment]
Cool, just a matter of getting used to existing coding styles.

**Comment by Scotchester** [comment]
Yep :) Also, always happy to hear reasoned counterarguments, if you have them.

**Comment by anselmbradford** [comment]
Resolved as coding style
