### ISSUE TITLE
Document browser support for the site

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#251]
Document browser support for the site so we know what browsers to check changes on.

**IE**
I believe cfgov-refresh is supposed to have support back to IE7, but I believe OAH only has support back to IE8, so how will that be reconciled? When will we drop IE7 support?

**Evergreen browsers**
Modern operating systems will keep these browsers (Firefox, Chrome) on the latest versions (if the user accepts updates). But these will be capped at certain versions for older OSs. What OS platform versions do we care about? (e.g. back to XP?).

**Mobile**
What mobile browsers/versions are we supporting? e.g. what iOS versions (some say Mobile Safari is the new IE7, great), Android, Chrome on Android, Opera mini, Blackberry browser, etc.?

**Comment by anselmbradford** [comment]
Note, there is internal documentation on this to draw from.

**Comment by schaferjh** [comment]
@anselmbradford internal documentation elsewhere on git or elsewhere? would you link to it?

**Comment by anselmbradford** [comment]
@schaferjh PM, I'm told not to link to the intranet addresses from public github.

**Comment by marcesher** [comment]
@anselmbradford Cybersecurity team has indicated they do not want any internal URLs out in the public

**Comment by anselmbradford** [comment]
Related to https://github.com/cfpb/front-end/issues/31
