### ISSUE TITLE
View(s) CPT

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#252]
Has anyone considered renaming the "Views" post type? It can be confusing in discussions whether we're talking about the post type or the presentation layer.

**Comment by anselmbradford** [comment]
+1

**Comment by jimmynotjim** [comment]
After working on the project more, I'm inclined to say we should get rid of the Views CPT and move everything into the code. Anyone have a good reason to keep it (especially since we're only using it on a few pages that won't be updated _that_ often)

**Comment by anselmbradford** [comment]
cc @kurtw @dpford

**Comment by dpford** [comment]
I agree.  When someone asks "What is a view?" it's too hard to explain.  The benefits don't outweigh the added complexity.  I think it would be fine to move it into the code.

**Comment by kurtw** [comment]
:+1:

**Comment by rosskarchner** [comment]
hmmm--- I agree with all of the above, and yet I think we might still want some mechanism for managing metadata and things like heroes for pages that are otherwise un-typed.

But maybe the current "views" system isn't a step on that path.

**Comment by jimmynotjim** [comment]
WP has a built in way to do heros, "make sticky". I'm sure any future CMS would as well.

**Comment by jimmynotjim** [comment]
Closing as we're moving CMS
