### ISSUE TITLE
Technology and Innovation Fellowship page is off...

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#2546]
I sent the T&I fellowship page to a @antislice and all the JS, CSS, and images are broken. :(

## Current behavior

![image](https://cloud.githubusercontent.com/assets/1860176/20458736/94c947f8-ae61-11e6-94d7-861ac20f97f7.png)

## Expected behavior

- It should look something like this. http://web.archive.org/web/20160308233312/http://www.consumerfinance.gov/jobs/technology-innovation-fellows/

## Steps to replicate behavior

1. Visit http://www.consumerfinance.gov/jobs/technology-innovation-fellows/

**Comment by chosak** [comment]
This was fixed in #2547 and is now fixed on [the live site](http://www.consumerfinance.gov/jobs/technology-innovation-fellows/). Thank you for reporting this @KimberlyMunoz!
