### ISSUE TITLE
Odd filter behavior when only one date is chosen

### ISSUE THREAD

**Issue by dpford** [cfpb/cfgov-refresh#261]
When using the filter on pages such as /blog/ and /newsroom/, if only a single date is filled out, after submission that entered date will switch to the other date field (To -> From or visa versa).

To reproduce: on /newsroom/, enter a To: month and year, but enter nothing for From.  Hit submit.  Now look at the filter.   The month and year you selected will be in the From section.

I believe this has to do with some clever behavior that swaps the From and To dates if the To date is earlier than the From date.

**Comment by himedlooff** [comment]
Yeah, I wonder if this is because the JS checks which date is greater and swaps them so that `from` is the earlier date and `to` is the later date. If one is missing maybe it's getting counted as the earlier date.

**Comment by anselmbradford** [comment]
Mike!
