### ISSUE TITLE
Leadership calendar page missing breadcrumb

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2634]
## Current behavior

- http://www.consumerfinance.gov/about-us/the-bureau/leadership-calendar/ is missing the `The Bureau` breadcrumb that other pages in that section have.

## Expected behavior

- All pages within the bureau section should have a breadcrumb link back to the main about the bureau page above the navigation.

**Comment by chosak** [comment]
The breadcrumb is missing because this page's parent (The Bureau) is not in Wagtail yet. In order for breadcrumbs to render properly, pages need their full ancestry to be served by Wagtail.

**Comment by anselmbradford** [comment]
@chosak All other pages in that section have the breadcrumb, can't the leadership calendar use the same code those pages use? Or not worth the effort as it'll all be in wagtail eventually?

**Comment by sebworks** [comment]
@anselmbradford, all the other pages are legacy pages. I've created a hack to fix the issue but it won't scale well. We need a more robust solution to handle cases where some of the pages aren't in Wagtail.

**Comment by sebworks** [comment]
The leadership calendar now has a breadcrumb, so I'm closing this.
