### ISSUE TITLE
Event filter multiselect is broken

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2636]
## Current behavior

- Events filter Topic filter appears to be broken with unclickable options when there are no upcoming events. 

## Expected behavior

- Expects topic filter to be multi-select with clickable options.

## Steps to replicate behavior

1. Visit http://www.consumerfinance.gov/about-us/events/
2. Click show filter.
3. Note Topic multi-select options are showing and are unclickable.

## Screenshots

![screen shot 2016-12-30 at 4 42 20 pm](https://cloud.githubusercontent.com/assets/704760/21573169/580f6130-ceaf-11e6-8a45-dff9ae3eed12.png)

**Comment by sebworks** [comment]
Looks like this is happening because there are no upcoming events. We should discuss if it's just worth hiding the filter.

**Comment by anselmbradford** [comment]
Yeah we should hide the filter when there are no events. This is currently (11/3) broken on the live site https://www.consumerfinance.gov/about-us/events/

@chosak This an easy fix?

**Comment by schbetsy** [comment]
PR: https://github.com/cfpb/cfgov-refresh/pull/4758
