### ISSUE TITLE
`breadcrumb__sidebar-first` class appears to be unused

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2639]
## Current behavior

- https://github.com/cfpb/cfgov-refresh/blob/83c1281bd92868437c5a8b611d686f020d53f2dc/cfgov/jinja2/v1/_layouts/content-base-sidebar-first.html#L17 does not appear to be used.

## Expected behavior

- Unused classes should be removed.

## Steps to replicate behavior

1. Visit http://www.consumerfinance.gov/about-us/the-bureau/about-director/
2. Inspect the breadcrumb and note no styling applied by `breadcrumb__sidebar-first`

**Comment by Scotchester** [comment]
For additional confirmation, the string `sidebar-first` does not appear anywhere in our `cfgov/unprocessed/css` folder anymore.

There's also [these](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_layouts/content-base-main-first.html#L10) [instances](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_layouts/content-base-main-first.html#L17) in `content-base-main-first.html` that also appear obsolete.
