### ISSUE TITLE
Remove demo.less

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#2642]
This project hasn't had a demo version for some time, pretty sure this file can be removed to tidy things up. https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/css/demo.less

**Comment by anselmbradford** [comment]
Also https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/css/main.less#L172
