### ISSUE TITLE
The Bureau styles defined but not included

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2644]
## Current behavior

- [This template](https://github.com/cfpb/cfgov-refresh/blob/4f3e8b308c630038b02920c2c5104c6ba6f607d3/cfgov/jinja2/v1/about-us/the-bureau/index.html#L106) uses `bureau-functions`, which is defined in [bureau.less](https://github.com/cfpb/cfgov-refresh/blob/4f3e8b308c630038b02920c2c5104c6ba6f607d3/cfgov/unprocessed/css/pages/bureau.less). However, that less file is not included in https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/css/main.less#L161-L166, so those classes are not applied.

## Expected behavior

Either:
- `bureau.less` and the associated classes should be removed.
- `bureau.less` should be included in `main.less`.
- `bureau.less` should be refactored to use atomic styles instead of the bespoke ones it defines.

**Comment by sebworks** [comment]
yep, must have got deleted when I did the jQuery stuff. I'll add it back.
