### ISSUE TITLE
Stop nuking node_modules

### ISSUE THREAD

**Issue by contolini** [cfpb/cfgov-refresh#2654]
Our build script deletes the [project's node_modules directory](https://github.com/cfpb/cfgov-refresh/blob/master/frontend.sh#L29) before re-installing everything:

```sh
# Clean project dependencies.
clean() {
  # If the node directory already exists,
  # clear it so we know we're working with a clean
  # slate of the dependencies listed in package.json.
  if [ -d $NODE_DIR ]; then
    echo 'Removing project dependency directories...'
    rm -rf $NODE_DIR
  fi
  echo 'Project dependencies have been removed.'
}
```

This is good for idempotence but bad for efficiency.

```sh
$ time npm install

real	0m23.881s
user	0m23.155s
sys	0m1.486s

$ rm -rf node_modules/
$ time npm install

real	2m32.014s
user	1m39.444s
sys	0m38.497s
```

It doesn't affect local development a whole lot but it adds minutes to our CI jobs and slows down deployments. How would y'all feel about removing it from our build script?

@cfpb/cfgov-frontends @chosak

**Comment by marcesher** [comment]
💯

**Comment by Scotchester** [comment]
I'm certain that we started doing this intentionally. I don't fully remember why, but are we sure that whatever reason we did it isn't still in play?

**Comment by chosak** [comment]
I like the idea of removing the deletion by default. Would it be possible to add either a command-line parameter to `frontend.sh` (and, I suppose, then `setup.sh`) or an environment variable to retain the option to remove that directory? I'm thinking it might be useful to support a cleaning option in the build scripts, and this would avoid having to refer to `$NODE_DIR` outside of this script.

**Comment by contolini** [comment]
> I'm certain that we started doing this intentionally. I don't fully remember why, but are we sure that whatever reason we did it isn't still in play?

I think it was added to reduce JS compilation errors by ensuring we always have fresh copies of the project's node modules. I would rather manually wipe `node_modules` when I run into errors than do it on every install.

> Would it be possible to add either a command-line parameter to frontend.sh (and, I suppose, then setup.sh) or an environment variable to retain the option to remove that directory?

I'm into this. Something like `./setup.sh --clean`.

**Comment by sebworks** [comment]
> I'm into this. Something like ./setup.sh --clean.

👍

**Comment by Scotchester** [comment]
I think that is a good compromise. One thing we should be sure to watch out for is running that proactively when we remove a dependency.

**Comment by jimmynotjim** [comment]
We only need to nuke the modules directory when https://github.com/cfpb/cfgov-refresh/blob/master/npm-shrinkwrap.json updates right? Is there some way we could notify folks when they pull down the latest that it's been updated? It's not something I'd think to check very often since it's been kind of automatic so far.

**Comment by anselmbradford** [comment]
Was this resolved?

**Comment by jimmynotjim** [comment]
After running into some issues with the CF docs branch, it seems you really do sometimes need to nuke a module in order to convince npm to update it. Even after changing the version in `package.json` I could not get it to update till I deleted the package from the project.

**Comment by contolini** [comment]
> After running into some issues with the CF docs branch, it seems you really do sometimes need to nuke a module in order to convince npm to update it. Even after changing the version in package.json I could not get it to update till I deleted the package from the project.

K then I think we're good here -- the `node_modules` dir [sometimes](https://github.com/cfpb/cfgov-refresh/blob/master/frontend.sh#L99-L109) gets cleaned and other times doesn't based on flags passed at build time.
