### ISSUE TITLE
Is there any reason description and website aren't filled out?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#266]
... on the main repo page? Otherwise I'll add something.

![screen shot 2015-02-20 at 2 48 14 pm](https://cloud.githubusercontent.com/assets/704760/6308141/923735fc-b90f-11e4-9a58-f041b5356961.png)

**Comment by Scotchester** [comment]
No reason. Probably no need for a website, though.

**Comment by anselmbradford** [comment]
Added `In-progress redesign of the consumerfinance.gov website.`
