### ISSUE TITLE
Post entry footer needs a clearfix

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#271]
Some blog posts and all event posts have a floating sidebar inside the `post_body` content. If this sidebar is taller than the body copy, the sidebar floats to the right of the tags, which are in the post's `<footer>`. This element should have a clearfix applied, e.g. `clear: both;`.

Screenshot:
![screen shot 2015-02-23 at 3 18 23 pm](https://cloud.githubusercontent.com/assets/704760/6336253/399a9b2a-bb6f-11e4-8ad3-d38a74a72d46.png)

**Comment by sebworks** [comment]
:+1:

**Comment by anselmbradford** [comment]
Fixed in https://github.com/cfpb/cfgov-refresh/pull/272
