### ISSUE TITLE
Get in touch with the Wagtail core team

### ISSUE THREAD

**Issue by tomdyson** [cfpb/cfgov-refresh#2731]
This is a fantastic project. As a member of the Wagtail core team I've learned a lot from reading your PRs. We're also very interested in your `wagtail-sharing` and `wagtail-flags` apps. We'd love you to make contact so we can learn from each other.

## Current behavior

The CFPB team isn't in touch with the Wagtail core team.

## Expected behavior

The CFPB team should be in touch with the Wagtail core team.

## Steps to address the issue

1. Email hello@wagtail.io to set up a Hangout.

**Comment by anselmbradford** [comment]
@hillaryj @amymok and @anselmbradford will be at Djangocon!

**Comment by hillaryj** [comment]
Here are the repos mentioned and a [guide on how to use feature flags](https://cfpb.github.io/cfgov-refresh/feature-flags/):

[`wagtail-flags`](https://github.com/cfpb/wagtail-flags)
[`wagtail-sharing`](https://github.com/cfpb/wagtail-sharing)
