### ISSUE TITLE
Avoid sectioning content in macros?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#276]
https://github.com/cfpb/cfgov-refresh/blob/gh-pages/_includes/macros.html#L84 defines a share aside section that is included with, e.g. https://github.com/cfpb/cfgov-refresh/blob/gh-pages/_includes/article.html#L62-L66

However, since this adds an `aside` this macro can't be used in composition with other sections easily. For example, additional content couldn't be added to the share aside without editing the macro (which for page-specific adjustments, may not be desired). We may want to consider making the `aside` a `div` and leaving sectioning to the implementation location, like:

```
<aside>
        {{ share(post.title, false, {
           'text':     post.twtr_text,
           'related':  post.twtr_rel,
           'language': post.twtr_lang,
           'hashtags': post.twtr_hash
        }) }}
</aside>
```

**Comment by Scotchester** [comment]
I love that you all are giving the attention to the document outline that I always wanted to give :heart_eyes_cat:

**Comment by himedlooff** [comment]
> However, since this adds an aside this macro can't be used in composition with other sections easily.

Can you clarify?

**Comment by anselmbradford** [comment]
> Can you clarify?

An example might be best. Okay, (this is theoretical), say you have a post that has tangential content you want next to the main post content. Say it's a footnote and the share buttons, so looks like:

```
<aside>
    <p class="footnote">
        Blah blah blah a footnote.
    </p>
    {{ share(post.title, true, {
        'text':     post.twtr_text,
        'related':  post.twtr_rel,
        'language': post.twtr_lang,
        'hashtags': post.twtr_hash
    }) }}
</aside>
```

The generated content for this would look like:

```
<aside>
    <p class="footnote">
        Blah blah blah a footnote.
    </p>
    <aside>
       <h1>Share this page</h1>
       ...
    </aside>
</aside>
```

The document outline for this would be:

```
UNNAMED aside
    "Share this page" aside
```

So say you don't want to show the sharing heading content, so the macro is run as `{{ share(post.title, false, {`, the outline now looks like:

```
UNNAMED aside
    UNNAMED aside
```

Kind of redundant, right? Also is the inside `aside` tangential to the content in the outside aside or tangential to a larger container section on the page (presumably an `article`)? In this implementation if the sharing buttons are included in their own section (which I think makes sense), they should probably be a `section` not an `aside`, however this isn't possible with the `aside` in the macro. 

I think ideally, if https://github.com/cfpb/cfgov-refresh/issues/275 if addressed, the share icons would have a heading that could be shown/hidden, not included/excluded, so something like the following could be constructed:

```
<aside>
    <h1 class="u-visually-hidden">Post notes and tools</h1>
    <p class="footnote">
        Blah blah blah a footnote.
    </p>
    <section>
        {{ share(post.title, true, {
            'text':     post.twtr_text,
            'related':  post.twtr_rel,
            'language': post.twtr_lang,
            'hashtags': post.twtr_hash
        }) }}
    </section>
</aside>
```

Which would generate the HTML:

```
<aside>
    <h1 class="u-visually-hidden">Post notes and tools</h1>
    <p class="footnote">
        Blah blah blah a footnote.
    </p>
    <section>
       <div>
          <h1 class="u-visually-hidden">Share this page</h1>
          ...
       </div>
    </aside>
</aside>
```

Which would have the outline:

```
"Post notes and tools" (aside)
   "Share this page" (section)
```

Optionally, to remove the pointless `div`, the parent container could be omitted from the macro, **or the parent container element could be passed in as an argument to the macro** (this would be best I think, but I'm not sure how to do this with jinja).

I'm not saying we have to be so precise with everything having a named heading like this, but I think the macro should allow a construction like that, if desired.

**Comment by himedlooff** [comment]
The initial thought I had when using sectioning elements in these macros was that we could recommend the appropriate element based on the content. Share links seem like they will always be aside-worthy. Other macros might not be so obvious, admittedly. As far as the outline goes though, have you considered a generic wrapper there, like a div? What if legit content needs to go in there too? If the wrapper were generic you could do it like this:

```
div // a wrapper for the aside-like stuf
  aside // share stuff
  section // legit content
  aside // junk
```

Just food for thought. Like I said, there is an admitted flaw in assuming we can really know the appropriate sectioning element for every macro, so it seems sound to leave them out or build in some customization.

**Comment by himedlooff** [comment]
Ran a quick test and this works:

```html
{% macro test(el='aside') %}
    <{{el}}>test</{{el}}>
{% endmacro %}

{{ test('p') }} // outputs <p>test</p>
{{ test('h1') }} // outputs <h1>test</h1>
```

**Comment by anselmbradford** [comment]
> Ran a quick test and this works:

@himedlooff Thanks for looking into this! I like your approach here because it's self-documenting what container element the macro is creating at the place the macro is invoked... but you can leave it off and go with the default too if that's preferable
