### ISSUE TITLE
Fix Sourcemaps

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#282]
Sourcemaps are broken/non-existent causing difficulty when tracking down style rules.

**Comment by anselmbradford** [comment]
What are the steps to fix this issue? I'm not so familiar with creating sourcemaps.

**Comment by sebworks** [comment]
@anselmbradford, the source maps are normally created via uglify in the Gruntfile.js file.

**Comment by jimmynotjim** [comment]
Sourcemaps are set by grunt-contrib-less. I was able to turn them on but it seems the grunt-contrib-cssmin plugin is having issues. Will report back when I figure it out.

**Comment by jimmynotjim** [comment]
Turns out you can't run sourcemaps in both the less and cssmin tasks. Who knew ¯\_(ツ)_/¯

Now the issue is Chrome isn't finding the sourcemap, even though I can see it in the source tab

![screen shot 2015-02-25 at 5 48 21 pm](https://cloud.githubusercontent.com/assets/1280430/6382435/84bb40de-bd16-11e4-9963-1a719ec82949.png)

Any thoughts?

**Comment by jimmynotjim** [comment]
Finally got this figured out. First, if you turn on auto-reload in chrome settings without all the other steps that are required, it seems to stop reading the source maps.

Next, we do need to generate source maps in the less task, otherwise the mappings to the less files aren't generated. Unfortunately cssmin strips the less generated source maps, and if you turn source maps on in cssmin, it replaces them with it's own.

Then I thought we could use the Less plugin's built in `cleancss` option, but it turns out this option strips the source maps as well. It looks like there's no possible way to minify *and* have source maps.

My question now is, do we have a reason to use minified sources locally? In my previous job we added a dev flag to our tasks that skipped the min tasks for both css and js. We were also able to conditionally set the asset urls based on the local environment. The second part might be a bit more difficult here, but I think it's worth trying to get source maps working and avoid having to CMD+SHIFT+F to find everything.

If no one objects, I'll make an attempt at this tomorrow.

**Comment by anselmbradford** [comment]
> My question now is, do we have a reason to use minified sources locally? In my previous job we added a dev flag to our tasks that skipped the min tasks for both css and js. We were also able to conditionally set the asset urls based on the local environment. The second part might be a bit more difficult here, but I think it's worth trying to get source maps working and avoid having to CMD+SHIFT+F to find everything.

Ideally we wouldn't be minifying till right before pushing to a staging server. Having the minified assets on every branch during development means any change to the CSS/JS will **always** have a conflict with upstream.

**Comment by jimmynotjim** [comment]
Agreed. I've never been a fan of minified sources in git history for that exact reason. Hopefully we can work with the delivery team to create a better deployment process that takes care of the minification (something I hadn't quite solved in my last job).

**Comment by Scotchester** [comment]
/cc @dpford 

We discussed the idea a while back of running the default Grunt tasks on the demo servers, which would enable us to take the minified stuff out of the repo. I believe this is something Jenkins can do for us. Dan, can we get that on the backlog? I don't think it ever officially made it there.

**Comment by jimmynotjim** [comment]
The only thing we have to watch when doing this is file name matching. Right now we use `.min` in the file name and swapping that back and forth is a pain if you don't have environment variables to automate it. If we do end up with a deployment script minifying, `.min` should be ommited since it doesn't make sense in local/dev environments.

**Comment by dpford** [comment]
Sounds like a perfectly cromulent idea.  Added it to backlog.
