### ISSUE TITLE
Include grunt sub-tasks in readme

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#283]
Grunt watch is running every task on changes (taking nearly 30-40 sec) rather than limiting itself to just concatenating changed file type. We could either reduce it to running just what's needed for local dev (requiring running the full grunt task before committing) or create a lighter version of watch for this purpose. Most projects limit watch to locally needed tasks, but I'm afraid to change existing workflows without team agreement.

**Comment by Scotchester** [comment]
There are `css` and `cssjs` targets that only run tasks necessary for local dev.

**Comment by jimmynotjim** [comment]
Ah, sorry, I hadn't dug into the gruntfile, was just jotting down thoughts. Changing this to include these sub-tasks in the readme for easier discovery.

**Comment by jimmynotjim** [comment]
Closed by #287
