### ISSUE TITLE
Clarification on IE7 support

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2844]
## Current behavior

- In https://github.com/cfpb/cfgov-refresh/blob/cb923f0834c49864e65735767fbd91aed613263f/gulp/tasks/styles.js#L70-L93 IE7 and 8 are mentioned. Autoprefixer is set up for IE7 and 8 compatibility while gulpCleanCss is set for only IE8 compatibility later in the same task. Checking if IE7 should be completely dropped from this task?

## Expected behavior

- stylesIE8 task should completely support IE7 or not at all.

**Comment by sebworks** [comment]
I don't feel like we should support IE7 based on the analytics and testing constraints.

**Comment by anselmbradford** [comment]
Sounds good to me 👍

**Comment by sebworks** [comment]
Fixed in https://github.com/cfpb/cfgov-refresh/pull/2976
