### ISSUE TITLE
Submit a complaint on /complaint should go to /complaint/getting-started

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2884]
## Current behavior

- When on `/complaint` "Submit a Complaint" link is prominent on the upper-right, but the "Start a complaint" button may be scrolled out of view. This could lead a user clicking "Submit a Complaint" in the upper-right and expect to be taken to `/complaint/getting-started` (as the button further down on the page does). However, that link goes to the same page the user is on, so it appears the link is not working.

## Expected behavior

- Perhaps change "Submit a Complaint" link to point to `/complaint/getting-started` OR remove the link on /complaint OR disable the "Submit a Complaint" link in the upper-right when on `/complaint`.

## Steps to replicate behavior

1. Visit https://www.consumerfinance.gov/complaint/ and click "Submit a Complaint" in the upper-right.

## Screenshots
<img width="1327" alt="screen shot 2017-05-01 at 12 29 58 pm" src="https://cloud.githubusercontent.com/assets/704760/25586250/7d48f354-2e6c-11e7-8174-dd55ec2012b7.png">

**Comment by Scotchester** [comment]
OR have it go to `/complaint/getting-started` IF you're already on `/complaint`?

**Comment by Scotchester** [comment]
And then there's the question of what to do with that link when on https://www.consumerfinance.gov/complaint/getting-started/ :)

**Comment by anselmbradford** [comment]
@schaferjh How do you think this should work?

**Comment by schaferjh** [comment]
This is a great detailed observation but we have not recieved any indication that it's an issue or blocker and I would prefer not to create a unique behavior here given that the link in question is part of the global header. I think this issue can be closed.
