### ISSUE TITLE
Remove Ustream code and most of the Video Player code

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#2918]
We no longer use the Ustream player and rely upon Youtube for live streams and archive playback.  Much of the video player JS code was built upon the premise of using multiple video player APIs. That is no longer the case, so the code should removed.

**Comment by jimmynotjim** [comment]
🍌 💃 (Github needs the real banana dance emoji)

**Comment by sebworks** [comment]
This has been done.
