### ISSUE TITLE
Your Money, Your Goals menu broken in IE

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2979]
## Current behavior

Error (1):
- Visit /educational-resources/your-money-your-goals/ in IE9
- Click on a mega menu item, such as Data & Research
- See error in console `SCRIPT5007: Unable to get value of property 'getDom': object is null or undefined`

Error (2):
- Visit /educational-resources/your-money-your-goals/ in IE10
- Click on a mega menu item, such as Data & Research
- See error in console `Invalid character`

<img width="976" alt="screen shot 2017-06-02 at 3 25 55 pm" src="https://cloud.githubusercontent.com/assets/704760/26741572/e59727f6-47a7-11e7-8084-648c0199290c.png">

## Expected behavior

- No errors in IE and user should be able to navigate menu.

**Comment by Scotchester** [comment]
Can't reproduce in IE9. Still need to get an IE10 VM downloaded after business hours when I'm off the VPN.

**Comment by anselmbradford** [comment]
> Can't reproduce in IE9. Still need to get an IE10 VM downloaded after business hours when I'm off the VPN.

Looked again, are you clicking the Data & Research heading? Once you do that the menu will not expand anymore:

![glitchy](https://cloud.githubusercontent.com/assets/704760/26790206/e8eccf92-49e0-11e7-9136-ed519b7d59db.gif)

Probably my authored bug 👅

**Comment by Scotchester** [comment]
Hmmm, OK, I'll take another look. I think I missed the instruction to click.

**Comment by jimmynotjim** [comment]
Confirmed this behavior. Not so sure on a fix.

**Comment by anselmbradford** [comment]
Just saw this bug in Chrome on OS X but can't replicate.

**Comment by anselmbradford** [comment]
Likely this error in New Relic
![screen shot 2018-04-10 at 12 34 20 pm](https://user-images.githubusercontent.com/704760/38570305-86e76c5c-3cbb-11e8-9634-24c3fdecb9d3.png)

**Comment by anselmbradford** [comment]
With the new menu release I'm not able to reproduce this and I don't see the `getDom` error in new relic any more.
