### ISSUE TITLE
CSS cleanup in event

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#299]
- [x] Investigate whether !important is needed https://github.com/cfpb/cfgov-refresh/pull/288#discussion-diff-25465198R102
- [x] Use numerical weights for `font-weight` or create Less variable https://github.com/cfpb/cfgov-refresh/pull/288#discussion_r25465685
- [x] Investigate adding a modifying instead of resetting `content` attribute in `event-meta_address` https://github.com/cfpb/cfgov-refresh/pull/288#discussion_r25465744 and https://github.com/cfpb/cfgov-refresh/pull/288#discussion_r25465765

**Comment by jimmynotjim** [comment]
On number two, I think we should revisit these font mixins. Many times the weight is the only change needed, but we're using the mixin because of the way the weights were originally declared in the mixins.

**Comment by Scotchester** [comment]
We should have a scheduled chat about the webfonts. It's verrrrrry complicated. I did a lot of research into it.

**Comment by jimmynotjim** [comment]
@Scotchester I actually have a pretty free day tomorrow after lunch time

**Comment by Scotchester** [comment]
@jimmynotjim I could meet anytime after 11:30 except 2–3 and 4–5.

**Comment by Scotchester** [comment]
Correction: after noon.

**Comment by sebworks** [comment]
@jimmynotjim @anselmbradford  did we come to a final decision on the font weights? I like this format https://gist.github.com/fat/1f6da6b3bd0311a1f8a0

**Comment by anselmbradford** [comment]
@sebworks I was going to look into it today or Monday when doing browser testing (DF-1537), see DF-1565. Is that the right gist you meant to link to? It's z-indices? Cool reference, regardless!

**Comment by sebworks** [comment]
@anselmbradford, Yes it's correct. I just like the format but we would implement it for font-weight. This is the complete article https://medium.com/@fat/mediums-css-is-actually-pretty-fucking-good-b8e2a6c78b06.

**Comment by jimmynotjim** [comment]
We can't use font-weight alone until we determine a single font-family is stable on BB. I'd say use the mixin for now and revisit this after Ans has finished testing in Sprint 23
