### ISSUE TITLE
--a11y flag broken

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#2996]
## Current behavior

- https://github.com/cfpb/cfgov-refresh/blob/master/docs/testing.md says `gulp test:acceptance --a11y` is a command. 
- `gulp test:acceptance --a11y` runs tox at https://github.com/cfpb/cfgov-refresh/blob/master/gulp/tasks/test.js#L60, but only looks for `--specs` flag.
- tox runs `gulp test:acceptance:protractor` at https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/cfgov/test.py#L130
- **No arguments except --specs flag are passed to gulp command in test.py** so `--a11y` flag is ignored.

## Expected behavior

- Calling  `gulp test:acceptance --a11y`, should pass `a11y` (and any other flag) to tox to then pass on back to gulp. 

## Steps to replicate behavior

1. Run `gulp test:acceptance --a11y`, see that no accessibility testing is done.

**Comment by sebworks** [comment]
even if you pass the flag, how did this work before?

**Comment by anselmbradford** [comment]
`gulp test:acceptance:protractor --a11y`, works, but `gulp test:acceptance` calls that task, but strips the flag, so it could be just that the documentation is wrong, but it seems like it should pass through any flags in `gulp test:acceptance` back to gulp, not just `--spec`.

**Comment by sebworks** [comment]
yep, I see it now. Fixed in #2997.
