### ISSUE TITLE
Change gh-pages to master

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#301]
There's no longer a need for `gh-pages` and it's a bit misleading to anyone that comes across the project. We should consider changing the main branch to `master`

Reported by @himedlooff

**Comment by anselmbradford** [comment]
Is this just a matter of creating a `master` branch from `gh-pages` and deleting `gh-pages`? I've only ever worked in a repo that has a `master` AND `gh-pages` branch. Would be good to knock this issue out today if we can.

**Comment by jimmynotjim** [comment]
I don't believe so, because deployment should depend on the branch name. @dpford can you clarify this one?

**Comment by Scotchester** [comment]
If it's not too much work, I'd recommend maintaining gh-pages for ease of viewing the docs without starting up the local dev environment.

**Comment by dpford** [comment]
We would need to change the branch used in a few Jenkins jobs, plus a fabric script we have.

**Comment by jimmynotjim** [comment]
@Scotchester the local docs are semi-reliant on the branch name as well?

**Comment by Scotchester** [comment]
No, I mean it's occasionally nice to just go to (or point people to) http://cfpb.github.io/cfgov-refresh/docs/misc/

**Comment by jimmynotjim** [comment]
After the call yesterday we came up with a Git workflow that allows us to match branches to deployments:

continuous: feature ----> flapjack (unstable)
*by-weekly monday: flapjack ----> refresh (stable) --tagged minor
continuous: bugfix ----> refresh (stable) --tagged patch
internal approval: refresh ----> beta (beta)
legal/agency approval: beta ----> master (production)
alongside beta approval: beta ----> gh-pages (docs)

I've opened a Jira task for the BEWDs to update the Jenkins job in the next sprint to match.

*bi-weekly being the day before sprint review (Mon), so that at sprint review (Tue afternoon), all work is stable and viewable by the team on refresh

**This flow also makes setting up releases for the changelog a lot easier to create, which means we're more likely to use them (see https://github.com/cfpb/cfgov-refresh/issues/312#issuecomment-76472324)

**Comment by jimmynotjim** [comment]
We've started using the above branching model, and the deliver should be updated in the next sprint
