### ISSUE TITLE
Gruntfile.js is behind CF Generator

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#302]
The `Gruntfile.js` is an older version of that found in the CF Generator. It should be updated to include the latest changes.

Reported by @himedlooff

**Comment by jimmynotjim** [comment]
I have an open PR that updates the Generator to work with existing projects. I'm currently working on a second update that will allow users to pick the installation location. Once these are tested and ready it should make these CF core updates easier.

**Comment by jimmynotjim** [comment]
That PR is closed, @anselmbradford is now working on fixing this

**Comment by anselmbradford** [comment]
Incrementally being fixed in https://github.com/cfpb/cfgov-refresh/pull/545, https://github.com/cfpb/cfgov-refresh/pull/542, https://github.com/cfpb/cfgov-refresh/pull/541, and more to come.
