### ISSUE TITLE
Grid boxsizing polyfill error

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#303]
There is an error in `main.less`: `@grid_box-sizing-polyfill-path: "/cfgov-refresh/static/vendor/box-sizing-polyfill";` should be `@grid_box-sizing-polyfill-path: "/static/vendor/box-sizing-polyfill";`

Reported by @himedlooff

**Comment by jimmynotjim** [comment]
@anselmbradford did this get fixed with #499 changes?

**Comment by anselmbradford** [comment]
Appears to have been fixed in https://github.com/cfpb/cfgov-refresh/commit/99252f0d60c3d57b963f94e4e941d5bbbb762245#diff-087eea46a52d1a7e1e93f584045979f4R136
