### ISSUE TITLE
Generate and conditionally load additional assets

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#304]
Currently, all assets are compiled to one file for each type: `main.css` and `main.js`. Sectioning off unnecessary assets and conditionally loading them only when needed will reduce file size and page load.

**Comment by jimmynotjim** [comment]
@anselmbradford has started this with browserify in #499, but at the moment everything is still being compiled to one stylesheet.

**Comment by anselmbradford** [comment]
Related to https://github.com/cfpb/cfgov-refresh/issues/253

**Comment by KimberlyMunoz** [comment]
Talked with Ans and since JS conditional asset loading is in and the CSS stuff has its own issue in #253, it's okay to close this issue.
