### ISSUE TITLE
Make floating images flexible or stop floating at small screens

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#306]
Currently floating images within content are causing poor layout reflows.

Ex. 

- /blog/four-steps-you-can-take-if-you-think-your-credit-or-debit-card-data-was-hacked

![screen shot 2015-02-27 at 2 54 58 pm](https://cloud.githubusercontent.com/assets/1280430/6420032/a2bae474-be90-11e4-9bb7-454f88a4a701.png)

**Comment by jimmynotjim** [comment]
Stylesheet should include default WP alignment classes as well.

```
.alignleft
. aligntright
.aligncenter
.alignnone
```

**Comment by KimberlyMunoz** [comment]
DFJR-1204 is the JIRA issue for this one. It should be tackled as part of how we handle responsive image handling.
