### ISSUE TITLE
Fix post tables

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#308]
Some posts have tables in the content that could use some design love

Ex.
- /blog/student-banking-101
- /blog/explainer-why-did-it-take-1099-pages-to-propose-a-three-page-mortgage-disclosure

**Comment by Scotchester** [comment]
One comment about this and its sister issues: Don't spend too much time on stuff if it's only in older posts (I think defined as older than 1 year? @jameshupp?). But there might be this sort of thing in newer posts or things that are really popular and we do want to fix them up.

I think existing tables almost all have this `class="alj"`. One possible approach could be to create a temporary `.alj` block of CSS that overrides a lot of the weird things you see that we can cast off once that stuff hasn't been used for a long time. Might need to use `!important` in a few places to override some inline styles.

That is, unless someone wants to actually traipse through all our posts and fix all of this markup in WordPress :)

**Comment by jimmynotjim** [comment]
Got it. These all came from a todo.md so I just tried to capture them best I could. Sounds like we'll have to use some discretion when taking them on.

**Comment by Scotchester** [comment]
:+1:

**Comment by KimberlyMunoz** [comment]
I can't assign anything to myself, but I'm going to grab this issue.

**Comment by jimmynotjim** [comment]
Try it again Kim, just added you as a collaborator.

**Comment by KimberlyMunoz** [comment]
I edited these and a few other "Explainer" articles to remove any wonky tables and use the new simple-table in the CMS. Since those classes don't do anything in the old CMS, they should be fine and this avoids any nasty !important hacks.

**Comment by jimmynotjim** [comment]
Once @jameshupp ramps the content you can run `sheer index --reindex` to double check everything made it over. Then @dpford will need to reindex each of the staging environments as well.

**Comment by KimberlyMunoz** [comment]
Since it's such a process, I'll grab the related issues, #309 and #307, today as well. It's probably easier to check them all at once.

**Comment by KimberlyMunoz** [comment]
I'm waiting for things to grab the newest posts from WordPress. I also added data-labels where appropriate to keep the tables responsive on mobile.

- /blog/student-banking-101/
- /blog/scoring-student-loan-servicers/
- /blog/explainer-how-the-final-tila-respa-rule-differs-from-the-proposal/

**Comment by KimberlyMunoz** [comment]
Changes are in and look good. Closing this issue.

![image](https://cloud.githubusercontent.com/assets/1860176/7306185/579841b4-e9d1-11e4-94d9-4d7bef13a7c3.png)
