### ISSUE TITLE
Fix post insets

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#309]
Some posts have insets that could use some design love.

Ex. 

- /blog/exemption-from-escrow-requirement-for-small-creditors-in-rural-or-underserved-counties
- /blog/you-have-a-right-to-see-specialty-consumer-reports-too

**Comment by KimberlyMunoz** [comment]
As @juidai recommended, I'm just ripping out the inline styles here and replacing them with the new `.post_inset__right` styles. I'm going to keep the custom `.note` class they have there so this doesn't look terrible on production.

**Comment by KimberlyMunoz** [comment]
This one is done and waiting to reindex the changes. The last two posts didn't show up for ramping, so I'd want to make sure those changes are actually there. Here's the posts that are affected.

- /blog/final-list-of-rural-and-or-underserved-counties-for-use-in-2013/
- /blog/exemption-from-escrow-requirement-for-small-creditors-in-rural-or-underserved-counties/
- /blog/plan-your-spending-to-avoid-holiday-debt/
- /blog/a-final-rule-that-makes-mortgage-disclosure-better-for-consumers/
- /blog/so-how-many-consumer-reporting-companies-are-there/
- /blog/final-list-of-rural-and-underserved-counties-for-use-in-2014/
- /blog/final-list-of-rural-or-underserved-counties-for-use-in-2015/

**Comment by KimberlyMunoz** [comment]
Looks like all the changes are there. Closing this issue.
