### ISSUE TITLE
Migrating JS Atomic Components to Preact

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#3103]
[Preact](https://github.com/developit/preact) is the perfect library for what we want to accomplish. It has a great API, documentation, and community support. It's also just 3kb. I'm going to be migrating https://github.com/cfpb/AtomicComponent to use Preact. The CF4 components will need to be migrated as well. 

## Notes

- I do have some concerns surrounding event delegation but those are far outweighed by the benefits of using Preact.

**Comment by cfarm** [comment]
> Preact supports modern browsers and IE9+:

We are baking in the loss of support for IE8 JS further with this. I would like to know more about how that decision was made and why, since it impacts many key applications on cf.gov.

**Comment by sebworks** [comment]
@cfarm, we don't support IE8 with JS. We haven't in a very long time.

**Comment by cfarm** [comment]
Yes, I realize that. It's something I only just learned at the last regroup, though. So I would like more insight into when and how that came to be - it wasn't something I was aware of before I joined platform team, nor were my teammates aware of it. Is there documentation on when and why the support was dropped?

**Comment by sebworks** [comment]
It has always been the policy that once the browser support reached a certain level that we dropped support for it. The flapjack team just made the determination to drop JS support based on the level of users and MS dropping security updates for the browser.

**Comment by jimmynotjim** [comment]
@cfarm that's on us for not making sure it was outside the original team and for not documenting it for the future. Do you think we should document it here or in the Development repo? I can take a stab at documenting it tomorrow, though the _when_ details are a bit foggy at this point.

**Comment by cfarm** [comment]
@jimmynotjim yeah I was just chatting with @sebworks about this. Development repo seems like the place for it - specifically: 

- adding a note to the IE8 bullet that JS is not supported https://github.com/cfpb/development/blob/master/browser-checklist.md
- and maybe https://github.com/cfpb/development/blob/master/javascript.md

&lt;/derail&gt; continue thread topic as originally planned :bowing_woman:

**Comment by wpears** [comment]
@sebworks let's chat about preact next week, I like it and have used it, but this seems like a fairly big decision we should probably hash out a bit more amongst the group

**Comment by ascott1** [comment]
Just came across this issue and I want to echo @wpears's comment. This is a decision that should be made at the team level. Preact is certainly interesting technology, but this would incur some new technical debt that should be considered. Hold off on implementing until this has been discussed more widely.

**Comment by sebworks** [comment]
Discussion was helpful, yet unsure on future direction.
