### ISSUE TITLE
Update `WORDPRESS` constant

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#311]
The variable WORDPRESS is misleading because it points to a server that is part WP and part Django. Maybe a task to take on is to split this variable into two:

```
export SITEURL=[demo url]
export WORDPRESS=${SITEURL}/api/
```

**Comment by jimmynotjim** [comment]
Pretty sure this is going away, right @rosskarchner?

**Comment by rosskarchner** [comment]
Yeah-- I don't think it's worth investing in fixing this.
