### ISSUE TITLE
Prefooter content on blog has inconsistent left/right spacing

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#3123]
## Current behavior

- Subscribe to RSS feed has different spacing in prefooter than other components around it.

## Expected behavior

- All components in the prefooter have the same left/right space.

## Steps to replicate behavior

1. Visit https://www.consumerfinance.gov/about-us/blog/
2. Resize the page down to mobile size.
3. Scroll to view prefooter.

## Screenshots

__Current__

![screen shot 2017-07-12 at 12 51 48 pm](https://user-images.githubusercontent.com/704760/28129912-2ef15c1c-6703-11e7-9caf-d46bad0a7b66.png)

**Comment by anselmbradford** [comment]
@schaferjh This is an issue, correct? I presume it should all left-align.

**Comment by schaferjh** [comment]
@anselmbradford It is a very minor bug, yes. It actually appears that it's the "Stay informed" section that is off as the subscribe CTA aligns with the content above "Stay informed." It's very low priority, though. If it should be worked on, I recommend moving it to the platform repo.

**Comment by gmkarl** [comment]
I viewed this page on 4/9/2019 on Windows 10 using both Google Chrome 73.0.3683.86 and Microsoft Edge 44.17763.1.0, and I was unable to reproduce this issue.  All the components of the prefooter appeared to have the same left margin to me.  Is this still an issue?

**Comment by anselmbradford** [comment]
Thanks @gmkarl this does appear to have been resolved!
