### ISSUE TITLE
Revisit base definition list styling

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cfgov-refresh#3124]
## The issue:

In updating the styling that fin-ed-resources imports from this project for the CF4 upgrade, I noticed that [this universal definition list styling](https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/css/enhancements/typography.less#L241-L268) was added to the CF enhancements here. This works pretty well for its [intended purpose](https://github.com/cfpb/cfgov-refresh/commit/d4ab0e825a41251313b5f1c26ec3cdb4112fb560#diff-4362f4d56b5ae00d0724af49023e680eR1119), the metadata lists on a job listing page, but is a bit specific for a general-purpose DL, and fails pretty badly if the `dt` is long, in particular:

![screen shot 2017-07-12 at 13 15 18](https://user-images.githubusercontent.com/1044670/28130840-187982fe-6706-11e7-94c3-d143171c634a.png)

## My proposal:

1. Create an `m-metadata-list` pattern in cf-typography that we could use on the job listing page and places like it.
2. Properly define general definition list styling (which we've never officially done) in cf-core.
3. Remove the enhancements code linked above.

## Please discuss:

- @cfpb/front-end-team-admin 
- @cfpb/design-team-admin (specifically for the general-purpose definition list styling)

**Comment by ielerol** [comment]
This is an example of the styling as intended on the jobs pages, right?

<img width="747" alt="screen shot 2017-07-12 at 10 46 42 am" src="https://user-images.githubusercontent.com/10562543/28131667-787b1896-66ef-11e7-8411-c0f40ba79e2c.png">

I agree that it's working well there and definitely not so well in that webinar archive example.

**Comment by Scotchester** [comment]
That's right, @ielerol.

**Comment by Scotchester** [comment]
Moved to Hubcap.
