### ISSUE TITLE
Media object to Capital Framework

### ISSUE THREAD

**Issue by cfarm** [cfpb/cfgov-refresh#321]
Can we get the [media](https://github.com/cfpb/cfgov-refresh/tree/gh-pages/docs/media) and [media object](https://github.com/cfpb/cfgov-refresh/tree/gh-pages/docs/media-object) styles added to Capital Framework so we can use it as a dependency on Owning a Home? 

I'm happy to attempt this and submit a PR if y'all think it's worth adding to CF.

**Comment by jimmynotjim** [comment]
:+1: go for it. Not sure about @anselmbradford and @sebworks but my backlog is backing up a bit so I probably won't have time till after this Sprint.

**Comment by Scotchester** [comment]
These are also overdue for being consolidated into a single thing, I think. Still not sure why we ended up with two implementations. @virginiacc was involved in the creation of one of these, perhaps she can lend a hand.

**Comment by anselmbradford** [comment]
I forget if it's media or media object, but @sebworks and I found that one or both of them has a top margin to align it with the line-height of heading text, when it is placed next to an `<h1>`, for example. This feels like an approach that's not ready for CF, since the alignment would be off if the heading text had a background color or border-top. Ideally with consolidating these two that could be looked at as well.

**Comment by virginiacc** [comment]
Good point about consolidation, @Scotchester -- it's definitely redundant to have both. I was working on pulling the image cropping functionality out of the `media-object` code so they could be combined. I'll see if that's ready to go and put in a pull request.

**Comment by virginiacc** [comment]
Just added a PR to move the post summary image cropping into its own class and combine the media objects.

**Comment by virginiacc** [comment]
The two media objects were consolidated in PR #325, so we should now be able to proceed with moving this out of the project.

**Comment by KimberlyMunoz** [comment]
@virginiacc or @cfarm, do you still need this moved into CF or was this already done?

**Comment by KimberlyMunoz** [comment]
Closing since it wasn't needed. We'll open a new issue and try to be more responsive about moving things out in the future!

**Comment by anselmbradford** [comment]
Was this moved?

**Comment by KimberlyMunoz** [comment]
Nope, it wasn't needed.
