### ISSUE TITLE
Wagtail admin: Contact > Phone rendering mangled when including dashes

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#3214]
Short description explaining the high-level reason for the new issue.

## Current behavior

- Add a phone number inside an expandable in Wagtail with dashes.
- Preview the page and note that it is mangled.

## Expected behavior

- Formatting of phone number with dashes is either disallowed, or is gracefully handled.

## Steps to replicate behavior

1. Create a browse page in wagtail.
2. Add an expandable.
3. Add a Phone with dashes in the number.
4. Preview the page. 

## Screenshots

__Current__

<img width="1007" alt="screen shot 2017-08-04 at 5 40 25 pm" src="https://user-images.githubusercontent.com/704760/28988138-6fd7a4f2-793c-11e7-95d9-ff90ad951603.png">

<img width="187" alt="screen shot 2017-08-04 at 5 40 32 pm" src="https://user-images.githubusercontent.com/704760/28988139-6fdb5aa2-793c-11e7-9ae4-3b7696344207.png">

__Expected__

<img width="177" alt="screen shot 2017-08-04 at 5 43 19 pm" src="https://user-images.githubusercontent.com/704760/28988137-6fd5f850-793c-11e7-85cd-2d0fe547a779.png">

**Comment by cfarm** [comment]
What Wagtail field is this?

**Comment by anselmbradford** [comment]
> What Wagtail field is this?

ContactPhone. Is that what you're asking? https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/v1/atomic_elements/molecules.py#L250
