### ISSUE TITLE
Checkboxes are off on multi-select

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#3392]
## Current behavior

- Looks like the multi-select's checkboxes checks are low compares to basic checkboxes. One or the other is wrong.

## Expected behavior

- All checkboxes look the same when checked.

## Steps to replicate behavior

1. visit /blog and check out the checkboxes in the filter.

## Screenshots

__Current__

![screen shot 2017-09-22 at 10 51 18 am](https://user-images.githubusercontent.com/704760/30750288-0b6c2cb8-9f84-11e7-9771-dc5965aec298.png)

**Comment by anselmbradford** [comment]
Actually, looks like it's due to the checkbox box size of the multi-select being slightly larger.

**Comment by jimmynotjim** [comment]
Part of this might be that the multiselect is using `cf-text-input` and possibly other old styles from this repo. Worth looking into updating this to v4 styles prior to moving it into Capital Framework.

**Comment by nataliafitzgerald** [comment]
@anselmbradford 
Ideally the checkmark would be centered vertically (and horizontally) in both instances. Currently, it looks like the checkmark is low in the multiselect and high in the standard checkboxes.

**Comment by Scotchester** [comment]
This will be updated soon with the change to SVG icons.

**Comment by anselmbradford** [comment]
This has been fixed.
