### ISSUE TITLE
BUG: Select elems in filterable controls get a-text-input classname

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#3443]
## Current behavior

The classname set [here](https://github.com/cfpb/cfgov-refresh/blob/3859d69acd6fc7d0acfefad827016dc77542dfbf/cfgov/v1/forms.py#L165) is also being set on select elements within the filterable controls module. It's been hidden because that element is replaced by the multiselect on page load.

## Expected behavior

The select element should have the proper class `a-multiselect` prior to the Multiselect script taking control.

## Steps to replicate behavior

1. To duplicate, turn off JS and inspect the element or view source.

## Screenshots

<img width="553" alt="screen shot 2017-10-03 at 9 06 32 pm" src="https://user-images.githubusercontent.com/1280430/31157199-da019038-a87e-11e7-9802-7902fd3258f6.png">

**Comment by anselmbradford** [comment]
Fixed by https://github.com/cfpb/cfgov-refresh/pull/4767

**Comment by jimmynotjim** [comment]
👏
