### ISSUE TITLE
Does outline require color?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#347]
Check that `outline` works as expected without a color https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/pages/bureau-structure.less#L178

**Comment by anselmbradford** [comment]
Err... looking at this again, it's the color that's missing not the unit.

**Comment by anselmbradford** [comment]
This is the default color that appears when tabbing to the element that uses this outline:

![screen shot 2015-03-19 at 12 02 29 pm](https://cloud.githubusercontent.com/assets/704760/6734668/dd8e510e-ce2f-11e4-8f94-deabaa6af2b4.png)

**Comment by KimberlyMunoz** [comment]
Add @pacific to the outline color.

**Comment by Scotchester** [comment]
Looks `@pacific` already to me.

**Comment by anselmbradford** [comment]
@Scotchester Do you know if outline explicitly needs a color set? In the case of this one it looks like it's inheriting the color, is that how it should be? That's what this issue is covering.

**Comment by Scotchester** [comment]
I guess I don't understand the issue. Do you not expect/want it to be Pacific?

**Comment by anselmbradford** [comment]
@Scotchester No the color is right, but should it be set in the outline, or is it fine to inherit it?

**Comment by Scotchester** [comment]
IMO, it's perfectly fine for it to be inherited.
