### ISSUE TITLE
Check if grid-gutter-width can be used for responsive size padding

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#349]
Would it be appropriate to use `@grid_gutter-width` in place of `30px` [here](https://github.com/cfpb/cfgov-refresh/blob/flapjack/static/css/misc.less#L789)?

**Comment by jimmynotjim** [comment]
I don't see why not, it's used for all sides to `padding` on [L:785](https://github.com/cfpb/cfgov-refresh/blob/flapjack/static/css/misc.less#L785)

**Comment by anselmbradford** [comment]
There are several occurrences where `@grid_gutter-width`, `(@grid_gutter-width / 2)`, and `(@grid_gutter-width * 2)` could be used in place of hardcoded values. See https://github.com/cfpb/cfgov-refresh/pull/401 for reference.
