### ISSUE TITLE
highcharts.css included in main.css uncompressed

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#3498]
## Current behavior

- highcharts.css is added to main.css unminized. (And to all pages.)

## Expected behavior

- highcharts.css should be minified with the rest of the CSS. 

## Steps to replicate behavior

1. Check `static_built/css/main.css` and see that highcharts CSS is unminified at the top.

## Screenshots

__Current__

![screen shot 2017-10-19 at 3 53 21 pm](https://user-images.githubusercontent.com/704760/31791137-b8d23548-b4e5-11e7-8421-2f7ed20e2215.png)

**Comment by sebworks** [comment]
This is happening because of the [inline](https://github.com/cfpb/cfpb-chart-builder/blob/master/src/css/cfpb-chart-builder.less#L1) property in the less file. If you switch it to `less`, then it seems to work fine.
