### ISSUE TITLE
Combine atomic-design page docs

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#3501]
## Current behavior

- Currently we have https://github.com/cfpb/cfgov-refresh/blob/master/docs/atomic-structure.md and https://github.com/cfpb/cfgov-refresh/blob/master/docs/notes-on-atomic-design.md

## Expected behavior

- Consolidate atomic-design into one doc.

**Comment by anselmbradford** [comment]
Also, much of this is outdated and internal chatter https://github.com/cfpb/cfgov-refresh/blob/master/docs/notes-on-atomic-design.md

**Comment by sebworks** [comment]
This has been implemented.
