### ISSUE TITLE
What is /offices/students-2/

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#351]
What is the status of the page http://flapjack.demo.cfpb.gov/offices/students-2/ ?
Is it in use?

If not, can https://github.com/cfpb/cfgov-refresh/tree/flapjack/offices and https://github.com/cfpb/cfgov-refresh/blob/flapjack/static/css/offices.less be removed?

**Comment by Scotchester** [comment]
I think this might have been a test page. @himedlooff?

**Comment by himedlooff** [comment]
It's a sample page for the offices section since we didn't have any content for this, or any other office page.

**Comment by jimmynotjim** [comment]
@KimberlyMunoz this can go away when the FOIA page gets up and working correctly right?

**Comment by kurtw** [comment]
https://github.com/cfpb/cfgov-refresh/pull/551

**Comment by anselmbradford** [comment]
Fixed ^
