### ISSUE TITLE
Some JS unit tests missing -spec suffix.

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#3524]
## Current behavior

- All JS unit tests have the `-spec` suffix in the file name so they are easier to differentiate from the source file when using cmd+t in an editor to look them up. However, the tests in https://github.com/cfpb/cfgov-refresh/tree/master/test/unit_tests/apps have the same file names as the source files.

## Expected behavior

- JS unit tests should all either have a `-spec` suffix or not.

**Comment by sebworks** [comment]
closed in #3525
