### ISSUE TITLE
Investigate whether minicon mixin can be used in place of unicode

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#354]
See https://github.com/cfpb/cfgov-refresh/pull/346#discussion-diff-26323793

**Comment by KimberlyMunoz** [comment]
Other projects have also been requesting this at cf-icons. I have a fork that I've already started that I can finish up today.

https://github.com/cfpb/cf-icons/issues/4

**Comment by anselmbradford** [comment]
sweet!

**Comment by KimberlyMunoz** [comment]
Merged. https://github.com/cfpb/cf-icons/pull/47

Once the changelog gets updated, we can update Flapjack with the new version.

**Comment by jimmynotjim** [comment]
[Changelog was updated](https://github.com/cfpb/cf-icons/pull/48), this can be done whenever someone has the time.
