### ISSUE TITLE
Fix step-slug positioning

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#363]
-Text isn't properly centered in step circle
-Step circle looks like bad Easter egg
![screen shot 2015-03-13 at 12 52 05 pm](https://cloud.githubusercontent.com/assets/1696212/6644718/b3a1cbf2-c98c-11e4-81df-5d8094cd9249.png)

**Comment by anselmbradford** [comment]
> Step circle looks like bad Easter egg

lol
