### ISSUE TITLE
Give IE9 no-js treatment

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#3687]
https://github.com/cfpb/cfgov-refresh/pull/3678 aimed to disable the busted mobile menu on IE9.
@sebworks pointed out that very few users actually visit the site in IE9 at mobile window sizes, so the extra bit of JS to do the disabling is probably not worth it. We also have two build configurations for IE8 and IE9 to handle a no-js and js state for each. If we merged those configurations we could eliminate a build step, the conditional comments and script for loading a class-list polyfill for IE9, and the JS added in #3678. Based on our analytics @sebworks says it's time and I agree.

@ascott1 @cfpb/cfgov-frontends Can we do it?

**Comment by Scotchester** [comment]
Probably should get a @schaferjh opinion on this, too.

**Comment by cfarm** [comment]
Is there a way to just serve the no-js menu to IE9 without disabling JS for all IE9 users? Can we scope a class name for the mega menu without js, and turn that on for IE9 and below?

**Comment by cfarm** [comment]
Also, @sebworks and @anselmbradford, as the proposers of this change, can you document for us what key pages will be affected that currently support IE9 JS, and the number of IE9 users on those pages in the last year? (Check out key pages list in the Platform wiki on GHE: https://GHE/CFGOV/platform/wiki/Key-pages-for-QA%2C-testing%2C-analytics). 

Perhaps it would also help to have a snapshot of how those numbers have changed over the last couple of years or so.

**Comment by sebworks** [comment]
ok, let me write some stuff up this weekend on how I think the change will affect us.

**Comment by sebworks** [comment]
Currently, less than 1% of all users are visiting the site using IE9. There are currently more visitors using IE8, which has already been transitioned to the no js experience.  The chart below shows the amount of IE users for the last 6 months. 

<img width="404" alt="screen shot 2017-12-18 at 11 08 00 am" src="https://user-images.githubusercontent.com/1696212/34115471-bddcdd54-e3e3-11e7-9c75-bce8b33f9efa.png">

The chart below depicts IE9 users for a two year period starting December 17, 2015.  From 20,000 monthly users to 630.

<img width="1082" alt="screen shot 2017-12-18 at 11 12 44 am" src="https://user-images.githubusercontent.com/1696212/34115719-67d33b64-e3e4-11e7-9a85-499858a65dd3.png">


As @anselmbradford has mentioned above, providing the no js experience for IE9 will significantly reduce the burden of ensuring the site behaves and looks correctly on IE9. Although, some the burden can be alleviated through automation, we will always be fighting an uphill battle to support so many old and new browsers.

I do think we shouldn't be making the decision for every application.  If a satellite application wants to support IE9, then we should still be able to facilitate that requirement.

**Comment by anselmbradford** [comment]
Great summary @sebworks. Having fewer users than IE8 is very compelling. I [created a PR](https://github.com/cfpb/cfgov-refresh/pull/3693) that removes the IE9 cruft. You can see it's quite a bit.

**Comment by mistergone** [comment]
@anselmbradford @sebworks - we discussed at the FEWD browser support group trying to apply our Change Management policy to this issue as a test run. Would you mind working through the following questions as a test run for making this kind of decision as a group?


1.  What is the device/OS/browser/feature for which you would like to drop support in this app?
2. What problem does dropping this support solve?
   1. Are you dropping support because engineering compatible solutions is too hard, or because no compatible solution yet exists? If the former, discuss the business impact of adding the time to build the compatible solution.
3. What is your fallback for this content in an accessible way for browsers that do not support?
4. What percentage of site users will not have access to your app because of this (request to Digital Analytics team to determine exact numbers at the time of the request so the team can validate. Include audiences if relevant)
   1. Include affected key pages (we provide list of links)
   2. Include affected satellite apps/repos (we should provide a list of links)
6. What are the performance impacts? Provide estimates or prototyped numbers for key metrics using Google Analytics and WebPageTest on impacted pages.

**Comment by cfarm** [comment]
@anselmbradford @sebworks 
For more context on the decision making process we're proposing in the Browser Support Working Group that will make use of the answers to the questions, check out the FEWD chat in Mattermost - links to the Draft policy google doc are posted there!

**Comment by anselmbradford** [comment]
1.  What is the device/OS/browser/feature for which you would like to drop support in this app?

JavaScript interactive experience for IE9 (does not include analytics scripts, etc.)

2. What problem does dropping this support solve?
   1. Are you dropping support because engineering compatible solutions is too hard, or because no compatible solution yet exists? If the former, discuss the business impact of adding the time to build the compatible solution.

  - Simplifies the build process since we can treat IE as before IE9 and after IE9, instead of IE8, IE9, and after IE9.
  - Simplifies the modernizr check since IE9 supports all es5 feature checks except strict-mode, but excluding IE9, modernizr can check shorthand `es5` feature detection.
  - Simplifies scripts. For example, the polyfill for class-list isn't needed, and the fallback for the dynamic script loader isn't needed (NOTE: this does have overlap with Opera and Safari http://kangax.github.io/jstests/script-element-onload-attribute-support/). 

3. What is your fallback for this content in an accessible way for browsers that do not support?

The `no-js` class is added to the HTML element, which is used to modify the CSS and provide a fallback experience.

4. What percentage of site users will not have access to your app because of this (request to Digital Analytics team to determine exact numbers at the time of the request so the team can validate. Include audiences if relevant)

See @sebworks summary above.

![screen shot 2017-12-21 at 12 57 23 am](https://user-images.githubusercontent.com/704760/34242547-f44cbf28-e5e9-11e7-8b21-281bbc51a7ae.png)

   1. Include affected key pages (Check out key pages list in the Platform wiki on GHE: https://GHE/CFGOV/platform/wiki/Key-pages-for-QA%2C-testing%2C-analytics)

![screen shot 2017-12-21 at 12 54 03 am](https://user-images.githubusercontent.com/704760/34242444-7943ec02-e5e9-11e7-88ab-566fdd8cdf91.png)

   2. Include affected satellite apps/repos - https://github.com/cfpb/development/issues/134#issuecomment-351824442 Ask @jimmynotjim for help if you're not sure!

Correct me if I'm forgetting, but satellite apps will be handling their own JS and won't be relying on common.js. 

6. What are the performance impacts? Provide estimates or prototyped numbers for key metrics using Google Analytics and WebPageTest on impacted pages. (See Key metrics in the Platform wiki on GHE: https://GHE/CFGOV/platform/wiki/How-to-measure-and-improve-performance)

Essentially unchanged for normal usage.

Before:
![screen shot 2017-12-21 at 12 42 01 am](https://user-images.githubusercontent.com/704760/34242136-d329868e-e5e7-11e7-9b8d-9f5fd4100eb8.png)

After:
![screen shot 2017-12-21 at 12 42 11 am](https://user-images.githubusercontent.com/704760/34242139-d54674ea-e5e7-11e7-953e-06849c11c334.png)

**Comment by anselmbradford** [comment]
> NOTE: this does have overlap with Opera and Safari http://kangax.github.io/jstests/script-element-onload-attribute-support/

Opera 8.54 and Safari 2.0.4 are listed as not having support. I couldn't find either exactly in our visitors. But total Opera visitors over the past year are 0.21% and I found Safari 2.0.1 in in-app Safari, which is 0.000023% of visitors (313 over the past year).

**Comment by jimmynotjim** [comment]
> Correct me if I'm forgetting, but satellite apps will be handling their own JS and won't be relying on common.js

Sort of, it looks like the recommended change is mostly implemented via the `no-js` body class. I believe most of those apps would need to make the same change in their own template code, but something like Owning a Home that is half satellite and half cfgov-refresh would be partially affected. Maybe this question should be extend further to ask whether the recommendation will be propagated to satellite apps or contained to the main project.

**Comment by cfarm** [comment]
> Correct me if I'm forgetting, but satellite apps will be handling their own JS and won't be relying on common.js.

Like @jimmynotjim I would like to clarify this answer as much as we can. We can look into at today's browser support meeting.

**Comment by cfarm** [comment]
VOTE HERE

**Comment by cfarm** [comment]
@ascott1 @schaferjh the browser support working group's recommendation is to implement this change as proposed, pending the following action items:

- [ ] Update proposal with more details based on meeting discussion - @anselmbradford 
- [ ] Document how to extend base template for supporting ie9 js - @anselmbradford and @jimmynotjim 
- [ ] Document some improvements to no-js state for cfpb-chart-builder apps (Mortgage performance, Consumer credit trends) - @contolini 
- [ ] Document no-js experience on affected pages (FEWDs are documenting in this thread).

**Comment by anselmbradford** [comment]
Pages that will be affected by this change will be using a script in base.html to change the `js` class added by modernizr to `no-js` https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/jinja2/v1/_layouts/base.html#L191

Pages that want to keep using their own JS can create an intermediate template that extends base.html but overrides the `{% block javascript %} … {% endblock %}` with their own block, [like is show in this closed PR](https://github.com/cfpb/cfgov-refresh/pull/3165/files#diff-4a835571f603714f3b11ea7126d34be7).

**Comment by jimmynotjim** [comment]
Realizing the JS extending probably doesn't belong in the Browser Support guide because it's not really specific to support. Should we officially documented somewhere other than this issue, maybe within cfgov-refresh or the HUB? Then we can point to it as an example in the guide of how we handle browser support differences between cfgov proper and a satellite project that uses base.html.

**Comment by ascott1** [comment]
> Realizing the JS extending probably doesn't belong in the Browser Support guide because it's not really specific to support. Should we officially documented somewhere other than this issue, maybe within cfgov-refresh or the HUB? Then we can point to it as an example in the guide of how we handle browser support differences between cfgov proper and a satellite project that uses base.html.

This is a great idea.

**Comment by jimmynotjim** [comment]
Discussion is complete and moved to the PR #3693. If you see something we missed please bring it up there.

**Comment by jimmynotjim** [comment]
Turns out these are still outstanding:

https://github.com/cfpb/cfgov-refresh/issues/3687#issuecomment-358122268

**Comment by jimmynotjim** [comment]
@sebworks is it possible for a single page within the main v1 section of cfgov-refresh to receive differing support than the rest? For example, if we for whatever reason found there were a lot of IE9 visitors attempting to use https://www.consumerfinance.gov/practitioner-resources/library-resources/ but couldn't interact with the video player, could we add scripting to shim that page alone for IE9

**Comment by anselmbradford** [comment]
> Document how to extend base template for supporting ie9 js - @anselmbradford and @jimmynotjim

Added a section in this PR https://github.com/cfpb/cfgov-refresh/pull/3873

**Comment by sebworks** [comment]
@jimmynotjim, I suppose we could do that by altering the scripts in `base.html` I don't think we should though for IE9. Once we place IE10 on the `no-js` list then it probably makes sense to do that.

**Comment by jimmynotjim** [comment]
Can we override `base.html` without using a custom template for the page? If not, we should document that custom templates are a requirement for modifying the browser support.

On the browser side, I'm not sure it should matter what version it is. If the analytics are telling us we have a large user base of "unsupported browsers" trying to use a specific page, we should take the time to ensure it works for them and have a plan how to deliver modifications to make that so. I picked Library pages specifically because libraries are usually the last to update their hardware and software, and patrons often rely on the public access from libraries as their only connection to the web.

**Comment by sebworks** [comment]
No, so each module should provide a `no-js` fallback. The video module should still work but you will be redirected to Youtube to watch it.  You must have js enabled tough but that is a requirement on the Youtube side.

**Comment by jimmynotjim** [comment]
Ah right, that makes sense. @cfarm can you remember if there are any other questions we had here? I think everything we discussed in the meetings has been answered but don't want to close if there's something still outstanding.

**Comment by jimmynotjim** [comment]
#3873 was merged and deployed, we can close this issue.
