### ISSUE TITLE
Broken layout at 809px

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#374]
Visit the site and resize to 809px wide. The About navbar item ends up on its own line:

![screen shot 2015-03-16 at 4 29 37 pm](https://cloud.githubusercontent.com/assets/704760/6675821/bfeabeea-cbf9-11e4-80aa-0b95460ae7de.png)

Also, the transition to tablet size is a pretty rough transition.

Both issues are low priority.

**Comment by anselmbradford** [comment]
Hm, realize this was introduced in my PR https://github.com/cfpb/cfgov-refresh/pull/371 :-/ because the header text is longer...

**Comment by duelj** [comment]
I was thinking about this yesterday when you said you were going to tackle it. I was curious to see what would happen if it broke. I spend a little time yesterday on a template file just looking at possible solutions if we want to keep the normal navigation at this width. The top version is adjusting the type size to 16px medium to fit them all on one line. This would likely not work much narrower than 768px. The bottom version is keeping the 18px type but allowing it to stack. This could work  down to a width that we just switch to the mobile nav at. The problem with it is, it looks pretty unresolved (bad), especially with the "about" label being so short. 
![screen shot 2015-03-17 at 9 57 55 am](https://cloud.githubusercontent.com/assets/6873734/6688819/bc6e3d44-cc8c-11e4-8413-def024ae81fa.png)

**Comment by anselmbradford** [comment]
@duelj Keeping the existing breakpoint width would be great! I got down kind of a rabbit hole on this issue. For instance, if you visit https://github.com/cfpb/cfgov-refresh/blob/flapjack/static/css/beta.less and search for `respond-to` you'll see there are a whole bunch of breakpoints that would need to be updated and checked if the header breakpoint width changes.

From what you wrote it sounds like reducing the header navbar text may be the route to try?

**Comment by duelj** [comment]
After the design review today we had settled letting the labels break to multiple lines and adjusting the type size (from 18px to 16px Avenir Next regular). I have an example below and will present this during the Thursday (3/19) working session. I am not sure how the type size adjustment affects break points, let me know if there is something we missed on this. 

Proposed style|Spacing detail|
---|---
|![screen shot 2015-03-17 at 1 57 24 pm](https://cloud.githubusercontent.com/assets/6873734/6694180/c2647868-ccae-11e4-96e7-16aabc94a1fa.png)|![screen shot 2015-03-17 at 2 04 25 pm](https://cloud.githubusercontent.com/assets/6873734/6694184/c8cb70bc-ccae-11e4-9d48-081f77f31328.png)|
