### ISSUE TITLE
Scrolling menu at tablet size and resizing leads to confusing page-tall white gap

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#375]
To reproduce:
1. Resize page to show tablet size. 
2. Open sidebar menu.
3. Scroll down.
4. Close menu.
5. Resize page.

![transition](https://cloud.githubusercontent.com/assets/704760/6677445/6c370940-cc06-11e4-989b-b9f26ddae2f0.gif)

This may be an issue if someone opens, scrolls and closes the menu on a tablet and then rotates the tablet.

@jimmynotjim Had some ideas for a solution.

**Comment by Scotchester** [comment]
Is this tested by sizing the viewport in Chrome with side-docked DevTools? If so, note that the media query widths do not take into account the space taken up by the scrollbar.

**Comment by anselmbradford** [comment]
@Scotchester This is in Chrome, but without the DevTools open.

**Comment by Scotchester** [comment]
How did you determine the window size?

**Comment by anselmbradford** [comment]
Haha, good call! I did open the DevTools to check the window size, but then opened a new window (which opens at the last open size) to check the behavior, so the gif is without DevTools open (also I opened DevTools bottom-docked).

**Comment by Scotchester** [comment]
:)
