### ISSUE TITLE
Explore ability to use bold/italic Avenir Next in combination

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#386]
Explore the best method for using bold/italic Avenir Next in combination

**Comment by Scotchester** [comment]
A long time ago, we agreed to limit things to four styles for performance reasons. That footer issue is the only place it's come up so far. We've successfully avoided needing bold-italic to this point. I would recommend continuing to try and avoid it.

**Comment by Scotchester** [comment]
To clarify: The four styles we have in use are:
- Regular
- (Regular) Italic
- Medium
- Demi (which is used in place of bold)

**Comment by sebworks** [comment]
ok, I'm going to close this issue as the new footer design no longer uses bold/italic in combination.
