### ISSUE TITLE
Align heading and filters button on /blog

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#394]
Currently the heading and filter button are on two lines, leaving an odd layout.

![screen shot 2015-03-20 at 10 41 04 am](https://cloud.githubusercontent.com/assets/1280430/6753611/aa90eabe-ceed-11e4-9acc-a4876abf9161.png)

The issue with moving things around is that there is no logic for when filters are applied leaving a more broken layout.

![screen shot 2015-03-20 at 10 36 16 am](https://cloud.githubusercontent.com/assets/1280430/6753630/c7240666-ceed-11e4-9810-3b17e1206410.png)

Possible [solution recommended](https://github.com/cfpb/cfgov-refresh/pull/357#issuecomment-79128162) by @Scotchester is to add class through the filtering logic.

**Comment by sebworks** [comment]
No longer relevant as we have updated the filter designs.
