### ISSUE TITLE
Remove unit() method for calculations that don't convert units

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#402]
Some uses of `unit()` helper mixin convert a variable that's already in pixels to pixels.

See:

https://github.com/cfpb/cfgov-refresh/pull/401#discussion_r26867139
https://github.com/cfpb/cfgov-refresh/pull/401#discussion_r26867272
https://github.com/cfpb/cfgov-refresh/pull/401#discussion_r26867311
https://github.com/cfpb/cfgov-refresh/pull/401#discussion_r26867332
https://github.com/cfpb/cfgov-refresh/pull/401#discussion_r26868272
https://github.com/cfpb/cfgov-refresh/pull/401#discussion_r26868325
https://github.com/cfpb/cfgov-refresh/pull/401#discussion_r26868339

**Comment by anselmbradford** [comment]
This may have been fixed in https://github.com/cfpb/cfgov-refresh/pull/525

**Comment by anselmbradford** [comment]
Appears to have been fixed. I couldn't find another occurrence of this.

**Comment by KimberlyMunoz** [comment]
Yep. I forgot to tag this as closed. Thanks!
