### ISSUE TITLE
Align readme with updated OS project template

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#409]
When https://github.com/cfpb/open-source-project-template/issues/11 is resolved, update this repo's Readme to align to the clarified structure for requirements, tech stack, etc.

See https://github.com/cfpb/cfgov-refresh/pull/247#discussion_r26838707

**Comment by wpears** [comment]
The readme structure has diverged quite a bit from when this was proposed and non-bugfixes in that template seem more or less abandoned. Closing for now, if work picks up on https://github.com/cfpb/open-source-project-template/issues/11, I'm sure it will be done with updating this readme and a new issue can be opened.
