### ISSUE TITLE
Improve client-side validation on filters

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#416]
Rework filters so that it isn't necessary to swap the values. See comment thread at https://github.com/cfpb/cfgov-refresh/pull/366#issuecomment-81717149

**Comment by jimmynotjim** [comment]
Before doing this, we should wait and see how the filters get flushed out. The recommendation from design seemed to be replacing multiple drop downs with a single text input for each end of the query period. I'm not sure if that's been finalized though. cc @ajbush @duelj

**Comment by sebworks** [comment]
This is no longer relevant.
