### ISSUE TITLE
Refactor Character icons to remove BEM modifiers

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#428]
Character icons, in misc.less, need to be refactored to remove the step BEM modifiers (e.g. 1, 2, 3, a, b, c).  This now can be accomplished using CSS counters (https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Counters). Need to make sure the solution degrades gracefully.

**Comment by anselmbradford** [comment]
Is this issue referring to https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/css/pages/event.less#L116 ?

**Comment by jimmynotjim** [comment]
I don't remember events having steps but I know OaH does https://www.consumerfinance.gov/owning-a-home/process/close/

**Comment by Scotchester** [comment]
It's referring to this: https://github.com/cfpb/cfgov-refresh/blob/master/cfgov/unprocessed/css/misc.less#L154-L254

**Comment by jimmynotjim** [comment]
Looks like it was only used on [Doing Business with Us](https://www.consumerfinance.gov/about-us/doing-business-with-us/) which has been modified since moving to Wagtail. Can we ditch these entirely or do we still want them on that page?

**Comment by sebworks** [comment]
@jimmynotjim, how do you feel about closing this issue?

**Comment by jimmynotjim** [comment]
If they're no longer used lets close it. If it resurfaces we can always reopen it at a later date.
