### ISSUE TITLE
<sub> element overlaps at mobile sizes

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#431]
- Visit http://beta.consumerfinance.gov/budget/performance-plan-report
- Resize window down to a small screen size. 
- Observe this:

![screen shot 2015-03-26 at 7 07 27 pm](https://cloud.githubusercontent.com/assets/704760/6859089/927862c4-d3eb-11e4-823e-28332c30184b.png)

**Comment by Scotchester** [comment]
While this is super weird, this text shouldn't be in a `sub` element. This is not a problem in real-world content scenarios.

**Comment by anselmbradford** [comment]
> While this is super weird, this text shouldn't be in a sub element. This is not a problem in real-world content scenarios.

So there are two issues? (a) Sub shouldn't be wrapping text like this on one line, and (b) this particular content shouldn't be in a sub in the first place. Is that right?

**Comment by Scotchester** [comment]
(a) Probably not, but in properly-marked up content, you'll never have `sub` with more than 2 characters in it. (b) Correct.
