### ISSUE TITLE
Testing Chosen.js

### ISSUE THREAD

**Issue by himedlooff** [cfpb/cfgov-refresh#44]
Chosen.js testing: http://cfpb.github.io/cfgov-refresh/blog_static/landing.html

## Browsers

- [x] Chrome (31)
- [x] Safari (6,7)
- [x] FF (28)
- [x] IE11
- [x] IE10
- [x] IE9
- [ ] IE8
  - Everything works well except for the bg img. The issue is with Legacssy and an issue has been created here: https://github.com/robinpokorny/grunt-legacssy/issues/7
- [x] IE7 N/A Chosen is disabled on IE7, a standard select menu is the fallback
- [x] Opera (12)
- [ ] iOS (6,7)
  - Chosen is disabled on the iphone and ipod, a standard select menu is the fallback
  - Chosen is NOT disbaled on the ipad and does not work well because it activates the select underneath it. It's also very difficult to close it once opened.
- [x] Android (4.4,4.3) N/A Chosen is disabled on Android, a standard select menu is the fallback
- [ ] Blackberry Bold
  - Chosen is NOT disabled on Blackberry and suffers from a known issue where clicking on the drop down will activate items underneath it

## Accessibility

- [x] Keyboard friendly
- [ ] Screen reader friendly
  - Not screen reader friendly, we will address this in the next sprint

## Other

- [x] Is useable without CSS

**Comment by jimmynotjim** [comment]
I'm going to assume since chosen is already implemented we can close this?

**Comment by anselmbradford** [comment]
Seems like it. Looks like it was tested almost all the way, and the gaps would surface in general testing as well.

**Comment by jimmynotjim** [comment]
Ok closing for now
