### ISSUE TITLE
Improve the convenience of the collapse function on expanded history timelines

### ISSUE THREAD

**Issue by jameshupp** [cfpb/cfgov-refresh#452]
When a user expands any of the timelines, s/he is at the top of that particular list. To collapse it, user has to scroll all the way to the bottom. As one colleague put it, this kind of defeats the purpose of closing it".

There should be a collapse toggle of some kind at the top of the open timeline.

**Comment by anselmbradford** [comment]
What pages do these appear on?

**Comment by jimmynotjim** [comment]
@schaferjh Was this included in the discussion about accordions vs "static" expandables?

**Comment by schaferjh** [comment]
@jimmynotjim yes and no. :)

* The history timeline expandables already function independently of one another -- they are not an accordion and you can open as many or as few of them as you want. 
* We know that they need to be brought up to "code" as it were to match our expandable style -- which will fix the issue @jameshupp has identified here. That's part of what @duelj was looking at this sprint.
* We just got some user testing feedback on these timelines that may mean we rethink their structure a bit in future releases. 'Twill be added to the backlog once feedback is fully processed.

**Comment by jimmynotjim** [comment]
@schaferjh since it sounds like it's a multi-tasked issue, should we close this in favor of individual Jira tasks?

**Comment by schaferjh** [comment]
yes, that sounds good.
