### ISSUE TITLE
Changelog - Link to semver info from readme

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#460]
https://github.com/cfpb/cfgov-refresh/blob/flapjack/CHANGELOG.md links to readme at the top, but could connect direct to https://github.com/cfpb/cfgov-refresh/blob/flapjack/README.md#how-this-repo-is-versioned

OR

semver section from readme could possibly be moved entirely over to the top or bottom of the changelog.

**Comment by jimmynotjim** [comment]
I'm on board with moving it into the CHANGELOG, it's how many projects do it (ex of my own https://github.com/jimmynotjim/scrollNav/blob/master/CHANGELOG.md)

**Comment by anselmbradford** [comment]
:+1: That would be my feeling too.
