### ISSUE TITLE
Running all tests together

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#462]
What is/going to be our project strategy for running all tests together? E.g. something like `grunt test` or an [sh script](https://github.com/codeforamerica/ohana-web-search/blob/master/script/test) to run all code quality checks (jinja template unit tests + browser tests + mocha or whatever js tests I anticipate we'll have at some point, maybe eslint, etc.)

cc @willbarton

**Comment by jimmynotjim** [comment]
This is being packaged in #797
