### ISSUE TITLE
Need an edit to this page by COB today (01/28)

### ISSUE THREAD

**Issue by welterso** [cfpb/cfgov-refresh#4788]
When I go to the following page and try to access content view, I don't see the Wagtail bird and can't edit the page: https://www.consumerfinance.gov/consumer-tools/financial-well-being/about/

Please edit this page as follows:
on right sidebar, add link at top of list under For Further Reading and Research sidebar: See how to use financial well-being with the people you serve [link to /practitioner-resources/financial-well-being-resources]

I need this edit by COB today (01/28).

Thanks!

## Expected behavior

-

## Steps to replicate behavior

1.

## Screenshots

__Current__

__Expected__

**Comment by Scotchester** [comment]
This update is live.
