### ISSUE TITLE
sidenav is blank with only cf-expandable JS

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#501]
Initial state of sidenav on `/doing-business-with-us/past-awards/` is blank because the expandable tab is hidden and it is set as a closed cf-expandable initially. It animates downward when it opens, which is controlled by a separate script. If the second script was not present and the pure cf-expandable script was used it would not display at all:

![screen shot 2015-04-30 at 8 55 24 pm](https://cloud.githubusercontent.com/assets/704760/7425246/5227bb9c-ef7b-11e4-9d90-44e1812fb42b.png)

Ideally the sidenav would not animate down initially on page load and would be already in an open state. The associated code triggers a click on the menu https://github.com/cfpb/cfgov-refresh/blob/flapjack/static/js/app.js#L76

**Comment by schaferjh** [comment]
@anselmbradford It looks like this is the case for all pages with a sidenav, right? It seems like an unnecessary bit of animation. @juidai do you know if there's a specific reason for having the sidenav expand?

**Comment by Scotchester** [comment]
It's an artifact of how it was coded to be able to collapse on mobile
devices.

**Comment by anselmbradford** [comment]
Yeah, probably what's needed is a script or CSS that overrides the animation for cf-expandables. The existing JS simulates a click to the menu, but we probably want it to be set directly to the open state initially, instead of having it closed and triggering a click event on it, which causes the animation to happen. @sebworks first encountered this with some screenshots he was taking in Selenium which ran faster than the animation happened and displayed like the screenshot in this post.

**Comment by schaferjh** [comment]
Huh. Add it to the backlog!

**Comment by anselmbradford** [comment]
Added as DF-1856

**Comment by KimberlyMunoz** [comment]
This has been resolved with the refactoring.
