### ISSUE TITLE
Add querySelector and addEventListener polyfills so we don't need jQuery for DOM queries and events

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#502]
`querySelector` and `querySelectorAll` [are well-supported](http://caniuse.com/#feat=queryselector) (with the exception of IE7 – but there's a [polyfill for that](https://gist.github.com/chrisjlee/8960575)).

`addEventListener` is also widely supported, with the exception of IE8 and earlier ([polyfill available](https://css-tricks.com/snippets/javascript/addeventlistner-polyfill/)). It's a shame to have to hook into a huge library like jQuery to do simple DOM querying when virtually all browsers can do those operations natively.

**Comment by anselmbradford** [comment]
OAH polyfills https://github.com/cfpb/owning-a-home/blob/master/src/static/js/legacy/lte-ie8.js brought to my attention via @sebworks

**Comment by himedlooff** [comment]
jQuery is used here for more than simple DOM querying, can you explain the benefits of your proposal?

**Comment by anselmbradford** [comment]
> jQuery is used here for more than simple DOM querying, can you explain the benefits of your proposal?

Sure! So we've recently added Browserify to the site to break the JS apart into modules. At the moment everything is still being delivered to every page, but the idea is that eventually JS that applied only to one page could be cordoned off and only be delivered to the page it's needed on and none other, as OAH currently does.

In the existing codebase, it's not uncommon to have a module that looks like:

```
var $ = require( 'jquery' );

…
  $( '#beta-banner_btn' ).click( …
```

This code uses jQuery to proxy for `querySelector` and `addEventListener` and doesn't use jQuery for anything further. In this case the jQuery library is being used effectively as a polyfill for IE8-.
This necessitates two things:

- It requires jQuery to be loaded on pages that wouldn't normally require it. For example, a 404 page on mobile might be loading jQuery so that the menus on the page can do DOM querying.
- It bakes in jQuery syntax, which differs from the syntax of other web standard APIs. In contrast a polyfill specific to `querySelector` and `addEventListener` shadows standard syntax, leaving the door open to removing the polyfill in the future when IE7/IE8 support is no longer needed—without requiring any further adjustments to the codebase.

For the rest of the time where jQuery _is_ used for things beyond DOM querying, it can be required at the top of the modules where it's needed and delivered to the page where it's needed, like any other library that works on specific areas of functionality on the site.

**Comment by himedlooff** [comment]
I see where you're going with this and it makes a lot of sense. The more reliance on using jQuery the harder it will be to move off of it if/when we want to. It seems more about thinking long-term. All pages will probably still have jQuery on them since the main menu uses it for more than simple DOM queries but the more we do those simple things in plain JS the more flexible our future will be.
