### ISSUE TITLE
Should blog be lowercase in the Activity Log?

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#511]
Quick question. As I was scrolling down the Activity Log, I noticed `blog` is the only thing that is lowercase. Is this intentional?

![image](https://cloud.githubusercontent.com/assets/1860176/7484385/f30c8082-f355-11e4-984e-7a193ea85f45.png)

**Comment by juidai** [comment]
It is not on purpose. Please capitalize "B".

**Comment by KimberlyMunoz** [comment]
Thanks for the quick response! Looking into it.

**Comment by KimberlyMunoz** [comment]
[Found the culprit](https://github.com/cfpb/cfgov-refresh/blob/0b384511afc9536e16f65758bc48d2d32334eec9/activity-log/index.html#L44). I should have something up shortly with this and a few other icon issues.
