### ISSUE TITLE
Outdated documentation about Node version

### ISSUE THREAD

**Issue by chosak** [cfpb/cfgov-refresh#5111]
The current documentation cites requirements of

> Node.js v8.5 or higher, and npm v5.2 or higher"

But the frontend build seems to require at least Node 10. The docs should be updated.

Markdown source is [here](https://github.com/cfpb/cfgov-refresh/blob/dd09c94e5571a2f6154a07747d78ca1586b8d35b/docs/installation.md#front-end-dependencies), live version is [here](https://cfpb.github.io/cfgov-refresh/installation/#front-end-dependencies).

## Screenshots

![image](https://user-images.githubusercontent.com/654645/61132536-8e83fc00-a489-11e9-92b8-6f40ee4bd311.png)

**Comment by anselmbradford** [comment]
Fixed in https://github.com/cfpb/cfgov-refresh/pull/5114
