### ISSUE TITLE
Small fix: Another broken inset in the blog

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#512]
Related to #309. 

/blog/accepting-applications-for-our-advisory-board-and-councils-2015/

**Comment by anselmbradford** [comment]
@jimmynotjim Do you see the issue in https://www.consumerfinance.gov/about-us/blog/accepting-applications-for-our-advisory-board-and-councils-2015/ related to insets?

**Comment by jimmynotjim** [comment]
@anselmbradford This post was converted from WordPress prior to launch and would have changed from when this issue was created. I think we can close it.
