### ISSUE TITLE
setup regulation page

### ISSUE THREAD

**Issue by shaunstoltz** [cfpb/cfgov-refresh#5190]
python2_1        | [25/Aug/2019 03:41:13] "GET /regulations3k-service-worker.js HTTP/1.1" 200 1573
python2_1        | Flag BETA_NOTICE evaluated False with condition: environment is (False).
python2_1        | Flag HMDA_OUTAGE evaluated False with conditions: parameter (False), path matches (False).
python2_1        | Flag COMPLAINT_INTAKE_TECHNICAL_ISSUES evaluated False with conditions: path matches (False), boolean (False).
python2_1        | Flag COMPLAINT_INTAKE_MAINTENANCE evaluated False with conditions: path matches (False), boolean (False).
python2_1        | [25/Aug/2019 03:41:13] "GET / HTTP/1.1" 200 58780
python2_1        | [25/Aug/2019 03:41:13] "GET /static/css/main.css HTTP/1.1" 304 0
python2_1        | [25/Aug/2019 03:41:13] "GET /static/fonts/2cd55546-ec00-4af9-aeca-4a3cd186da53.woff2 HTTP/1.1" 404 1757
python2_1        | [25/Aug/2019 03:41:13] "GET /static/wagtailadmin/css/userbar.css HTTP/1.1" 304 0
python2_1        | [25/Aug/2019 03:41:13] "GET /static/fonts/627fbb5a-3bae-4cd9-b617-2f923e29d55e.woff2 HTTP/1.1" 404 1757
python2_1        | [25/Aug/2019 03:41:13] "GET /static/wagtailadmin/js/userbar.js HTTP/1.1" 304 0
python2_1        | [25/Aug/2019 03:41:13] "GET /static/img/logo_237x50.png HTTP/1.1" 304 0
python2_1        | [25/Aug/2019 03:41:13] "GET /static/fonts/2cd55546-ec00-4af9-aeca-4a3cd186da53.woff2 HTTP/1.1" 404 1757
python2_1        | [25/Aug/2019 03:41:14] "GET /static/fonts/627fbb5a-3bae-4cd9-b617-2f923e29d55e.woff2 HTTP/1.1" 404 1757
python2_1        | [25/Aug/2019 03:41:14] "GET /static/img/us-flag_22x13.png HTTP/1.1" 304 0
python2_1        | [25/Aug/2019 03:41:14] "GET /static/fonts/1e9892c0-6927-4412-9874-1b82801ba47a.woff HTTP/1.1" 404 1754
python2_1        | [25/Aug/2019 03:41:14] "GET /static/fonts/f26faddb-86cc-4477-a253-1e1287684336.woff HTTP/1.1" 404 1754
python2_1        | [25/Aug/2019 03:41:15] "GET /regulations3k-service-worker.js HTTP/1.1" 200 1573
python2_1        | Not Found: /policy-compliance/rulemaking/
python2_1        | Not Found: /policy-compliance/rulemaking/
python2_1        | [25/Aug/2019 03:41:17] "GET /policy-compliance/rulemaking/ HTTP/1.1" 404 1734
python2_1        | [25/Aug/2019 03:41:19] "GET /regulations3k-service-worker.js HTTP/1.1" 200 1573

__Current__

__Expected__

**Comment by willbarton** [comment]
Hi, @shaunstoltz. Can you say more about what you're trying to do?
