### ISSUE TITLE
Check and remove unnecessary parens

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#520]
See https://github.com/cfpb/cfgov-refresh/pull/508#discussion_r29684567

**Comment by KimberlyMunoz** [comment]
Code now exists at https://github.com/cfpb/cfgov-refresh/blob/f8710f995bc8bed1e941fde47025c675bb9135cb/src/_includes/macros/util/format/contact.html

**Comment by anselmbradford** [comment]
Thanks! Stealth updated to line number.
