### ISSUE TITLE
If code is unreleased, don't tag banner code with release version

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#531]
Currently the banner code adds [`pkg.version`](https://github.com/cfpb/cfgov-refresh/blob/flapjack/Gruntfile.js#L201), which is the code version from [bower.json](https://github.com/cfpb/cfgov-refresh/blob/flapjack/bower.json#L3), however when the code is unreleased (e.g. when there is content in the Unreleased section of the changelog), this technically shouldn't be tagged with a release number as the actual JS code may contain more than what's in the release version specified.

**Comment by jimmynotjim** [comment]
so then there will be no version number at all in between releases? Maybe we need a release grunt task that adds all that only when opening a PR from refresh->beta?

**Comment by anselmbradford** [comment]
> So then there will be no version number at all in between releases?

That or something like:
```
 *  cfgov-refresh - v3.0.0-1.0.0 + Unreleased
```

> Maybe we need a release grunt task that adds all that only when opening a PR from refresh->beta?

That sounds good to me.

**Comment by sebworks** [comment]
We no longer include the version in the banner.
