### ISSUE TITLE
Can string-replace:static-legacy task be removed from Gruntfile?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#543]
The Gruntfile contains a rather lengthy task called [`string-replace:static-legacy`](https://github.com/cfpb/cfgov-refresh/blob/flapjack/Gruntfile.js#L49-L95). This tasked was added last year so that the styles from the existing site can be copied over and the font-references replaced so that the hosted fonts can be used (see https://github.com/cfpb/cfgov-refresh/pull/213#issuecomment-66196859). As far as I can tell the only purpose for this task is IF the styles.css is updated on the live site, it can be copied down into cfgov-refresh and this task can be run to incorporate it into the project correctly. I'm unclear if styles.css on the live site will be seeing any updates anymore and whether this task could be removed and retrieved from history if needed again in the future.

cc @Scotchester

**Comment by Scotchester** [comment]
Even if the current site's `styles.css` is updated, there would be no need to update the one in this project's `/static-legacy`, because the only thing using it is the strategic plan, whose styling will almost certainly not be updated further.

So, yes, I think it's okay to remove this.

**Comment by anselmbradford** [comment]
Is the idea of `/static-legacy/` that it would be a directory for a number of legacy pages that may be migrated over as a final step of moving beta to www? So it _could_ be a dependency for more than the strategic plan in the future?

(That said I'm all good with recovering this task from history if needed.)

**Comment by Scotchester** [comment]
I think that could be a potential use, yeah. There's not a lot of harm in leaving it in there until we're sure.
