### ISSUE TITLE
Add correct JSdocs to JS

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#547]
Noticed while reviewing https://github.com/cfpb/cfgov-refresh/pull/539 that the JSDocs are wrong in https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/util/web-storage-proxy.js. They should use `@returns` and need to use multi-line code comment blocks to be picked up by the linter (boo, I wonder if this is a JSDoc setting?).

Overall the JS could use more jsdoc coverage, though low priority since we're not generating docs from it right now.

**Comment by anselmbradford** [comment]
Jira task DF-1940

**Comment by anselmbradford** [comment]
Some added in https://github.com/cfpb/cfgov-refresh/pull/1016

**Comment by KimberlyMunoz** [comment]
Closed with DFJR-33
