### ISSUE TITLE
Youtube API is generating errors due to http/https issues

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#548]
There are currently errors being generated when the Youtube iframe is inserted into the DOM. May need to switch from the Javascript api to the Iframe api. Also need to investigate the role the Google Tag Manager plays in inserting the YouTube api.

**Comment by anselmbradford** [comment]
See https://github.com/cfpb/cfgov-refresh/pull/552#discussion_r30545609

**Comment by sebworks** [comment]
I'm not currently seeing the bug on production. Can you verify @anselmbradford ?

**Comment by anselmbradford** [comment]
Yeah I don't see it on http://www.consumerfinance.gov/tax-preparer-resources/ or http://www.consumerfinance.gov/about-us/the-bureau/. 

I see it on
http://www.consumerfinance.gov/know-before-you-owe/ but is that the same player code?

**Comment by sebworks** [comment]
> I see it on
http://www.consumerfinance.gov/know-before-you-owe/ but is that the same player code?

No, that is just an embed.

**Comment by Scotchester** [comment]
I'll look into this.

>

**Comment by Scotchester** [comment]
Is KBYO the only place where it's happening?

**Comment by anselmbradford** [comment]
@Scotchester That's the only place I've seen it, but that doesn't mean it isn't elsewhere.

**Comment by Scotchester** [comment]
Well, yeah :) Just wondering if there were definitely examples of it elsewhere. The PR in the KBYO repo fixes it for KBYO, but without knowing if it's happening elsewhere, I can't fix it anywhere else. I guess we'll wait and see if other places get reported :)

**Comment by Scotchester** [comment]
Fixed the HTTPS error in KBYO, but there are other YouTube related issues. See DFJR-1392.

**Comment by schaferjh** [comment]
Since we didn't pick up any new jira issues for our final refresh team wrap up sprint, I'm not sure anyone has taken a look at DFJR-1392. @sebworks before you go on PTO would you take a look at that issue and let me know the urgency?

**Comment by sebworks** [comment]
@schaferjh, that issue is unrelated to this one. I'm going to close this issue as I don't see the original issue happening anymore.
