### ISSUE TITLE
Rename main.css to main.min.css

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#565]
https://github.com/cfpb/cfgov-refresh/blob/flapjack/static/css/main.css is minified, it should be named accordingly.

**Comment by jimmynotjim** [comment]
This will be harder to accomplish with the newly suggested `dev` and `build` tasks that change minification. Is it better to have a minified `main.css` or an unminified `main.min.css`?

**Comment by anselmbradford** [comment]
That's a good point. Some projects handle this by doing preprocessing based on environment. Ideally that's probably the way to go. See for instance, https://www.npmjs.com/package/gulp-preprocess

Otherwise my vote would be to keep it `main.css`, as that's how it currently is and unminified `main.min.css` sounds more misleading.

**Comment by jimmynotjim** [comment]
@anselmbradford yeah, I do the env thing in my personal projects and my past job, but the source swapping is automated there. I'm not sure how that'll work with Jinja templates. Just seems like a lot of extra work/code for a gain that doesn't really amount to much in the end.

**Comment by KimberlyMunoz** [comment]
Since we have different preprocessing on environment, can we close this @anselmbradford ?

**Comment by anselmbradford** [comment]
Probably should stay open. It's still an issue, albeit minor.

**Comment by anselmbradford** [comment]
The web has moved along in 5 years and I no longer think this makes sense to do. A particular CSS file could be in several states… e.g. pre-transpilation, post-transpilation, and minified. It doesn't make sense to introduce logic to change the path to a different filename based on the state of the file. Devs can view the file to see what state it is in.
