### ISSUE TITLE
Normalize single/double quotes in jinja template

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#567]
See https://github.com/cfpb/cfgov-refresh/pull/552#discussion_r30543834

**Comment by KimberlyMunoz** [comment]
Do we have a standard for single vs double quotes in jinja? I might standardize everywhere while I'm at it.

**Comment by anselmbradford** [comment]
I believe it's single quotes

**Comment by KimberlyMunoz** [comment]
Note to close DF-1317 after this issue is closed.

**Comment by KimberlyMunoz** [comment]
This would have been way easier to do in May before we created a lot of these pages.
