### ISSUE TITLE
Remove extra parens

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#568]
See https://github.com/cfpb/cfgov-refresh/pull/552#discussion_r30544327

**Comment by KimberlyMunoz** [comment]
Removing the parens cause an internal error. Will close for now.

**Comment by jimmynotjim** [comment]
Yep, it turns out the inner set is for the tuple so these all need to stay.

**Comment by anselmbradford** [comment]
Oh right, tuples..

**Comment by jimmynotjim** [comment]
![tuples](https://i.imgflip.com/on4lb.jpg)
