### ISSUE TITLE
cf_notifier.js: Use class to hide element

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#569]
`cf_notifier.js` uses `style="display: none;`, could it use the `u-hidden` class instead of inline styles?

See https://github.com/cfpb/cfgov-refresh/pull/552#discussion_r30545123 for background discussion.

**Comment by KimberlyMunoz** [comment]
Issues #570 and #571 are related.

**Comment by jimmynotjim** [comment]
Assigning all to me since I have a half working notifications module to go into CF. Hopefully find some time to finish it up toward the end of the sprint.

**Comment by sebworks** [comment]
We no longer use `cf_notifier.js`.
