### ISSUE TITLE
Remove unneeded this lookups

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#571]
See https://github.com/cfpb/cfgov-refresh/pull/552#discussion_r30545473

**Comment by anselmbradford** [comment]
Only remains in BreakpointHandler I think https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/unprocessed/js/modules/BreakpointHandler.js#L72

**Comment by sebworks** [comment]
This has been addressed.
