### ISSUE TITLE
Facebook Share Error in About-Us Hero

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#581]
Currently getting the following error when clicking on the Facebook share button on the About-Us Hero.

![screen shot 2015-05-20 at 5 54 12 pm](https://cloud.githubusercontent.com/assets/1696212/7737467/68d999de-ff19-11e4-90fb-7cdedbff8b91.png)
Need to find out who has admin rights to the CFPB Facebook page. Might need to just whitelist Flapjack/Refresh domains per @jimmynotjim , @KimberlyMunoz .

**Comment by KimberlyMunoz** [comment]
Share now seems to work differently.
