### ISSUE TITLE
Load global jQuery CDN to satisfy GTM requirement

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#587]
1. Load jquery CDN in head with fallback to local source:
  
 ```html
<script>
// If jQuery didn't already get loaded somewhere else, attempt to load it from a CDN.
if(typeof jQuery==='undefined'){document.write(unescape("%3Cscript src='https://cdnjs.cloudflare.com/ajax/libs/jquery/1.11.3/jquery.min.js'%3E%3C/script%3E"));}
// Check that jQuery loaded, otherwise fallback to loading it from a local source.
if(typeof jQuery==='undefined'){document.write(unescape("%3Cscript src='/static/js/vendor/jquery/jquery.min.js'%3E%3C/script%3E"));}
</script>
 ```
2. Move local jquery to `/static/js/vendor/jquery/jquery.min.js` via the settings in `bower.json` and the bower Grunt task (https://github.com/cfpb/cfgov-refresh/pull/553 needs merging first).

3. Set as global in browserify-shim https://github.com/thlorenz/browserify-shim#a-expose-global-variables-via-global in browserify.

4. Add TODO comment to refactor so jQuery loads in the footer. The best would be refactoring in GTM to remove the jQuery dependency if it's not needed or to have similar logic to step 1 where it's referenced in GTM.

See background in https://github.com/cfpb/cfgov-refresh/issues/496

**Comment by jimmynotjim** [comment]
Related https://www.youtube.com/watch?v=2ksXo2_Lfl0

**Comment by anselmbradford** [comment]
Error looks like this: 
![screen shot 2015-06-09 at 5 48 45 pm](https://cloud.githubusercontent.com/assets/704760/8070535/f7a71a2c-0ecf-11e5-9f10-e27f3ffd213c.png)
