### ISSUE TITLE
Organize includes directory

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#597]
We have a number of files types in the _includes directory:

1. **HTML snippets.** Straight-up HTML without any additional logic:
  - upcoming-events.html
  - header.html
  - footer.html
  - comments.html

2. **HTML templates.** HTML with jinja logic included:
  - nav-secondary.html

3. **Single-file macros.** HTML templates wrapped in a jinja `render` method that expects some arguments to be passed in:
  - tags.html
  - sidenav.html
  - rss.html
  - related-posts.html
  - related-links.html
  - posts-paginated.html
  - popular-stories.html
  - pdfreactor-footer.html
  - leadership-calendar-table.html
  - hero.html
  - contact-macro.html
  - category-slug.html
  - article.html

4. **Aggregate macros.** Single utility macros aggregated together into a single file:
  - post-macros.html
  - macros.html

The current setup has two issues:
  a. There are a mix of different include types mixed together in the same directory with no way to tell what's what without looking at the file contents.
  b. The utility macros are grouped by being macros or macros that work with posts, but without examining the file contents it's not clear what the macros are for.

To address (a) I propose we create subdirectories in the `/_includes/` directory and logically group the templates and macros separately. For (b) I propose we break apart the aggregate macros into topical files.

For (a) I'm thinking these three subdirectories:

```
_includes/macros/
_includes/macros/util/
_includes/templates/
```

HTML snippets and template would go into `/_includes/templates/`.
Single-file macros would go into `/_includes/macros/`.
Aggregate macros would be topically broken apart and go into `/_includes/macros/util/`.

```
_includes/macros/util/share.html # share and share-twitter-url macros
_includes/macros/util/format.html # format-phone, format-address, and slugify macros
_includes/macros/util/text.html # string_length macro

_includes/macros/subscribe.html # subscribe macro, with render method†.
_includes/macros/pagination.html # pagination macro, with render method†.
_includes/macros/youtube.html # YouTube macro, with render method†.
_includes/macros/activity-snippet.html # activity_snippet macro, with render method†.
_includes/macros/activity-snippets.html # activity_snippets macro, with render method†.
_includes/macros/post-summary.html # post_summary macro, with render method†.
_includes/macros/category-icon.html # category_icon macro, with render method†.
_includes/macros/filters.html # Filters macro, with render method, see note below† ††.
```

† The macros in `/includes/macros/` would need to be updated to use a `render` method for their main entry point.

†† The `filters.html` should contain the macros `active_filters`, `filters_form`, `filter_checkbox`, and `filter_option`, but these should be updated to be prefixed with an underscore to designate them as private so they can't be [imported elsewhere](http://jinja.pocoo.org/docs/dev/templates/#import).

How does this re-organization look to everyone?

**Comment by Scotchester** [comment]
Pinging @rosskarchner or @dpford to confirm that Sheer can deal with adding subdirectories to `_includes` and/or `_layouts`.

**Comment by anselmbradford** [comment]
Good call @Scotchester if subdirectories aren't possible, the file names could be prefixed with the directory structure, e.g. `templates_upcoming-events.html`, `macros_filters.html`, `macros_util_format.html`

**Comment by himedlooff** [comment]
Pro tip, read up on how Jinja caches `import`s: http://jinja.pocoo.org/docs/dev/templates/#import

I don't remember exactly how it works but if you did `import "nav.html"` in one file and then `import some-folder/nav.html` in another you can run into trouble because they both have the same filename. And since Jinja caches them you'll get whichever one was requested first.

**Comment by rosskarchner** [comment]
@himedlooff does it work that way in Sheer? I'd call that a bug.

**Comment by rosskarchner** [comment]
I think subdirectories *ought* to work, but I don't recall testing it myself.

**Comment by anselmbradford** [comment]
> By default, included templates are passed the current context and imported templates are not.…
This behavior can be changed explicitly: by adding with context or without context to the import/include directive, the current context can be passed to the template and caching is disabled automatically.

@himedlooff Interesting that imports appear to work like includes when `with context` (or from the reverse direction `without context`) is added. Seems like the places that use import with context could just use includes instead.

**Comment by anselmbradford** [comment]
We're using subdirectories now and haven't encountered any issues that I know of.
I just made a slight edit to the [original post](https://github.com/cfpb/cfgov-refresh/issues/597#issue-81589703) to make the HTML pages dash separated instead of underscore separated spacing because that appears to be the convention in place.

**Comment by KimberlyMunoz** [comment]
Hey @anselmbradford, we've mostly moved towards this. Is this ready to close?

**Comment by anselmbradford** [comment]
Yup moved quite a few, but still have some to go! Needs to stay open for now. Thanks for checking!

**Comment by anselmbradford** [comment]
Chatting with @sebworks about how we might evolve the file structure to handle our atomic design direction. The idea came up to have a [folder by feature structure](https://github.com/johnpapa/angular-styleguide#folders-by-feature-structure), so that each atom/molecule/organism would have all its assets together. Something like:

```
// Global non-atomic stuff
cfgov/jinja2/v1/_includes/common/macro/*
cfgov/jinja2/v1/_includes/common/template/*

// Atomic stuff
cfgov/jinja2/v1/_includes/atoms/*
cfgov/jinja2/v1/_includes/molecules/*
cfgov/jinja2/v1/_includes/organisms/filter-filterable-list/filter-filterable-list.html
cfgov/jinja2/v1/_includes/organisms/filter-filterable-list/filter-filterable-list.less
cfgov/jinja2/v1/_includes/organisms/filter-filterable-list/filter-filterable-list.js

// Global non-atomic CSS/JS
cfgov/preprocessed/css/common/*
cfgov/preprocessed/js/common/*
```

What do bewds @kurtw @kave @rosskarchner think about this? Right now we have things divided by technology, not feature, so what would be the implication for, e.g. pulling less out of `cfgov/jinja2/v1/_includes/organisms/filter-filterable-list/` instead of the preprocessed folder. Would gulp handle that and then the bewd build would pull the compiled main.css out of the preprocessed folder?

**Comment by Scotchester** [comment]
Just gonna throw this out there... `preprocessed` might not be the most future-proof name ;) (And it already sounds like the resulting CSS files AFTER preprocessing.)

**Comment by anselmbradford** [comment]
@Scotchester Here's the background on that folder name https://github.com/cfpb/cfgov-refresh/pull/1015 Though I'm not sure whether `preprocessed` is a Django convention or not.

**Comment by kurtw** [comment]
I think we're starting to get too far from best practices with that. It may be a nice to have everything grouped by feature but this is just...weird. Conventions have static assets in one folder and template in another.

`preprocessed` is not a Django convention. Might I suggest 'unprocessed`? :D

**Comment by anselmbradford** [comment]
@Scotchester I realized I wrote putting the compiled main.css file in `preprocessed`, I meant `static_built`.

@kurtw So take the filter-filterable-list for example, with the existing setup we have:

```
cfgov/jinja2/v1/_includes/organisms/filter-filterable-list/filter-filterable-list.html
cfgov/preprocessed/css/organisms/filter-filterable-list/filter-filterable-list.less
cfgov/preprocessed/js/organisms/filter-filterable-list/filter-filterable-list.js
```

Do you see a better way?

Also, +1 to `unprocessed`

**Comment by Scotchester** [comment]
What I was trying to get at is that "preprocessed" is the output of the preprocessor. https://en.wikipedia.org/wiki/Preprocessor

**Comment by kave** [comment]
true i agree unprocessed makes more sense

**Comment by kurtw** [comment]
So these files that you're describing are under subject to change. We're discussing how our Django project will eventually be structured and without tipping the hand prematurely before a decision has been made, things will be different in the way it's structured. 

Fundamentally, I think organizing files by `organism` and `molecule` is a great way to go but I'm very hesitant to put them together in the same file as it creates an idiosyncrasy for our Django project that requires documenting. This means moving away from default behavior and therefore higher learning curve. I'd like to see other's thoughts on this.

**Comment by KimberlyMunoz** [comment]
Would you consider this done @anselmbradford

**Comment by anselmbradford** [comment]
I'm okay with closing it.
