### ISSUE TITLE
pdf.json is looking for files on localhost without a port, is this an issue?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#616]
See https://github.com/cfpb/cfgov-refresh/blob/flapjack/_settings/pdf.json#L7 for example, the URL `http://localhost/static/css/pdfreactor-fonts.css` won't resolve for me locally because there isn't a port set. How is this URL used? cc @dpford

**Comment by dpford** [comment]
PDFreactor accesses that URL as it runs alongside the web server.  It works.  It was actually recommended to use localhost over a relative URL by our fallen brethren who braved PDFreactor before us.

**Comment by anselmbradford** [comment]
Okay, just checking! Thanks!

**Comment by jimmynotjim** [comment]
@dpford which fallen brethren?
