### ISSUE TITLE
Broken image on /budget/

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#626]
Haven't looked into this, but marking it for later. There's a strange broken image on the budget page.

![screen shot 2015-06-05 at 5 20 04 pm](https://cloud.githubusercontent.com/assets/1860176/8015515/392ea28e-0ba7-11e5-8a90-cb96ace9289a.png)

**Comment by anselmbradford** [comment]
Strange. I don't see it.

**Comment by KimberlyMunoz** [comment]
:kanye-shrug: I don't see it anymore either.
