### ISSUE TITLE
Sidenav appears below hero on mobile on /the-bureau/ page

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#635]
Visit `/the-bureau`, sidenav appears below hero when it should appear above. Related to https://github.com/cfpb/cfgov-refresh/issues/408
![screen shot 2015-06-08 at 6 07 48 pm](https://cloud.githubusercontent.com/assets/704760/8068808/598704d4-0ec4-11e5-8c49-e2bc1adab191.png)

**Comment by sebworks** [comment]
@anselmbradford, what do you think about using is_mobile flag( in Jinja ) to determine if you are on mobile thus only writing one nav. https://github.com/cfpb/cfgov-refresh/pull/574/files#diff-ae11b16fd39f830f6f52d38e54892811R354. It wouldn't be responsive but would eliminate the double nav situation.

**Comment by anselmbradford** [comment]
I _think_ it would be possible to do with CSS, see this pen:

http://codepen.io/anon/pen/ZGyWWm?editors=110

Resize below 800px to see the divs swap stacking order.

**Comment by jimmynotjim** [comment]
I'm all for keeping this in CSS rather than trying to sniff out the browser in Jinja. Every time I've done that in the past it's lead to a world of hurt.

**Comment by anselmbradford** [comment]
This can be solved with modern browsers with Flexbox http://caniuse.com/#search=flexbox and the

**Comment by KimberlyMunoz** [comment]
This issue might go away with the design manual redesign on heros.

**Comment by KimberlyMunoz** [comment]
It went away with the redesign. There's no longer any pages with a side navigation and a hero.
