### ISSUE TITLE
Investigate and remove apparently unused cf_inputSplit.js

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#636]
https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/jquery/cf_inputSplit.js does not appear to be used anymore, with the exception of [a fixture](https://github.com/cfpb/cfgov-refresh/blob/flapjack/_tests/unit_tests/fixtures/forms.html#L47), which I believe is outdated.

I can't find anywhere else where the `.js-filter_range-date-wrapper` is used, so I think the HTML related to this jquery plugin has been refactored away, unless it's being added dynamically somewhere.

cc @Scotchester @himedlooff

**Comment by Scotchester** [comment]
This was used when we had two select fields for the date inputs when filtering (still live on Beta). No longer needed, now that you've changed to simple mm/dd/yyyy input. Poor @himedlooff put so much work into that :(

**Comment by himedlooff** [comment]
it happens, :+1: for simplicity
