### ISSUE TITLE
Refactor @font-size-small and @font-size-large variables out of existence

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#637]
`nav-secondary.less` contains `@font-size-small` and `@font-size-large` variables that likely aren't needed. Investigate their use, see if other existing variables can't be used instead and remove them.

See comment https://github.com/cfpb/cfgov-refresh/pull/634/files#r32061771

**Comment by KimberlyMunoz** [comment]
Refactored out! https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/unprocessed/css/organisms/secondary-navigation.less
