### ISSUE TITLE
Update forms testing fixture

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#638]
Form fixture names the form `email-subscribe-form_email-1`
https://github.com/cfpb/cfgov-refresh/blob/flapjack/_tests/unit_tests/fixtures/forms.html#L4
https://github.com/cfpb/cfgov-refresh/blob/flapjack/_tests/unit_tests/fixtures/forms.html#L7

However, the site appears to name the form `email-subscribe-form_email`.

**Comment by KimberlyMunoz** [comment]
We really should just remove the fixture and re-write that test suite. Could we close this issue to prevent any duplicate work on something that is on its way out?

**Comment by anselmbradford** [comment]
Is there an open issue around removing the fixtures? If not I can update this one to cover that.

**Comment by KimberlyMunoz** [comment]
I think there's a couple JIRA tasks on improving our unit tests in general, but that's a good call.

**Comment by anselmbradford** [comment]
Superseded by https://github.com/cfpb/cfgov-refresh/issues/832
