### ISSUE TITLE
New "In this Section" mobile nav needs some separation

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#652]
@KimberlyMunoz [pointed out](https://github.com/cfpb/cfgov-refresh/pull/648#issuecomment-111629020) that with the new breadcrumb nav above the mobile nav, there's no separation between the two. Not sure when the mobile nav changed, but it used to look more like the breadcrumb mockup she linked to when I first started the breadcrumbs.

cc @ajbush @duelj @schaferjh

**Comment by ajbush** [comment]
Hmm. The visual designs we landed on offered separation. Maybe a tweak was made I'm not aware of? See the screenshots below:

|No breadcrumb|With breadcrumb|
---|---|---
|![screen shot 2015-06-15 at 8 35 55 am](https://cloud.githubusercontent.com/assets/6931351/8159975/b3716bd2-1339-11e5-956d-daa1942e4b53.png)|![screen shot 2015-06-15 at 8 36 18 am](https://cloud.githubusercontent.com/assets/6931351/8159980/c7cbd586-1339-11e5-8c69-5e62318058f3.png)|

**Comment by schaferjh** [comment]
There hasn't been any change to the visual design -- there should be space between the breadcrumbs and the section dropdown. It looks like the dropdown does not have the light gray background and stroke on both top and bottom per @ajbush's design.

**Comment by anselmbradford** [comment]
Ahh, I went with the appearance in this gif --> [ghe]/flapjack/global/issues/20#issuecomment-43680 ... looks like a quick fix https://github.com/cfpb/cfgov-refresh/pull/656

**Comment by Scotchester** [comment]
I'm working on this in parallel with @jimmynotjim. We'll put our heads together this afternoon and get it squared away.
