### ISSUE TITLE
Verify that `cfpb_reports` is correct activity type for reports

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#654]
See https://github.com/cfpb/cfgov-refresh/pull/650#issuecomment-111629015

**Comment by KimberlyMunoz** [comment]
Hey @kurtw! Is this the right activity type for reports?

**Comment by kurtw** [comment]
It's called `cfpb_report`

**Comment by kurtw** [comment]
http://www.consumerfinance.gov/api/get_posts/?post_type=cfpb_report&count=50

**Comment by anselmbradford** [comment]
Heh, oops, looks like I had it right in the PR title and code edits, but not this issue comment.

**Comment by KimberlyMunoz** [comment]
Okay, so it looks like it's correct in the code. So I'm closing.

:heart: simple issues.
