### ISSUE TITLE
Map pin location is incorrect

### ISSUE THREAD

**Issue by Scotchester** [cfpb/cfgov-refresh#663]
I'm not sure how long this has been the case, but the Maps static API is generating an image with the pin for 1700 G Street in the wrong location (on /contact-us/). The actual location is across the street. I've marked our main entrance with a green star in the image below.

![screen shot 2015-06-16 at 14 53 43](https://cloud.githubusercontent.com/assets/1044670/8191864/9bd5759a-1438-11e5-8a3d-08601d9977bd.png)

**Comment by KimberlyMunoz** [comment]
Looks like Google has updated their location pin and I'll close this.

Here's the new location:

![image](https://cloud.githubusercontent.com/assets/1860176/8811035/131e1686-2fc1-11e5-9ff8-761bb842fe90.png)

![image](https://cloud.githubusercontent.com/assets/1860176/8811038/1c56a218-2fc1-11e5-90b6-ccd7b2868046.png)
