### ISSUE TITLE
Reduce complexity of conditions

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#667]
- @anselmbradford pointed out the default value of `from_date_formatted` may be an empty string, meaning [the condition on L:521](https://github.com/cfpb/cfgov-refresh/pull/660#discussion_r32529377) 
  of `_includes/post-macros.html` isn't necessary.
- There are a few instances of if/else conditions that could be reduced to one line [here](https://github.com/cfpb/cfgov-refresh/pull/660#discussion_r32537564) and [here](https://github.com/cfpb/cfgov-refresh/pull/660#discussion_r32660072).

There are most likely other instances of these and similar issues in the codebase. We should do a quick sweep to try and remove these unnecessary complexities.

**Comment by sebworks** [comment]
This issue predates the move to atomic design and most of the templates have been removed.
