### ISSUE TITLE
Remove unnecessary Jinja vars

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#669]
Some vars used in the Jinja templates are no longer necessary. We should do a quick sweep to make sure they are removed from the codebase. See [Sprint 29 PR comment](https://github.com/cfpb/cfgov-refresh/pull/660#discussion_r32533571)

**Comment by KimberlyMunoz** [comment]
Was is_mobile the only one you're thinking of or are there others? Just trying to grab more details so folks can grab this issue, especially if it's marked help wanted.

**Comment by jimmynotjim** [comment]
It was actually the `{%- set first = True %}` comment above that one. The `is_mobile` is a function that we use to sniff and swap content (a harder issue than this).
