### ISSUE TITLE
Explore reducing markup to create the main nav

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#671]
There are multiple wrapping elems to create the nav, both in `_includes/templates/primary-nav.html` and [where it's included](https://github.com/cfpb/cfgov-refresh/blob/flapjack/_layouts/base.html#L162). We should explore the possibility of reducing the markup and/or css and make it a bit simpler.

**Comment by KimberlyMunoz** [comment]
Is this done? @jimmynotjim
