### ISSUE TITLE
Weird wrapping on newsroom links

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#679]
![screen shot 2015-06-25 at 10 46 48 am](https://cloud.githubusercontent.com/assets/704760/8357187/91fff482-1b27-11e5-8680-fdaf26169e8b.png)

Because the link text is too long this is wrapping oddly.

Perhaps this could be shortened to `Payday field hearing remarks by Director Cordray`

**Comment by anselmbradford** [comment]
cc @sarahsimpson09

**Comment by sarahsimpson09** [comment]
Yup, go with your update! That's what I would have shortened it to.

**Comment by anselmbradford** [comment]
@sarahsimpson09 Can the interns update this?

**Comment by KimberlyMunoz** [comment]
So actually, this isn't necessary. We have an issue in JIRA that I'm taking on today to remove the arrows across the website.

**Comment by sarahsimpson09** [comment]
Great!--I was worried that trying to shorten the link text would open up a can of worms. That pulls straight from the title of the speech that's used on the current site now, and I have a feeling that trying to change that would have been a bigger deal than we wanted it to be.
