### ISSUE TITLE
Remove duplicate media query and update breakpoint to var

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#691]
In `nav-secondary.less` L:180 is no longer needed and the `801px` breakpoint should be updated to `$desktop-min` after the breakpoints branch is merged.

**Comment by KimberlyMunoz** [comment]
Refactored out. https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/unprocessed/css/organisms/secondary-navigation.less
