### ISSUE TITLE
Use block classes not utility classes for adjusting margin in blocks

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#696]
Replace instances of `u-mb0` and `u-mt0` with `block__flush-top` and `block__flush-bottom`.
See https://github.com/cfpb/cfgov-refresh/pull/690#discussion_r33521585

**Comment by KimberlyMunoz** [comment]
I think I'm mostly guilty of this, so I'll start cleaning this up.

**Comment by anselmbradford** [comment]
A caveat on this ... `block__flush-top`/`block__flush-bottom` eliminates padding, while `u-mb0`/`u-mt0` eliminates margin. So this won't be an equivalent replacement in cases where there are borders. Bottom line, just check that this is a harmless replacement in areas where it's updated.

**Comment by anselmbradford** [comment]
More instances of this:
 - https://github.com/cfpb/cfgov-refresh/blob/flapjack/the-bureau/about-rich-cordray/index.html#L17
 - https://github.com/cfpb/cfgov-refresh/blob/flapjack/the-bureau/about-steve-antonakes/index.html#L17
