### ISSUE TITLE
Normalize global vs single-section templating scheme

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#707]
Since this was talked about recently, I thought I'd open an issue for wider discussion. In addition to https://github.com/cfpb/cfgov-refresh/issues/597 we have two categories of includes: Those used in single sections of the site and those used across sections. It seems clear that the cross-section includes (such as `_includes/templates/header.html`) be in the `_includes` directory. However, it's less clear where the templates specific to a section should be located. Right now we have a mix of many schemes:

- **Arbitrary prefixed global include.** Includes that have some kind of identifier of where it's used, but it doesn't follow a URL or other scheme to identify where. Such as `_includes/leadership-calendar-table.html`, which is only used on `/the-bureau/leadership-calendar`. 
- **Arbitrary prefixed section include.** Includes that don't have any special prefixing and rely on their file location to convey where they're used. Such as `events/request-a-speaker/_faq.html`
- **Section prefixed section include.** Includes that are prefixed with their section and appear in their root section directory. Such as `events/_event.html`.
- **Section prefixed, postfixed type section include.** Includes that are prefixed with their section and postfixed with the type of include (macro or template) and that also appear in their root section directory. Such as `events/_event-post-macros.html`.
- **Type prefixed section include.** Includes that are prefixed with their type and included in their root section directory. Such as `careers/_template-block-social.html`

**Comment by KimberlyMunoz** [comment]
Would you say that our atomic design method resolves this issue? @anselmbradford

**Comment by anselmbradford** [comment]
Yeah, we'll have cleanup after April that may run into this, but we can re-find it.
