### ISSUE TITLE
CFPB_2Tone_isolated_RGB_352 is unused

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#721]
This image https://github.com/cfpb/cfgov-refresh/blob/flapjack/static/img/CFPB_2Tone_isolated_RGB_352.png appears to be unused. Can it be deleted? cc @Scotchester

**Comment by Scotchester** [comment]
I can't remember what this might've been used for. I suppose if it's not being referenced anywhere, might as well delete it.
