### ISSUE TITLE
Normalize image sizing

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#722]
These portrait images are set to 155px wide in the HTML, with source images of 480px wide:
https://github.com/cfpb/cfgov-refresh/blob/flapjack/the-bureau/about-rich-cordray/index.html#L30
https://github.com/cfpb/cfgov-refresh/blob/flapjack/the-bureau/about-steve-antonakes/index.html#L28

These portrait images are set to 60px wide in the HTML, with source images of 90px wide:
https://github.com/cfpb/cfgov-refresh/blob/flapjack/the-bureau/about-rich-cordray/index.html#L55
https://github.com/cfpb/cfgov-refresh/blob/flapjack/the-bureau/about-steve-antonakes/index.html#L50

These portrait images are set to 125px to 80px wide in the media_image [component override](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/pages/bureau.less#L74-L76), with a source image of 460px:
https://github.com/cfpb/cfgov-refresh/blob/flapjack/the-bureau/index.html#L175
https://github.com/cfpb/cfgov-refresh/blob/flapjack/the-bureau/index.html#L189

The [media component image sizing](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/media.less#L174-L183) sets image sizes, but the source images are the actual size set in the CSS, not double the size, so they aren't delivering 2x sizes for, e.g., retina displays.

@sebworks suggested in [this comment](https://github.com/cfpb/cfgov-refresh/commit/8741a151fc587709973fbf047fe016a72475e409#commitcomment-12035665) to add some base image sizing CSS that is applied based on a suffix on the image filename.

**Comment by anselmbradford** [comment]
See also https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/pages/careers.less#L6-L12

**Comment by KimberlyMunoz** [comment]
@duelj-- This is something else you might want to consider as you categorize patterns. We're having to create multiple classes for different scaling patterns for images. A little bit of standardization on that could help us.

**Comment by anselmbradford** [comment]
See also https://github.com/cfpb/cfgov-refresh/pull/833#discussion_r36013615

**Comment by duelj** [comment]
Sounds good, I will make sure I note that, would love to hear if there is a recommendation from the FEWDs on how we might standardize. I notice some of the examples are in circles some aren't. Would that impact how we standardized?

**Comment by KimberlyMunoz** [comment]
The circle images we use are already cropped for us with the circle border, so that shouldn't affect the standardization.

We can come up with a list of different sizes we support. I think it's the four above and a few more that we already have written classes for.

**Comment by KimberlyMunoz** [comment]
Looks like [we have](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/media.less)
- 60px on desktop & mobile
- 80px on desktop & mobile
- 100px on desktop & mobile
- 150px on desktop & mobile
- 155px on desktop & mobile
- 150px on desktop & 130 on mobile

**Comment by Scotchester** [comment]
Probably should survey what's live or coming soon in places like Owning a Home, You Have the Right, Youth Financial Education, Know Before You Owe (Realtors), etc.

Also worth noting that actual rendered size may be constrained by column widths and that values in CSS/filenames many not be representative of the end result.

**Comment by anselmbradford** [comment]
See also jira task DF-1292

**Comment by duelj** [comment]
@KimberlyMunoz the sizes you listed are interesting but without the context of where they are its hard to get a grasp on standardizing them. From the design standpoint I think we really only have three image formats right now (with flexible sizes)

* Hero image - flexible sizes and open discussion around different images for different breakpoints 
* Inline 16:9 - thumbnails, feature images, event maps, etc. Sizes vary on use case but the ratio we agreed on.
 * The portraits on the bio pages are a unique format currently and would be nice to being inline with what we are doing elsewhere
* Circles - desktop = 150px tablet & mobile = 130px ( I know that the leadership modules in the Bureau section are unique instances and would be nice to bring them inline with this format)

Are there cases I am missing? Can a model like this work for FEWDs? Are there any other thoughts that @ajbush of @schaferjh  have?

**Comment by KimberlyMunoz** [comment]
All those image sizes above were just circles, not hero images or maps.

On Tue, Aug 11, 2015 at 10:58 AM, Justin James <notifications@github.com>
wrote:

> @KimberlyMunoz <https://github.com/KimberlyMunoz> the sizes you listed
> are interesting but without the context of where they are its hard to get a
> grasp on standardizing them. From the design standpoint I think we really
> only have three image formats right now (with flexible sizes)
>
>    - Hero image - flexible sizes and open discussion around different
>    images for different breakpoints
>    - Inline 16:9 - thumbnails, feature images, event maps, etc. Sizes
>    vary on use case but the ratio we agreed on.
>       - The portraits on the bio pages are a unique format currently and
>       would be nice to being inline with what we are doing elsewhere
>    - Circles - desktop = 150px tablet & mobile = 130px ( I know that the
>    leadership modules in the Bureau section are unique instances and would be
>    nice to bring them inline with this format)
>
> Are there cases I am missing? Can a model like this work for FEWDs? Are
> there any other thoughts that @ajbush <https://github.com/ajbush> of
> @schaferjh <https://github.com/schaferjh> have?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cfpb/cfgov-refresh/issues/722#issuecomment-129918712>.
>



-- 

*Kimberly Muñoz*

kimberlymunoz.com | kimberlymunoz@gmail.com

**Comment by duelj** [comment]
I believe that although we are still in progress our plan is to simplify the circle illustration sizes to the specs from my pervious post. The ones that do not follow those guidelines will probably require a bit of design & coding attention if we are going to tweak retroactive patterns. @schaferjh does that sound right?

**Comment by schaferjh** [comment]
@duelj yes, that sounds right. 
@KimberlyMunoz just to make sure I'm understanding [your post] (https://github.com/cfpb/cfgov-refresh/issues/722#issuecomment-127402827): do have circle images displaying at all these sizes on beta right now, or do we have considerations for all these sizes in the beta code right now?

**Comment by KimberlyMunoz** [comment]
Closing this since we've managed to take care of it with our new molecular approach.

**Comment by anselmbradford** [comment]
Woo!
