### ISSUE TITLE
grunt build errors on jenkins server

### ISSUE THREAD

**Issue by rosskarchner** [cfpb/cfgov-refresh#741]
Do these errors make any sense?

https://gist.github.com/rosskarchner/a60f9e675ec8c83aa74d

**Comment by KimberlyMunoz** [comment]
Is this on Beta?

**Comment by rosskarchner** [comment]
it's on the jenkins server-- where we'll build the site, and then push just the results to the two beta servers

**Comment by rosskarchner** [comment]
I'm using the latest release (3.0.0-1.2.2)

**Comment by rosskarchner** [comment]
I've made some progress-- apparently the default on that server is node 0.10-- but 0.12 is available.

**Comment by kurtw** [comment]
Is gyp installed? Is the gyp module in the sys.path?

**Comment by rosskarchner** [comment]
yeah-- it seems like it just didn't work with 0.10.0

I'm now working through building the deployable artifact, without node_modules, Gruntfile, and other noise that isn't needed on the server. I'll close this.
