### ISSUE TITLE
DoubleClick Access denied error on IE11, Win7

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#751]
First, what code is introducing doubleclick.net tracking code?
Second, on IE11 (Win7) beta.cf.gov is throwing an `Access is denied` console error for activityi file coming from DoubleClick.

**Comment by Scotchester** [comment]
Google Analytics.

**Comment by KimberlyMunoz** [comment]
Tagging in @mistergone to weigh in.

**Comment by anselmbradford** [comment]
Not able to reproduce
