### ISSUE TITLE
Filters broken on IE11, Win7 - from shallow-extend

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#752]
Sorry to report :-/ but this crashes in the dev console and shows a Webpage Error dialog box when dev console is closed.

To repeat:
- Open saucelabs IE11, Win7 VM.
- Navigate to /blog
- Open dev console.
- Open filters, select a checkbox, and click apply.
- Observe site crash:
<img width="1112" alt="screen shot 2015-07-14 at 12 01 36 pm" src="https://cloud.githubusercontent.com/assets/704760/8678066/7ce5d258-2a20-11e5-836f-7f132b472f7c.png">

Appears to be originating from https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/util/shallow-extend.js#L30

**Comment by contolini** [comment]
Try replacing `toString.call( object )` with `({}).toString.call( object )` at [L15](https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/util/shallow-extend.js#L15). See http://stackoverflow.com/a/19321984.
