### ISSUE TITLE
Input validation failing on IE8

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#758]
Currently all input validation is failing on IE8. Validate.js is using `map` and `filter` Array methods which aren't supported by IE8.  

To repeat:
- Open saucelabs IE8, Win7 VM or (using virtual machine)
- Navigate to /blog
- Open dev console.
- Open filters, enter `04/11/2000` in the `From` field.

![ie8](https://cloud.githubusercontent.com/assets/1696212/8698460/72e25aae-2acc-11e5-8fd4-c433507c008d.png)

**Comment by ascott1** [comment]
For a quick fix, MDN has Polyfills for both `map` and `filter`:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map#Polyfill
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#Polyfill
