### ISSUE TITLE
Mega Menu Refactoring 

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#760]
This is a list of issues which need to be addressed with the mega menu nav and hamburger nav. 
## JS related Issues:
- [x] JS is not modular, uses jquery, and contains unnecessary code ( Ideally we would have a base nav class or plugin that all other navs would extend )
- [ ] Currently video doesn't auto-play but imagery suggest that it should.

## CSS related Issues:
- [x] CSS is not modular and isn't adhering to standards.
- [x] Should be using translate instead of using margin/left/etc... to animate. (http://www.paulirish.com/2012/why-moving-elements-with-translate-is-better-than-posabs-topleft/)
 - [x] `.primary-nav_top-level-list.list-expanding` sub classes are already nested and don't need `&`. 
-  [x] Should be able to use `.primary-nav .list_link ` to style links there by making ` .sub-nav_menu-list .list_link` unneccessary.

## Design related issues:
- [x] Spacing is tall when wrapping to new line: 
<img width="474" alt="screen shot 2015-07-14 at 2 20 27 pm"    src="https://cloud.githubusercontent.com/assets/704760/8681116/93eb8f7a-2a33-11e5-815c-9a05f0fcbe31.png">
- [x] The `About Overview` is styled almost identical to the menu links in not a link.
<img width="805" alt="screen shot 2015-07-15 at 9 42 28 am" src="https://cloud.githubusercontent.com/assets/1696212/8699768/da44b594-2ad5-11e5-911f-d3d0cb806e8f.png">

## Copy related issues:
- [ ]  Copy could be a better call to action, something like "Watch our short video to learn about the CFPB and how we go to work for you."

<img width="400" alt="screen shot 2015-07-15 at 9 43 48 am" src="https://cloud.githubusercontent.com/assets/1696212/8699794/0f6bc6ae-2ad6-11e5-99fe-33f5b3e31bf0.png">

**Comment by KimberlyMunoz** [comment]
Some extra issues:
Keyboard navigability.
- [ ] This should be navigable by keyboard. Anything you tab-to should be visible.
- [ ] Sometimes while keyboard navigating, you get something like this when you hit enter on the menu
![image](https://cloud.githubusercontent.com/assets/1860176/8736811/d30a3b90-2be9-11e5-994b-01c392f59dc3.png)
- [ ] The hover state for the video is a little funky and something in the alt text should indicate it's a video.

![image](https://cloud.githubusercontent.com/assets/1860176/8736847/25e36b7a-2bea-11e5-8ace-1b99166807d7.png)

**Comment by KimberlyMunoz** [comment]
Good link on making the mega menu accessible. http://terrillthompson.com/blog/474
