### ISSUE TITLE
Decision point: sheer to django transition

### ISSUE THREAD

**Issue by rosskarchner** [cfpb/cfgov-refresh#804]
Hi everyone!

it's looking like the soonest we'll be able to switch beta over to Django will be mid-august. I think that gives us a few different options for how to proceed.

a) Wait until mid-august (or whenever) to start using Django for local development and the flapjack/refresh demo servers.
b) Make the switch soon, and freeze beta until it can be switched to the new stack
c) Make the switch soon, but take care to not break compatibility with Sheer (so, not taking advantage of the new abilities Django gives us, like more server side logic).

"c" seems like a bad idea to me, but I didn't want to take it off the table.

**Comment by jimmynotjim** [comment]
I vote for a, mostly because Kurt is on vacation next week and I'm gone the following week. Sprint 34 should start Aug 12 and would probably be perfect.

**Comment by dpford** [comment]
@jimmynotjim makes a good point, but I'm leaning b.  The current Django setup is pretty solid, and I don't think you guys missing some time will necessarily derail the switchover.

**Comment by jimmynotjim** [comment]
That works too, just wasn't sure what work was going to be necessary from the rest of us :+1:
