### ISSUE TITLE
Make table row click `mousedown` or `click` event

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#811]
Moved from https://github.com/cfpb/cfgov-refresh/pull/803

https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/js/modules/simple-table-row-links.js#L15 uses a `mousedown` event. Should this be a `click` event like how the links behave? The downside is if a mousedown and drag happens, the wrong link may trigger. cc @schaferjh

**Comment by jimmynotjim** [comment]
I'd definitely prefer a click because that's the expected behaviour of links. I tried to right click the link to inspect it, and it opened the page. The same would happen if someone were to cmd+click to open in a new window.

**Comment by schaferjh** [comment]
ooooo, agree with @jimmynotjim if click allows mouse-experts to right/cmd click to their hearts' content.

**Comment by anselmbradford** [comment]
Added PR at https://github.com/cfpb/cfgov-refresh/pull/816

Note this doesn't behave exactly how regular links work. The right-click will work fine, but if you hold down the command key and click a link it'll open in a new tab. However, the parts of the table row that aren't actual links (closing date and location) will open the link in the same window. I think to emulate the same behavior the JS would need to listen for a keypress event and track whether the command key was pressed and then open in a new tab if it was. Let me know if this is behavior that should be added to the backlog to implement.

**Comment by anselmbradford** [comment]
Opened https://github.com/cfpb/cfgov-refresh/issues/819 for https://github.com/cfpb/cfgov-refresh/issues/811#issuecomment-125639317
