### ISSUE TITLE
Current openings careers table silently has active links at mobile size

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#812]
`/careers/current-openings/` has a table with clickable rows. When at mobile size, the rows are still clickable (the closing date and location), but only the title is styled as a clickable link.

<img width="602" alt="screen shot 2015-07-27 at 4 27 05 pm" src="https://cloud.githubusercontent.com/assets/704760/8916864/594053f8-347c-11e5-8609-1a49013a4e0c.png">

Should:
 a. there be some kind of visual feedback on the closing date and location text?
 b. the closing date and location fields not be clickable at mobile size?
 c. be left as fine as is. If a user is clicking any field of the posting they should be taken to the job details, even if there's no visual feedback.

cc. @schaferjh

**Comment by schaferjh** [comment]
I lean toward option b -- ideally only things that look clickable should be clickable. 

(I'm sure I've contradicted that ideal at some point but still...)

**Comment by KimberlyMunoz** [comment]
Design Manual is looking at potentially depreciating this. 

https://github.com/cfpb/design-manual/issues/153

**Comment by KimberlyMunoz** [comment]
Still an issue, but the table has changed looks.

![image](https://cloud.githubusercontent.com/assets/1860176/13893371/19b40510-ed34-11e5-8b84-0c03367279fe.png)

**Comment by anselmbradford** [comment]
This table has changed on careers
