### ISSUE TITLE
Sprint 32, part 2 issues

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#823]
This is a list of issues which that emerged as a result of the Sprint 32-2 PR review.
- [x] Double borders on stacked expandables
  <img width="319" alt="screen shot 2015-07-28 at 5 43 55 pm" src="https://cloud.githubusercontent.com/assets/1280430/8944745/5aeebd82-3550-11e5-992a-746fd0858c10.png">

- [x] Individual career postings should have 'Careers / Current Openings' breadcrumb 

- [x] Alternating borders are weird on small screens (simple table styles are adding background to the first `td`)

 <img width="482" alt="screen shot 2015-07-28 at 5 54 30 pm" src="https://cloud.githubusercontent.com/assets/1280430/8944994/ced627b6-3551-11e5-9e81-8c67705d6672.png">

- [ ] The content footer on the offices pages should have a top and right border
 <img width="965" alt="screen shot 2015-07-28 at 5 24 34 pm" src="https://cloud.githubusercontent.com/assets/1280430/8944251/8d9cc3c6-354d-11e5-8a8a-150a3ee9bec0.png">

- [x] Images don't seem to be loading on IE8
 <img width="675" alt="screen shot 2015-07-27 at 6 37 00 pm" src="https://cloud.githubusercontent.com/assets/1860176/8919580/8b9caf4c-348e-11e5-9e13-c3c41189c547.png">

**Comment by KimberlyMunoz** [comment]
> Individual career postings should have 'Careers / Current Openings' breadcrumb 

This is one is in the backlog (DF-2241) along with breadcrumbs for the blog and newsroom.

**Comment by anselmbradford** [comment]
> Images don't seem to be loading on IE8

Covered in 
https://github.com/cfpb/cfgov-refresh/issues/964

**Comment by anselmbradford** [comment]
Are the last two issues in here still issues?

**Comment by KimberlyMunoz** [comment]
The only thing that seems like an issue is the border on tables thing.

**Comment by schaferjh** [comment]
I actually don't see the table border issue any longer --

![screen shot 2016-05-27 at 10 52 14 am](https://cloud.githubusercontent.com/assets/10562545/15611680/86f9ef94-23f9-11e6-90e5-75d08fce330c.png)

**Comment by KimberlyMunoz** [comment]
Oh, then it's all fixed. Thanks for checking Jess!
