### ISSUE TITLE
Is gulp-load-plugins using `$` a convention?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#830]
`gulp-load-plugins` is mascarading as jquery in [our gulp tasks](https://github.com/cfpb/cfgov-refresh/blob/flapjack/gulp/tasks/test.js#L4). Is this a convention? It doesn't appear to be according to the plugin [GH repo](https://github.com/jackfranklin/gulp-load-plugins#usage).

**Comment by KimberlyMunoz** [comment]
@jimmynotjim, now that you're back. Could we change this to something else?

**Comment by jimmynotjim** [comment]
Sure, looking at the docs, their recommendation is to use `plugins` instead. I think I picked up `$` from a tutorial when I first started using Gulp a while back.
