### ISSUE TITLE
Refactor cf-notifications for simpler unit tests

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#832]
- [ ] Refactor cf-notifications so test fixtures aren't necessary.
- [ ] Remove https://github.com/cfpb/cfgov-refresh/blob/flapjack/test/unit_tests/fixtures/forms.html

**Comment by jimmynotjim** [comment]
CF Notifications are moving out of this project, these tests should just be removed entirely.

**Comment by richaagarwal** [comment]
I think this can be closed, ya? @jimmynotjim @anselmbradford

**Comment by jimmynotjim** [comment]
Notifications were changed completely, there's an empty unit test for the new ones at https://github.com/cfpb/cfgov-refresh/blob/flapjack/test/unit_tests/molecules/Notification-spec.js

**Comment by sebworks** [comment]
We no longer use `cf-notifications` so I'm going to close this issue.
