### ISSUE TITLE
Add `block__flush` to cf-enhancements

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#838]
For blocks that have flush sides, bottom, and top there should be a `block__flush` modifier.

See https://github.com/cfpb/cfgov-refresh/pull/833#discussion_r36017486

**Comment by jimmynotjim** [comment]
So just combining the existing `block__flush-sides`, `block__flush-top` and `block__flush-bottom`?

**Comment by anselmbradford** [comment]
That's right. We have `block__border`, not only does it seem like a gap that `flush` wouldn't follow the same pattern, but we also have places where all three flush classes are used.

**Comment by KimberlyMunoz** [comment]
@anselmbradford did the PR for this go in already?

**Comment by anselmbradford** [comment]
No, this is still open. Should go in https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/cf-enhancements.less#L1253
