### ISSUE TITLE
Make setup.sh clear /dist/ contents as opposed to removing the directory

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#847]
With setup.sh removing /dist/ repeatedly, it sometimes leads to Sheer not knowing what directory it's in. To see if it helps, the script should clear the contents of the /dist/ directory, not remove the directory.

**Comment by jimmynotjim** [comment]
We should make the same change to the Gulp task when this is done. I set that up to match `setup.sh` (luckily it's pretty easy to switch it).
