### ISSUE TITLE
Event: Comma included in street address span, leading to weird wrapping

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#848]
See `/events/field-hearing-on-payday-lending/`

<img width="341" alt="screen shot 2015-08-04 at 11 16 31 am" src="https://cloud.githubusercontent.com/assets/704760/9064424/6eccd358-3a9a-11e5-99f6-55aaaa0525c8.png">

**Comment by lerenah** [comment]
I'd like to work on this issue.

**Comment by lerenah** [comment]
I'm having a hard time getting the environment set up.  So, I'm going to focus on another issue for now.

**Comment by adamjubert** [comment]
I'll take a look at this issue.

**Comment by anselmbradford** [comment]
@adamjubert It being a 3 year old issue it certainly has changed, thanks for catching it. The archived event is at https://www.consumerfinance.gov/about-us/events/archive-past-events/field-hearing-on-payday-lending/, which does not have the issue shown in the screenshot. I'm not sure what updated it, but I think we can close this and re-open if needed. (cc @schaferjh )
