### ISSUE TITLE
office/subpage forms telephone id name appears wrong

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#852]
Form telephone field has name `telephone_number`, while the `for` attribute value in the associated label 
is `telephone-number`.

See:

https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/_includes/templates/forms/amending-and-correcting-records-under-the-privacy-act-form.html#L82

https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/_includes/templates/forms/file-a-privacy-complaint-form.html#L86

**Comment by KimberlyMunoz** [comment]
These forms are gone.
