### ISSUE TITLE
Remove or update processor unit tests

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#860]
According to @kurtw the [processor tests](https://github.com/cfpb/cfgov-refresh/tree/flapjack/test/processor_tests/tests) are outdated. Currently none of them are running when the task is run. They should either be updated or removed.

**Comment by KimberlyMunoz** [comment]
I vote for scraping them.

**Comment by kurtw** [comment]
Yeah let's delete them.
