### ISSUE TITLE
Move process.env to global project configuration file.

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#861]
See guidance in https://github.com/eslint/eslint/blob/master/docs/rules/no-process-env.md#when-not-to-use-it

We should have a config/settings file in `./config/` that maps environment variables (and potentially other sources of project variables) to parameters that are then accessed through the project. This de-couples the source of global variables.

**Comment by anselmbradford** [comment]
Note that `./config/` should only be for build configuration, see https://github.com/cfpb/cfgov-refresh/pull/866#issuecomment-130062362

**Comment by anselmbradford** [comment]
Examples of process.env:

https://github.com/cfpb/cfgov-refresh/blob/f1996a3d3301dcf84f18ebe934dbec97549853bf/test/browser_tests/environment.js

https://github.com/cfpb/cfgov-refresh/blob/37e6388435c12e3ea8b2b828eb5d16b78b3b7eaf/test/browser_tests/jenkins_conf.js

**Comment by jimmynotjim** [comment]
Add the latest changes to the main conf.js file as well

**Comment by anselmbradford** [comment]
Some have been moved here https://github.com/cfpb/cfgov-refresh/blob/master/config/environment.js#L11-L25
