### ISSUE TITLE
Broken link on legacy strategy plan

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#867]
1. Visit `/budget/strategic-plan/interactive/`
2. Click `THE CFPB STRATEGIC PLAN, BUDGET, AND PERFORMANCE PLAN AND REPORT` link.
3. Get 404 for `/strategic-plan-budget-and-performance-plan-and-report/`

**Comment by KimberlyMunoz** [comment]
The print button is also broken.

**Comment by KimberlyMunoz** [comment]
According to Steven, the content is coming from the CMS.  https://github.com/cfpb/cfgov-refresh/pull/870#issuecomment-130069804

**Comment by anselmbradford** [comment]
The print button URL is okay on beta because it's accessing files.consumerfinance.gov. We may want to update it to an absolute URL... not sure what the tradeoff is there.

**Comment by KimberlyMunoz** [comment]
Both links expect to be linking to consumerfinance.gov right now. 

http://www.consumerfinance.gov/strategic-plan-budget-and-performance-plan-and-report/
http://www.consumerfinance.gov/f/strategic-plan.pdf

There's a couple solutions:

1. We could leave it be and take care of it when we create redirect links for the stuff currently on www. (Assuming that we are doing that for all the blog posts that are linking to things with the current site structure!)
2. Fix it to point to www
3. Write JS to conditionally fix on beta only.

I'm leaning towards confirming that 1. is an option and possibly closing this issue.

**Comment by anselmbradford** [comment]
1 sounds good. As an aside if I recall correctly anything with a `/f/` is copied to files.cf.gov on a cron job,  so http://files.consumerfinance.gov/f/strategic-plan.pdf is the AWS source we'd want to point to for PDFs (cc @dpford).

**Comment by KimberlyMunoz** [comment]
Fixed in the new section.
