### ISSUE TITLE
remove gulp-jshint

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#876]
Check and remove [gulp-jshint](https://github.com/cfpb/cfgov-refresh/blob/flapjack/package.json#L24). It doesn't seem needed?

**Comment by jimmynotjim** [comment]
Whoops, thanks for catching this, it can definitely be removed. I'm not even sure why I included it (probably the initial investigation phase) since we've been using eslint for quite a while.
