### ISSUE TITLE
Analyze Javascript to reduce size

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#881]
common.min.js is currently at 900kb ( there are currently things erroneously included / not minified ). Based on the scope, complexity, and goals for the project, we should try to reduce the size to 200kb.

**Comment by jimmynotjim** [comment]
It's going to be hard when we package all the libraries together. I'd say our own JS should be below 200kb, but when jQuery alone is 90kb, getting everything under is going to be difficult. Hopefully this will be resolved when we can break out scripts with browsersync.

**Comment by anselmbradford** [comment]
`common.js` is now 133KB per https://github.com/cfpb/cfgov-refresh/pull/968 
Is there more to do in this issue?

**Comment by sebworks** [comment]
I would love to remove the jQuery dependency but that probably isn't V1.
