### ISSUE TITLE
GovDelivery key appears to be required

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#898]
https://github.com/cfpb/cfgov-refresh/blob/flapjack/INSTALL.md#govdelivery says:

> The application will function but throw an error if the GovDelivery environment variables are not set in the Project Configuration.

However, with the environment variable `GOVDELIVERY_USER` blank I'm not able to start Sheer and get a key error for `KeyError: 'GOVDELIVERY_USER'`.

Test that this is actually the case. E.g. does it matter if the key is blank vs not being set. And update `INSTALL.md` to reflect the findings.

**Comment by anselmbradford** [comment]
cc @dpford @kurtw

**Comment by anselmbradford** [comment]
Actually, ideally the site would function without these set and just the email subscriptions wouldn't work.

**Comment by anselmbradford** [comment]
https://github.com/cfpb/cfgov-refresh/blob/flapjack/INSTALL.md#4-project-configuration also says:
> `WORDPRESS` is the only one that’s absolutely necessary to run the site.

**Comment by jimmynotjim** [comment]
@KimberlyMunoz do you remember why this one was closed https://github.com/cfpb/cfgov-refresh/issues/250? I didn't think we every officially tested it.

**Comment by KimberlyMunoz** [comment]
I was testing it as I cleared out my folder one time and it didn't seem necessary. Was it tested with no GovDelivery_User instead of a blank one?

Although, tbh this really doesn't seem like something worth testing given the move to a new CMS.

**Comment by jimmynotjim** [comment]
I've run the project with the default `.env` file without issues. I think we can safely say it's no longer required.
