### ISSUE TITLE
Refactor _filter_checkbox helper macro to include <label>?

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#918]
See https://github.com/cfpb/cfgov-refresh/pull/915#discussion_r37347537

This is a private helper macro for the filters, so it seems like it could include the enclosing `<label>` that surrounds it everywhere it's called.

**Comment by KimberlyMunoz** [comment]
Yes. Let's do it. It should be a small task.

**Comment by KimberlyMunoz** [comment]
Looks like @anselmbradford's refactor of the filter does this.
