### ISSUE TITLE
Update instructions to be clearer about clean, build, watch tasks

### ISSUE THREAD

**Issue by jimmynotjim** [cfpb/cfgov-refresh#922]
Because we can't build then watch (see #912), we need to make sure it's clear that a build kickoff is required after cloning the repo or running the clean task, prior to watching.

**Comment by anselmbradford** [comment]
Perhaps just update https://github.com/cfpb/cfgov-refresh/blob/flapjack/README.md#4-launch-the-gulp-watch-task to be:

```
gulp build
gulp watch
```

Also, removed the `$`, as it seems like we removed that from everywhere else.
