### ISSUE TITLE
Add required asterisk on forms via CSS content attribute

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#927]
See https://github.com/cfpb/cfgov-refresh/pull/915#discussion_r37441686

**Comment by KimberlyMunoz** [comment]
This might not be necessary depending on what we hear back from @sarahsimpson09.

**Comment by KimberlyMunoz** [comment]
I think #942 should cover this one.

**Comment by KimberlyMunoz** [comment]
Closed via #942
