### ISSUE TITLE
Replace class based js/qa hooks with data attribute hooks

### ISSUE THREAD

**Issue by sebworks** [cfpb/cfgov-refresh#930]
Currently we are using `js-*` and `qa-*` class based hooks for dom manipulation and testing. We should use data attributes instead and only use classes for styles. 

`<div class='js-youtube'` would become `<div data-js-hook='youtube'`

`<div class='qa-youtube'` would become `<div data-qa-hook='youtube'`

**Comment by jimmynotjim** [comment]
Quick question, can you have multiple values in an attr? I thought you couldn't, making something like `data-js-hook="hook-1 hook-2"` impossible because it's treated as a single value.

**Comment by sebworks** [comment]
https://css-tricks.com/multiple-attribute-values/

**Comment by himedlooff** [comment]
I'm curious what the benefit is.

**Comment by sebworks** [comment]
The benefit is a separation of concerns (i.e. css is only for styling). There is a performance hit with this approach which should be considered. 

There is a good article on the subject at http://toddmotto.com/data-js-selectors-enhancing-html5-development-by-separating-css-from-javascript/

**Comment by himedlooff** [comment]
I don't feel too strongly about this but I do feel strongly about saying "classes are only for styling". They have some semantic meaning which helps to identify and select certain nodes in the tree.

**Comment by sebworks** [comment]
I wasn't trying to imply that they didn't have some semantic meaning. I just want us to avoid situations like the following (copied from youtube.com) :  

`<script src="//s.ytimg.com/yts/jsbin/spf-vflbit-XM/spf.js" type="text/javascript" name="spf/spf" class="js-httpssytimgcomytsjsbinspfvflbitXMspfjs"></script>`

**Comment by himedlooff** [comment]
![70s-head-shake-point](https://cloud.githubusercontent.com/assets/1093373/9550028/eec55b68-4d76-11e5-9f29-8fbfcd04a7ad.gif)

Wow that is..... something else! ha.

**Comment by anselmbradford** [comment]
Update in https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/offices/_single.html, e.g. https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/offices/_single.html#L113

**Comment by anselmbradford** [comment]
And https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/_includes/macros/activities-block.html#L22

**Comment by anselmbradford** [comment]
I can't find any `js-` classes anymore and the last `qa-` class will be removed in https://github.com/cfpb/cfgov-refresh/pull/2119 ... closing this.

> Quick question, can you have multiple values in an attr? I thought you couldn't, making something like data-js-hook="hook-1 hook-2" impossible because it's treated as a single value.

Woot! We have this now in https://github.com/cfpb/cfgov-refresh/blob/flapjack/cfgov/unprocessed/js/modules/util/data-hook.js
