### ISSUE TITLE
CSS banner is mangled after minification

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#951]
The CSS banner should be built so that it survives minification. Possibly it should be added post-minifying.

<img width="455" alt="screen shot 2015-09-03 at 2 59 57 pm" src="https://cloud.githubusercontent.com/assets/704760/9667901/93750558-524c-11e5-80f9-1c9bf86486a6.png">

**Comment by KimberlyMunoz** [comment]
Would you say this is a `bite-size` issue?

**Comment by jimmynotjim** [comment]
It's not minification, it looks like the system is replacing `′` with `â€²`, but I can't replicate it locally.

![screen shot 2015-09-08 at 6 09 59 am](https://cloud.githubusercontent.com/assets/1280430/9733422/bdac23c2-55f0-11e5-818f-1144c606a07c.png)

**Comment by Scotchester** [comment]
@anselmbradford, what is that screenshot taken from?

**Comment by anselmbradford** [comment]
@jimmynotjim good catch @Scotchester http://beta.consumerfinance.gov/static/css/main.css

**Comment by anselmbradford** [comment]
http://flapjack.demo.cfpb.gov/static/css/main.css is wonky:

![screen shot 2015-09-25 at 5 49 45 pm](https://cloud.githubusercontent.com/assets/704760/10112970/d49a5192-63ad-11e5-9c66-45b1bf8eb007.png)

**Comment by KimberlyMunoz** [comment]
Thanks for reopening. I just noticed it today. What if we went back to the OaH dollar sign banner?

**Comment by KimberlyMunoz** [comment]
Closed by #1142.
![image](https://cloud.githubusercontent.com/assets/1860176/11133369/7e42f188-8963-11e5-9341-7ff2baef705d.png)
