### ISSUE TITLE
IE8 - Videos won't play

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#962]
Steps to reproduce:

1. Go to a video page like http://flapjack.demo.cfpb.gov/the-bureau in IE8
2. Click play
3. Get the following screen and no video :disappointed: 

![novideo](https://cloud.githubusercontent.com/assets/1860176/9740971/a78e0d5a-5625-11e5-9672-fb1fde082e9d.png)

**Comment by anselmbradford** [comment]
@KimberlyMunoz Can you re-test this? It works for me:

![screen shot 2015-09-25 at 5 41 16 pm](https://cloud.githubusercontent.com/assets/704760/10112901/11f4e44a-63ad-11e5-9b10-58cd8337fdd7.png)

Localhost redirects to youtube, flapjack plays it embedded. The preview image is a bit wonky.

**Comment by sebworks** [comment]
I'm seeing the same as you @anselmbradford. I'll fix the issue with the white bar.

**Comment by KimberlyMunoz** [comment]
It might be a localhost thing. I'll assign it to myself to retest it.
