### ISSUE TITLE
IE8 - Images are not showing up on IE8

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cfgov-refresh#964]
Affected pages:
- http://flapjack.demo.cfpb.gov/careers/application-process/
- http://flapjack.demo.cfpb.gov/the-bureau/about-director/

When visiting these pages, the images aren't showing up.

![where in the world is rich cordray](https://cloud.githubusercontent.com/assets/1860176/9741439/7be056ba-5628-11e5-95b5-511cc38b983a.png)

**Comment by anselmbradford** [comment]
Appears to be IE8 not liking `max-width: 100%` on the image and not the container. 

http://stackoverflow.com/questions/3915219/max-width-on-img-tag-not-working-in-ie8

**Comment by sebworks** [comment]
closing, we no longer support IE8 in any capacity.
