### ISSUE TITLE
Make about-us href active and preventDefault via JS

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#967]
https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/_includes/templates/nav/primary-nav.html#L20 Sets the href to `#`. The TODO comment says to change this to a button, however, it seems like this should remain a link with an href to `/about-us/` as a fallback. The default behavior can then be prevented via JS when the megamenu shows, or the href can be removed on page load.

**Comment by jimmynotjim** [comment]
I think this makes sense
