### ISSUE TITLE
Check and remove h4 on budget CSS

### ISSUE THREAD

**Issue by anselmbradford** [cfpb/cfgov-refresh#981]
Budget pages don't appear to have h4's, but their stylesheet does:

https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/pages/budget.less#L10

https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/pages/budget.less#L16

Verify that these aren't needed and remove them from the CSS.

**Comment by KimberlyMunoz** [comment]
This is just part of the general budget page refactor. That whole page doesn't have blocks or the same stuff from capital framework.

**Comment by KimberlyMunoz** [comment]
Budget pages have moved to wagtail!
